-- ============================================================================
-- Apocrypha seed — 70+ documents + 中文 1 / 英文 placeholders + 原文 placeholders
-- Sources: 基督教典外文獻 (王曉朝主編，CCLC 10 卷) + Charlesworth APOT/OTP +
--          Schneemelcher NT Apocrypha + Robinson Nag Hammadi
-- ============================================================================

-- ── Documents ───────────────────────────────────────────────────────────────
INSERT INTO apocrypha_documents
  (slug, title_zh, title_zh_short, title_en, title_orig,
   category, testament, language_orig,
   composition_low, composition_high, canon_status_jsonb,
   summary_zh, display_order)
VALUES
-- ============================================================================
-- OT APOCRYPHA / DEUTEROCANON 次經 / 第二正典 (display 100-199)
-- ============================================================================
('tobit', '多比傳', '多比', 'Tobit', 'Τωβίτ',
 'ot_apocrypha', 'ot', 'aramaic',
 -225, -175,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true,"syriac":true}',
 '描述虔誠猶太人多比父子在尼尼微的故事；含天使拉斐爾介入婚姻、驅魔等元素。羅馬天主教與東正教列為第二正典。',
 110),

('judith', '猶滴傳', '猶滴', 'Judith', 'Ἰουδίθ',
 'ot_apocrypha', 'ot', 'hebrew',
 -150, -100,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true,"syriac":true}',
 '寡婦猶滴勇斬亞述軍統帥何樂弗尼救國的故事。羅馬天主教與東正教列為第二正典。',
 115),

('esther-additions', '以斯帖補篇', '以斯帖補', 'Additions to Esther', 'τὰ τῆς Ἐσθήρ προστιθέμενα',
 'ot_apocrypha', 'ot', 'greek',
 -150, -50,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true}',
 '七篇補篇 — 加在希伯來原文以斯帖記之外的希臘文片段，包含末底改的夢、皇后的禱告等。',
 120),

('wisdom-solomon', '所羅門智訓', '智訓', 'Wisdom of Solomon', 'Σοφία Σαλωμῶνος',
 'ot_apocrypha', 'ot', 'greek',
 -100, 50,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true}',
 '亞歷山大猶太人哲學作品；融合希伯來智慧傳統與柏拉圖主義。羅馬天主教與東正教第二正典。',
 125),

('sirach', '便西拉智訓', '便西拉', 'Sirach (Ecclesiasticus)', 'Σοφία Σιραχ',
 'ot_apocrypha', 'ot', 'hebrew',
 -200, -180,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true,"syriac":true}',
 '便西拉之孫翻譯的智慧文學；51 章；新教稱「次經」；天主教與東正教為第二正典。',
 130),

('baruch', '巴錄書', '巴錄', 'Baruch', 'Βαρούχ',
 'ot_apocrypha', 'ot', 'hebrew',
 -200, -100,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true,"syriac":true}',
 '託名巴錄 (耶利米的書記) 所作；含懺悔禱詞與智慧讚詩。',
 135),

('letter-jeremiah', '耶利米書信', '耶利米書信', 'Letter of Jeremiah', 'Ἐπιστολὴ Ἰερεμίου',
 'ot_apocrypha', 'ot', 'greek',
 -300, -200,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true}',
 '託名耶利米致被擄者的信，警戒勿拜偶像。武加大版併入 Baruch 第六章，東正教獨立成卷。',
 140),

('1-maccabees', '馬加比一書', '馬加比一', '1 Maccabees', '',
 'ot_apocrypha', 'ot', 'hebrew',
 -135, -100,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true}',
 '哈斯摩尼王朝起義史 (公元前 175-134)；猶大馬加比領導反塞琉古起義。最重要的 Second-Temple 歷史文獻之一。',
 145),

('2-maccabees', '馬加比二書', '馬加比二', '2 Maccabees', '',
 'ot_apocrypha', 'ot', 'greek',
 -150, -100,
 '{"protestant":false,"catholic":true,"orthodox":true,"ethiopian":true}',
 '節錄基勒尼人耶松五卷之作；側重宗教詮釋而非編年；含復活信念早期見證。',
 150),

('3-maccabees', '馬加比三書', '馬加比三', '3 Maccabees', '',
 'ot_apocrypha', 'ot', 'greek',
 -100, -50,
 '{"protestant":false,"catholic":false,"orthodox":true,"ethiopian":false}',
 '描述托勒密四世迫害埃及猶太人的故事；東正教典外；不在天主教第二正典內。',
 155),

('4-maccabees', '馬加比四書', '馬加比四', '4 Maccabees', '',
 'ot_apocrypha', 'ot', 'greek',
 0, 100,
 '{"protestant":false,"catholic":false,"orthodox":true,"ethiopian":false}',
 '斯多葛哲學風格的講道；以馬加比殉道者為理性勝過情慾之榜樣。東正教 appendix。',
 160),

('1-esdras', '以斯拉上 (希臘文以斯拉)', '以斯拉上', '1 Esdras (Greek Ezra)', 'Ἔσδρας Αʹ',
 'ot_apocrypha', 'ot', 'hebrew',
 -200, -100,
 '{"protestant":false,"catholic":false,"orthodox":true,"ethiopian":true}',
 '另版以斯拉-尼希米故事，重整聖殿敘述；東正教接受，天主教不接受。',
 165),

('prayer-manasseh', '瑪拿西禱詞', '瑪拿西禱', 'Prayer of Manasseh', 'Προσευχὴ Μανασσῆ',
 'ot_apocrypha', 'ot', 'greek',
 -200, 100,
 '{"protestant":false,"catholic":false,"orthodox":true,"ethiopian":false}',
 '託名猶大王瑪拿西被擄至巴比倫時悔罪禱告；東正教接受。',
 170),

('psalm-151', '詩篇 151', '詩 151', 'Psalm 151', 'Ψαλμός ΡΝΑʹ',
 'ot_apocrypha', 'ot', 'hebrew',
 -300, -100,
 '{"protestant":false,"catholic":false,"orthodox":true,"ethiopian":true,"syriac":true}',
 '七十士譯本附加大衛詩篇一首；昆蘭 11Q5 含希伯來原文。',
 175),

-- ============================================================================
-- OT PSEUDEPIGRAPHA 偽典 (display 200-299)
-- ============================================================================
('1-enoch', '以諾一書', '以諾一', '1 Enoch (Ethiopic Enoch)', '',
 'ot_pseudepigrapha', 'ot', 'ethiopic',
 -300, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":true}',
 '五大部分 (Watchers / Parables / Astronomical / Dream Visions / Epistle)；新約《猶大書》引用；衣索匹亞 Tewahedo 正典。',
 210),

('2-enoch', '以諾二書 (斯拉夫語以諾)', '以諾二', '2 Enoch (Slavonic Enoch)', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '以諾遊歷七重天的異象記錄；只以斯拉夫文古抄本保存；原文可能希臘文。',
 215),

('3-enoch', '以諾三書 (希伯來語以諾)', '以諾三', '3 Enoch (Hebrew Enoch)', '',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Hekhalot 文學；猶太祭司以實瑪利登天遇梅塔特隆 (轉化的以諾)。',
 220),

('jubilees', '禧年書', '禧年', 'Jubilees', '',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 -160, -150,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":true}',
 '創世記與出埃及記重述，按 49 個禧年週期編年；昆蘭多份斷片；衣索匹亞 Tewahedo 正典。',
 225),

('test-12-patriarchs', '十二族長遺訓', '十二族長', 'Testaments of the Twelve Patriarchs', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '雅各十二子各自遺訓；倫理教導與啟示元素並存；含基督徒重編層。',
 230),

('test-job', '約伯遺訓', '約伯遺訓', 'Testament of Job', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -100, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名約伯臨終遺訓；強調忍耐受苦的德行。',
 235),

('test-3-patriarchs', '三族長遺訓 (亞伯拉罕/以撒/雅各)', '三族長', 'Testaments of Abraham/Isaac/Jacob', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '族長臨終異象與死亡敘事；天使大千個來迎接靈魂。',
 240),

('test-moses', '摩西遺訓', '摩西遺訓', 'Testament of Moses (Assumption of Moses)', '',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 0, 50,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '摩西預言以色列歷史；《猶大書》第 9 節暗引「米迦勒爭辯摩西屍體」。',
 245),

('test-solomon', '所羅門遺訓', '所羅門遺訓', 'Testament of Solomon', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 100, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '所羅門用印戒控制群魔建聖殿的故事；早期魔法傳統。',
 250),

('test-adam', '亞當遺訓', '亞當遺訓', 'Testament of Adam', '',
 'ot_pseudepigrapha', 'ot', 'syriac',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞當臨終遺訓給賽特，含天使品級論。敘利亞傳統。',
 255),

('jacob-ladder', '雅各天梯', '雅各天梯', 'Ladder of Jacob', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '創世記 28 雅各夢天梯的擴寫；只存於斯拉夫文。',
 260),

('jannes-jambres', '雅尼和佯庇書', '雅尼佯庇', 'Book of Jannes and Jambres', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '《提後》3:8 提及兩位埃及術士的傳奇故事。',
 265),

('joseph-history', '約瑟歷史', '約瑟歷史', 'History of Joseph', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '創世記約瑟故事的擴寫，重在埃及流亡與和兄弟和解。',
 270),

('aristeas', '阿立斯蒂亞書信', '阿立斯蒂亞', 'Letter of Aristeas', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, -100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '七十士譯本起源傳說 — 72 位譯者各譯一卷完全相同。',
 275),

('joseph-aseneth', '約瑟與亞西納書', '約瑟亞西納', 'Joseph and Aseneth', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -100, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '約瑟與祭司女兒亞西納的浪漫故事，著重她皈依以色列上帝。',
 280),

('life-adam-eve', '亞當和夏娃生平', '亞當夏娃', 'Life of Adam and Eve', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞當夏娃被逐出伊甸後的生平、悔罪與死亡；含撒但墮落敘事。',
 285),

('pseudo-philo', '託斐羅名猶太聖經古史', '託斐羅', 'Pseudo-Philo (Biblical Antiquities)', 'Liber Antiquitatum Biblicarum',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 0, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名斐羅的猶太聖經重述本 (亞當-大衛)；只以拉丁譯本保存。',
 290),

('lives-prophets', '先知生平', '先知生平', 'Lives of the Prophets', 'Βίοι Προφητῶν',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '希伯來大小先知的傳記與死亡敘述；初期猶太-基督徒文獻。',
 295),

('rechab-history', '利甲人歷史', '利甲人', 'History of the Rechabites', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '隱士 Zosimus 尋訪 Rechabites (耶利米 35 章) 於神秘島嶼。',
 300),

('2-baruch', '巴錄二書 (敘利亞語)', '巴錄二', '2 Baruch (Syriac Baruch)', '',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 70, 130,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '聖殿被毀 (70 CE) 後的神義論反思；末世論異象與書信。',
 305),

('3-baruch', '巴錄三書 (希臘語啟示)', '巴錄三', '3 Baruch (Greek Apocalypse)', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '巴錄遊歷五重天的異象。',
 310),

('4-baruch', '巴錄四書 (耶利米補篇)', '巴錄四', '4 Baruch (Paraleipomena Jeremiou)', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '耶利米剩餘事蹟，含基督教徒層的二次重編。',
 315),

('4-ezra', '以斯拉下 (4 Ezra)', '以斯拉下', '4 Ezra (2 Esdras)', '',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 70, 130,
 '{"protestant":false,"catholic":false,"orthodox":true,"ethiopian":true}',
 '以斯拉七場異象 — 聖殿被毀後的神義論反思；東正教典外。',
 320),

('5-6-ezra', '以斯拉五書及以斯拉六書', '以斯拉五六', '5 Ezra and 6 Ezra', '',
 'ot_pseudepigrapha', 'ot', 'latin',
 100, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '4 Ezra 之拉丁版增章 (1-2 + 15-16 章) — 基督徒層的擴寫。',
 325),

('greek-ezra-apoc', '希臘語以斯拉默示錄', '希臘以斯拉', 'Greek Apocalypse of Ezra', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 100, 800,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '以斯拉登天異象的後期希臘文版。',
 330),

('vision-ezra', '以斯拉異象', '以斯拉異象', 'Vision of Ezra', '',
 'ot_pseudepigrapha', 'ot', 'latin',
 100, 800,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '以斯拉登天視審判罪人的拉丁傳統。',
 335),

('questions-ezra', '以斯拉題問', '以斯拉題問', 'Questions of Ezra', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 100, 800,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '以斯拉與天使問答錄 (亞美尼亞傳統)。',
 340),

('sedrach-apoc', '塞德拉克默示錄', '塞德拉克', 'Apocalypse of Sedrach', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 100, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '塞德拉克與上帝對話論罪與恩典；後期希臘啟示文學。',
 345),

('abraham-apoc', '亞伯拉罕默示錄', '亞伯拉罕默', 'Apocalypse of Abraham', '',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 70, 150,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞伯拉罕從偶像家庭出來、登天領受啟示；猶太-基督徒神祕主義早期文獻。',
 350),

('adam-apoc', '亞當默示錄', '亞當默', 'Apocalypse of Adam', '',
 'ot_pseudepigrapha', 'ot', 'coptic',
 0, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞當對其子賽特啟示末世；常見於 Nag Hammadi 諾斯底文獻。',
 355),

('elijah-apoc', '以利亞默示錄', '以利亞默', 'Apocalypse of Elijah', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 100, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '以利亞最後審判與末世異象。',
 360),

('daniel-apoc', '但以理默示錄', '但以理默', 'Apocalypse of Daniel', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 700, 900,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '中世紀但以理風格末世文學，反映拜占庭時代政局。',
 365),

('zephaniah-apoc', '西番雅默示錄', '西番雅默', 'Apocalypse of Zephaniah', '',
 'ot_pseudepigrapha', 'ot', 'coptic',
 -100, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '西番雅遊地獄記；只以科普特文殘片保存。',
 370),

('ezekiel-apoc', '以西結偽經', '以西結偽', 'Apocryphon of Ezekiel', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -100, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '以西結書外傳；含瞎子背瘸子的著名比喻。',
 375),

('shem-treatise', '閃的論說', '閃的論說', 'Treatise of Shem', '',
 'ot_pseudepigrapha', 'ot', 'syriac',
 0, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '閃 (挪亞之子) 對十二宮預兆的論述；占星傳統。',
 380),

('sibylline-oracles', '西卜神諭篇 (西卜神諭篇 / 西卜林神諭篇)', '西卜神諭', 'Sibylline Oracles', 'Σιβυλλιακοὶ Χρησμοί',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, 700,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '14 卷異教外衣的猶太-基督徒末世神諭；歷代擴寫；早期教父頻繁引用。',
 385),

('christian-sibyl', '基督教西卜神諭篇 (第 6-8 卷)', '基督教西卜', 'Christian Sibyllines (Books 6-8)', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 100, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '西卜神諭篇中明顯為基督徒所作的卷次。',
 390),

('ahiqar', '亞希誇', '亞希誇', 'Story of Ahiqar', '',
 'ot_pseudepigrapha', 'ot', 'aramaic',
 -500, -400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞述廷臣亞希誇被陷害復起的智慧文學；伊里芬丁亞蘭文版可至公元前 5 世紀。',
 395),

('aristobulus', '亞理斯多布魯斯書斷片', '亞理斯多布', 'Aristobulus Fragments', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, -150,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞歷山大猶太哲學家對摩西五經的寓意詮釋斷片。',
 400),

('artapanus', '阿塔帕納書斷片', '阿塔帕納', 'Artapanus Fragments', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, -100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '猶太-希臘化作家所作族長傳奇 (摩西=Hermes-Trismegistus)。',
 405),

('demetrius-chron', '年代學家底米丟書', '底米丟', 'Demetrius the Chronographer', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -250, -200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞歷山大猶太作家對族長年代學的斷片。',
 410),

('eupolemus', '尤波利蒙書', '尤波利蒙', 'Eupolemus', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, -150,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '尤波利蒙與託名尤波利蒙的歷史斷片。',
 415),

('orphica', '奧菲卡書', '奧菲卡', 'Orphica (Pseudo-Orpheus)', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, 0,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '猶太化作家以 Orpheus 名義作的一神論詩篇。',
 420),

('philo-poet', '史詩詩人斐羅書', '詩人斐羅', 'Philo the Epic Poet', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, -100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '希臘化猶太詩人以六步格寫族長史詩斷片。',
 425),

('theodotus', '塞奧多圖書', '塞奧多圖', 'Theodotus', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, -100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '希臘化猶太詩人對示劍歷史的史詩斷片。',
 430),

('phocylides', '託福西萊德名書', '託福西萊德', 'Pseudo-Phocylides', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -100, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名公元前 6 世紀希臘詩人 Phocylides 的猶太道德教訓詩。',
 435),

('menander-syr', '敘利亞語門安德寓言', '門安德', 'Syriac Menander', '',
 'ot_pseudepigrapha', 'ot', 'syriac',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名希臘喜劇家 Menander 的敘利亞語格言文學。',
 440),

('hecataeus', '託赫卡泰烏名書', '託赫卡泰烏', 'Pseudo-Hecataeus', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 -200, -100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名 Hecataeus of Abdera 的猶太化希臘斷片。',
 445),

('psalms-solomon', '所羅門詩篇', '所羅門詩', 'Psalms of Solomon', 'Ψαλμοὶ Σαλωμῶντος',
 'ot_pseudepigrapha', 'ot', 'hebrew',
 -100, -50,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '18 首託名所羅門的彌賽亞詩篇；對龐培入耶路撒冷的反思。',
 450),

('odes-solomon', '所羅門頌詩', '所羅門頌', 'Odes of Solomon', '',
 'ot_pseudepigrapha', 'ot', 'syriac',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '42 首基督徒頌詩；早期敘利亞詩歌文學。',
 455),

('joseph-prayer', '約瑟禱文', '約瑟禱文', 'Prayer of Joseph', '',
 'ot_pseudepigrapha', 'ot', 'greek',
 0, 100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '猶太天使學斷片；以色列 = 雅各 = 天使 Israel 的天上身份。',
 460),

-- ============================================================================
-- QUMRAN 昆蘭 (display 500-549)
-- ============================================================================
('1qs', '崑蘭社群規章 (1QS)', '社群規章', 'Community Rule (1QS)', '',
 'qumran', 'ot', 'hebrew',
 -200, -50,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '昆蘭社群的入會、儀式、紀律與兩靈論文獻。死海古卷核心文獻之一。',
 510),

-- ============================================================================
-- NT APOCRYPHA — Gospels 福音書類 (display 600-699)
-- ============================================================================
('gthom', '多馬福音', '多馬福', 'Gospel of Thomas', '',
 'nag_hammadi', 'nt', 'coptic',
 50, 150,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '114 句耶穌語錄；Nag Hammadi II,2；學界爭論：早期 Q-tradition vs 二世紀諾斯底重編。',
 610),

('infancy-thomas', '多馬的耶穌嬰孩時期福音', '多馬嬰孩', 'Infancy Gospel of Thomas', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '幼年耶穌 (5-12 歲) 行神跡奇事的傳奇故事。',
 615),

('protoevangelium-james', '雅各原始福音', '雅各原始', 'Protoevangelium of James', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '馬利亞家世、童女生子、耶穌降生敘事擴寫；後世聖母敬禮神學重要來源。',
 620),

('infancy-arabic', '阿拉伯語耶穌嬰孩時期福音', '阿拉伯嬰孩', 'Arabic Infancy Gospel', '',
 'nt_apocrypha', 'nt', 'syriac',
 500, 700,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '基督教中東傳統對幼年耶穌與在埃及神蹟的彙整。',
 625),

('infancy-latin', '拉丁語耶穌嬰孩時期福音 (阿倫德爾抄本404)', '拉丁嬰孩', 'Latin Infancy Gospel (Arundel 404)', '',
 'nt_apocrypha', 'nt', 'latin',
 800, 1100,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '中世紀拉丁語幼年耶穌敘事傳統。',
 630),

('joseph-carpenter', '木匠約瑟的歷史', '木匠約瑟', 'History of Joseph the Carpenter', '',
 'nt_apocrypha', 'nt', 'coptic',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '約瑟臨終、死亡與天上待遇的敘事；科普特禮儀傳統重要。',
 635),

('birth-mary', '馬利亞的出生', '馬利亞出生', 'Birth of Mary (Liber de Nativitate Mariae)', '',
 'nt_apocrypha', 'nt', 'latin',
 600, 900,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '馬利亞家世與童年敘事的後期拉丁傳統。',
 640),

('gpet', '彼得福音', '彼得福', 'Gospel of Peter', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '受難與復活敘事的擴寫；含十字架對話的擬人化異象。',
 645),

('gmary', '馬利亞 (抹大拉) 福音', '馬利亞福', 'Gospel of Mary (Magdalene)', '',
 'nt_apocrypha', 'nt', 'coptic',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '抹大拉馬利亞對使徒分享復活主之教導；柏林抄本 BG 8502。',
 650),

('ghebrews', '希伯來人福音', '希伯來福', 'Gospel of the Hebrews', '',
 'nt_apocrypha', 'nt', 'aramaic',
 50, 150,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '早期猶太-基督徒社群所用之福音書；只以教父引用保存斷片。',
 655),

('gnazarenes', '拿撒勒派人福音', '拿撒勒福', 'Gospel of the Nazarenes', '',
 'nt_apocrypha', 'nt', 'aramaic',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞蘭文版本的馬太福音改編；只存教父斷片。',
 660),

('gebionites', '伊便尼派人福音', '伊便尼福', 'Gospel of the Ebionites', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '低基督論猶太-基督徒社群所用；只存 Epiphanius 引用斷片。',
 665),

('gegyptians', '埃及人福音', '埃及福', 'Gospel of the Egyptians', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞歷山大基督徒社群所用；含關於性別與救恩的禁欲主義對話。',
 670),

('gphilip', '腓力福音', '腓力福', 'Gospel of Philip', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi II,3；華倫天奴派 (Valentinian) 神祕主義文獻；含聖事神學早期反思。',
 675),

('gtruth', '真理福音', '真理福', 'Gospel of Truth', '',
 'nag_hammadi', 'nt', 'coptic',
 150, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi I,3 + XII,2；可能 Valentinus 親作；華倫天奴派神祕詩學作品。',
 680),

('gjudas', '猶大福音', '猶大福', 'Gospel of Judas', '',
 'nt_apocrypha', 'nt', 'coptic',
 130, 170,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Codex Tchacos；該隱派 (Cainite) 觀點下的猶大為「正確使徒」。',
 685),

('gbart', '巴多羅買福音', '巴多羅買', 'Gospel of Bartholomew', '',
 'nt_apocrypha', 'nt', 'greek',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '巴多羅買向復活主問答下地獄之奧秘。',
 690),

('gnicodemus', '尼哥德慕福音 (彼拉多行傳)', '尼哥德慕', 'Gospel of Nicodemus (Acts of Pilate)', '',
 'nt_apocrypha', 'nt', 'greek',
 300, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '受審/受難/復活敘事 + 基督下地獄 (Harrowing of Hell)；中世紀流傳極廣。',
 695),

('q-secret-mark', '馬可的神秘福音', '馬可秘', 'Secret Gospel of Mark', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Morton Smith 1958 發現之 Clement 信件斷片；學界對真偽爭論未定。',
 700),

('p-oxy-840', '俄西林古蒲草紙 840', 'P.Oxy. 840', 'P.Oxy. 840', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '埃及俄西林古發現的耶穌與法利賽人禮儀爭論斷片。',
 705),

('p-egerton-2', '伊吉頓蒲草紙 2', 'P.Egerton 2', 'Egerton Papyrus 2', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '不知名福音書殘片；含類似約翰福音的對話片段。',
 710),

('p-merton-51', '默頓蒲草紙 51', 'P.Merton 51', 'P.Merton 51', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Merton 收藏中無名福音書殘片。',
 715),

('p-berlin-11710', '柏林蒲草紙 11710', 'P.Berl. 11710', 'P.Berlin 11710', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '柏林收藏無名福音書殘片。',
 720),

('p-berlin-16388', '柏林蒲草紙 16388', 'P.Berl. 16388', 'P.Berlin 16388', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '柏林收藏無名福音書殘片。',
 725),

('p-strasbourg', '斯特拉斯堡蒲草紙', 'P.Strasb', 'Strasbourg Papyrus', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '科普特語不知名福音書殘片。',
 730),

('gmatthias', '馬提亞福音 / 託馬太名福音', '馬提亞', 'Gospel of Matthias', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名替補使徒馬提亞的福音書斷片。',
 735),

('logia-unknown', '獨立存留的耶穌語錄', '獨立耶穌語', 'Independent Sayings of Jesus (Agrapha)', '',
 'nt_apocrypha', 'nt', 'greek',
 50, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '教父引用、抄本邊注等保存的零散耶穌語錄。',
 740),

('soph-jesus', '耶穌基督智慧書', '耶穌智慧', 'Sophia of Jesus Christ', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi III,4 + BG 8502,3；諾斯底版本之復活對話。',
 745),

('faiyum', '費爾語錄 (Faiyum 殘片)', '費爾語錄', 'Fayyum Fragment', '',
 'nt_apocrypha', 'nt', 'greek',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '埃及 Faiyum 出土福音書殘片。',
 750),

('q-mani', '摩尼福音', '摩尼福', 'Gospel of Mani', '',
 'nt_apocrypha', 'nt', 'syriac',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '摩尼教創立者所作福音斷片；多為論戰文獻引述。',
 755),

-- NT APOCRYPHA — Acts 使徒行傳類 (display 800-849)
('acts-paul', '保羅行傳', '保羅行', 'Acts of Paul', '',
 'nt_apocrypha', 'nt', 'greek',
 150, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '保羅在小亞、馬其頓、希臘的傳奇故事；含 Thecla 段、與羅馬殉道。',
 810),

('acts-peter', '彼得行傳', '彼得行', 'Acts of Peter', '',
 'nt_apocrypha', 'nt', 'greek',
 150, 250,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '彼得在羅馬、與術士西門對抗、倒釘十字架的傳奇敘事。',
 815),

('acts-andrew', '安得烈行傳', '安得烈行', 'Acts of Andrew', '',
 'nt_apocrypha', 'nt', 'greek',
 150, 250,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '安得烈在亞該亞傳道與殉道；只存教父引用斷片。',
 820),

('acts-john', '約翰行傳', '約翰行', 'Acts of John', '',
 'nt_apocrypha', 'nt', 'greek',
 150, 250,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '約翰在以弗所事工與神秘十字架詩篇 (Hymn of the Cross)。',
 825),

('acts-thomas', '多馬行傳', '多馬行', 'Acts of Thomas', '',
 'nt_apocrypha', 'nt', 'syriac',
 200, 250,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '多馬到印度傳道之傳奇；含著名「珍珠詩」(Hymn of the Pearl)。',
 830),

('acts-philip', '腓力行傳', '腓力行', 'Acts of Philip', '',
 'nt_apocrypha', 'nt', 'greek',
 300, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '腓力在希臘、巴提亞傳道與殉道。',
 835),

-- NT APOCRYPHA — Epistles 書信類 (display 850-899)
('3-cor', '哥林多三書 / 保羅與哥林多人書信', '哥三', '3 Corinthians', '',
 'nt_apocrypha', 'nt', 'greek',
 150, 250,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞美尼亞使徒教會曾接受的保羅偽信件；反諾斯底論戰背景。',
 855),

('q-laodicea', '老底嘉書', '老底嘉', 'Epistle to the Laodiceans', '',
 'nt_apocrypha', 'nt', 'latin',
 200, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名保羅致老底嘉之信 (歌羅西 4:16 提及之失傳信件)；只存拉丁文版。',
 860),

('seneca-paul', '辛尼加與保羅的信', '辛尼加保羅', 'Letters of Seneca and Paul', '',
 'nt_apocrypha', 'nt', 'latin',
 300, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '哲學家辛尼加 (尼祿之師) 與使徒保羅虛構通信 14 封；中世紀流傳廣。',
 865),

('pseudo-titus', '託提多名書', '託提多', 'Pseudo-Titus', '',
 'nt_apocrypha', 'nt', 'latin',
 300, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '託名提多書之禁欲主義講道。',
 870),

('pilate-claudius', '彼拉多給革老丟的信', '彼拉多給革老丟', 'Letter of Pilate to Claudius', '',
 'nt_apocrypha', 'nt', 'latin',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '彼拉多致皇帝書信文學系列之一。',
 875),

('pilate-tiberius', '彼拉多給提庇留的信', '彼拉多給提庇留', 'Letter of Pilate to Tiberius', '',
 'nt_apocrypha', 'nt', 'greek',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '彼拉多向羅馬皇帝報告耶穌受難之偽書信。',
 880),

('pilate-herod', '彼拉多與希律的信函', '彼拉多希律', 'Letters of Pilate and Herod', '',
 'nt_apocrypha', 'nt', 'greek',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '彼拉多與分封王希律之間虛構通信。',
 885),

('peter-philip', '彼得給腓力的信', '彼得給腓力', 'Letter of Peter to Philip', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi VIII,2；諾斯底版本之復活對話。',
 890),

('abgar', '亞伯加傳記', '亞伯加', 'Abgar Legend', '',
 'nt_apocrypha', 'nt', 'syriac',
 200, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Edessa 國王亞伯加與耶穌通信、收聖容布 (Mandylion) 的敘利亞傳統。',
 895),

('clement-romance', '革利免的傳奇故事 (Pseudo-Clementines)', '革利免傳奇', 'Pseudo-Clementines (Romance)', '',
 'nt_apocrypha', 'nt', 'greek',
 300, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Recognitions + Homilies；羅馬革利免的家庭離散與復合敘事；含彼得與西門術士辯論。',
 900),

('q-peter-preaching', '彼得的宣講 (Kerygma Petri)', '彼得宣講', 'Kerygma Petrou (Preaching of Peter)', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '早期教會宣教神學斷片；只存 Clement of Alexandria 引用。',
 905),

-- NT APOCRYPHA — Apocalypses 默示錄類 (display 950-999)
('apoc-peter', '彼得默示錄 (希臘)', '彼得默', 'Apocalypse of Peter', '',
 'nt_apocrypha', 'nt', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '最早的基督徒地獄遊歷文學；對中世紀但丁等影響深遠。',
 955),

('apoc-peter-cop', '科普替語諾斯底的彼得默示錄', '諾斯底彼得默', 'Coptic Apocalypse of Peter', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi VII,3；諾斯底版本之彼得異象。',
 960),

('apoc-paul', '保羅默示錄 (Visio Pauli)', '保羅默', 'Apocalypse of Paul (Visio Pauli)', '',
 'nt_apocrypha', 'nt', 'greek',
 300, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '保羅遊歷天堂與地獄的中世紀流傳本。',
 965),

('apoc-paul-cop', '科普替語諾斯底的保羅默示錄', '諾斯底保羅默', 'Coptic Apocalypse of Paul', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi V,2；諾斯底版本之保羅登天。',
 970),

('apoc-thomas', '多馬默示錄', '多馬默', 'Apocalypse of Thomas', '',
 'nt_apocrypha', 'nt', 'latin',
 400, 600,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '中世紀拉丁傳統之七日末世大災難敘事。',
 975),

('apoc-james-1', '雅各默示錄壹書', '雅各默壹', '1 Apocalypse of James', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi V,3；耶穌與雅各 (主之兄弟) 的復活對話。',
 980),

('apoc-james-2', '雅各默示錄貳書', '雅各默貳', '2 Apocalypse of James', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi V,4；含雅各殉道敘事的諾斯底文本。',
 985),

('isaiah-ascension', '以賽亞昇天記', '以賽亞昇天', 'Ascension of Isaiah', '',
 'nt_apocrypha', 'mixed', 'greek',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '以賽亞遊歷七重天的異象；融合猶太殉道與基督徒擴寫。',
 990),

-- NT APOCRYPHA — Misc 其他 (display 1000-1099)
('didache', '十二使徒遺訓 (Didache)', '十二使徒', 'Didache (Teaching of the Twelve Apostles)', '',
 'nt_apocrypha', 'nt', 'greek',
 50, 120,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '兩道倫理 + 教會儀禮綱要；最早禮儀文獻之一；學界視為使徒教父或 NT 邊界文獻。',
 1010),

('john-apocryphon', '約翰藏經 (Apocryphon of John)', '約翰藏', 'Apocryphon of John', '',
 'nag_hammadi', 'nt', 'coptic',
 100, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi II,1 / III,1 / IV,1 + BG 8502,2；諾斯底神學經典文本。',
 1015),

('pistis-sophia', '皮斯特斯·索菲亞 (Pistis Sophia)', '皮斯特斯索菲', 'Pistis Sophia', '',
 'nt_apocrypha', 'nt', 'coptic',
 200, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Askew Codex；復活後耶穌教導之長篇諾斯底對話。',
 1020),

('dialogue-savior', '與救主的對話', '救主對話', 'Dialogue of the Savior', '',
 'nag_hammadi', 'nt', 'coptic',
 200, 300,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Nag Hammadi III,5；耶穌與門徒 (含馬利亞) 之復活對話。',
 1025),

('epistula-apostolorum', '使徒書信 (Epistula Apostolorum)', '使徒書信', 'Epistula Apostolorum', '',
 'nt_apocrypha', 'nt', 'greek',
 150, 200,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '11 位使徒與復活主之對話 + 以信件形式寫成的反諾斯底文本。',
 1030),

('memoria-apostolorum', '使徒回憶錄', '使徒回憶', 'Memoria Apostolorum', '',
 'nt_apocrypha', 'nt', 'latin',
 200, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '使徒口述回憶的後期彙編傳統。',
 1035),

('joseph-arimathea', '亞利馬太約瑟的記述', '亞利馬太', 'Narrative of Joseph of Arimathea', '',
 'nt_apocrypha', 'nt', 'greek',
 200, 500,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '亞利馬太約瑟敘述受難週後之事。',
 1040),

('seventy-elders', '七十長老福音', '七十長老', 'Gospel of the Seventy', '',
 'nt_apocrypha', 'nt', 'greek',
 200, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '路加 10 章七十門徒傳統之擴寫敘事。',
 1045),

('john-baptist-life', '施洗者約翰生平', '施洗約翰生', 'Life of John the Baptist', '',
 'nt_apocrypha', 'nt', 'syriac',
 400, 700,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '東方教會傳統對施洗者約翰的擴寫傳記。',
 1050),

('vengeance-savior', '救主的伸冤 (Vindicta Salvatoris)', '救主伸冤', 'Vindicta Salvatoris', '',
 'nt_apocrypha', 'nt', 'latin',
 700, 900,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 '對耶路撒冷被毀作為對基督受難之神聖報復的中世紀敘事。',
 1055),

('two-books-jeu', '論約翰的兩本書 (Jeu)', '約翰兩本', 'Two Books of Jeu', '',
 'nt_apocrypha', 'nt', 'coptic',
 200, 400,
 '{"protestant":false,"catholic":false,"orthodox":false,"ethiopian":false}',
 'Bruce Codex；諾斯底升天神秘主義文本 — 與 Pistis Sophia 相關。',
 1060)

ON CONFLICT (slug) DO UPDATE
SET title_zh = EXCLUDED.title_zh,
    title_zh_short = EXCLUDED.title_zh_short,
    title_en = EXCLUDED.title_en,
    title_orig = EXCLUDED.title_orig,
    category = EXCLUDED.category,
    testament = EXCLUDED.testament,
    language_orig = EXCLUDED.language_orig,
    composition_low = EXCLUDED.composition_low,
    composition_high = EXCLUDED.composition_high,
    canon_status_jsonb = EXCLUDED.canon_status_jsonb,
    summary_zh = EXCLUDED.summary_zh,
    display_order = EXCLUDED.display_order;

-- ── Versions ────────────────────────────────────────────────────────────────
INSERT INTO apocrypha_versions
  (code, name_zh, name_en, language, language_zh, category,
   public_domain, is_redistributable, copyright_notice, source_url,
   display_order, is_default_zh, is_default_en, is_default_orig)
VALUES
-- 中文
('cct_zh', '基督教典外文獻 (王曉朝主編)', 'Christian Extra-Canonical Literature (ed. Wang Xiaochao)',
 'zh-Hant', '繁體中文', 'chinese',
 false, false,
 '© 基督教文藝出版社 (Chinese Christian Literature Council, Ltd) 2008-2013；個人研究用',
 NULL,
 10, true, false, false),
-- 英文 (待補)
('charles_apot', 'Charles 1913 APOT — 偽典英譯', 'R.H. Charles, Apocrypha and Pseudepigrapha of the OT (Oxford 1913)',
 'en', '英文', 'english',
 true, true,
 'Public domain (1913)',
 'https://archive.org/details/apocryphapseudep01char',
 20, false, true, false),
('charlesworth_otp', 'Charlesworth OTP 1983-85', 'J.H. Charlesworth, The Old Testament Pseudepigrapha (Doubleday 1983-85)',
 'en', '英文', 'english',
 false, false,
 '© Doubleday / Yale 1983-85；個人研究用 (待補)',
 NULL,
 25, false, false, false),
('mrjames_ntapoc', 'M.R. James 1924 — NT 偽典英譯', 'M.R. James, The Apocryphal New Testament (Oxford 1924)',
 'en', '英文', 'english',
 true, true,
 'Public domain (1924)',
 'https://www.earlychristianwritings.com/mrjames/',
 30, false, false, false),
('robinson_nh', 'Robinson NHL 1977/1996 — Nag Hammadi 英譯', 'J.M. Robinson, The Nag Hammadi Library in English (HarperOne 1977/1996)',
 'en', '英文', 'english',
 false, false,
 '© HarperOne 1977/1996；部分線上 PD',
 'http://gnosis.org/naghamm/nhl.html',
 35, false, false, false),
-- 原文 (待補)
('greek_orig', '希臘文原文', 'Greek original',
 'grc', '希臘文', 'source',
 true, true,
 '依各文本之 critical edition',
 NULL,
 50, false, false, true),
('coptic_orig', '科普特文原文 (Nag Hammadi Codices)', 'Coptic (Nag Hammadi Codices)',
 'cop', '科普特文', 'source',
 true, true,
 'Coptic Gnostic Library / Brill',
 NULL,
 55, false, false, false),
('syriac_orig', '敘利亞文原文', 'Syriac original',
 'syr', '敘利亞文', 'source',
 true, true,
 NULL, NULL,
 60, false, false, false),
('hebrew_orig', '希伯來文原文', 'Hebrew original',
 'hbo', '希伯來文', 'source',
 true, true,
 NULL, NULL,
 65, false, false, false),
('aramaic_orig', '亞蘭文原文', 'Aramaic original',
 'arc', '亞蘭文', 'source',
 true, true,
 NULL, NULL,
 70, false, false, false),
('ethiopic_orig', 'Ge''ez 衣索匹亞文原文', 'Ge''ez (Ethiopic) original',
 'gez', 'Ge''ez 文', 'source',
 true, true,
 NULL, NULL,
 75, false, false, false),
('latin_orig', '拉丁文原文', 'Latin original',
 'lat', '拉丁文', 'source',
 true, true,
 NULL, NULL,
 80, false, false, false)

ON CONFLICT (code) DO UPDATE
SET name_zh = EXCLUDED.name_zh,
    name_en = EXCLUDED.name_en,
    language = EXCLUDED.language,
    language_zh = EXCLUDED.language_zh,
    category = EXCLUDED.category,
    public_domain = EXCLUDED.public_domain,
    is_redistributable = EXCLUDED.is_redistributable,
    copyright_notice = EXCLUDED.copyright_notice,
    source_url = EXCLUDED.source_url,
    display_order = EXCLUDED.display_order,
    is_default_zh = EXCLUDED.is_default_zh,
    is_default_en = EXCLUDED.is_default_en,
    is_default_orig = EXCLUDED.is_default_orig;
