-- ============================================================
-- 天主教大主教座補充——美洲、亞洲、非洲、大洋洲
-- ============================================================

INSERT INTO episcopal_sees (name_zh, name_en, see_zh, church, tradition, rite, founded_year, abolished_year, status,
  current_patriarch_zh, current_patriarch_en, incumbent_since, location, notes, sources) VALUES

-- 美洲——拉丁美洲
('聖多明哥大主教座',
 'Archdiocese of Santo Domingo',
 '聖多明哥', '天主教', '天主教', '羅馬禮', 1511, NULL, '現存',
 '大主教弗朗西斯科·奧佐裡亞', 'Archbishop Francisco Ozoria', 2016, '多明尼加共和國聖多明哥',
 '1511年美洲最早設立的大主教座（新大陸），主教亞歷山大·赫罯特（Alexo de Merienda）繼1504年小主教座之後升任。',
 'Catholic Church records; Santo Domingo archdiocese'),

('墨西哥城大主教座',
 'Archdiocese of Mexico City (Primacy of Mexico)',
 '墨西哥城', '天主教', '天主教', '羅馬禮', 1530, NULL, '現存',
 '大主教卡洛斯·阿吉亞爾-雷特斯', 'Archbishop Carlos Aguiar Retes', 2017, '墨西哥墨西哥城',
 '1530年設主教座（卡洛斯一世授權）；1546年升為大主教座，胡安·德蘇馬拉加出任首任大主教；墨西哥天主教首席大主教座（Primatial See of Mexico）。墨西哥2025年仍為全球第二大天主教人口國。',
 'Catholic Church records; Mexico City archdiocese'),

('利馬大主教座',
 'Archdiocese of Lima',
 '利馬', '天主教', '天主教', '羅馬禮', 1541, NULL, '現存',
 '大主教卡洛斯·卡斯蒂略', 'Archbishop Carlos Castillo', 2019, '秘魯利馬',
 '1541年設主教座；1546年升為大主教座，南美洲最早的大主教座；聖玫瑰（Rose of Lima, 1586–1617）在此服事，為美洲第一位正式封聖的聖徒。',
 'Catholic Church records; Lima archdiocese'),

('波哥大大主教座',
 'Archdiocese of Bogotá',
 '波哥大', '天主教', '天主教', '羅馬禮', 1564, NULL, '現存',
 '大主教路易斯·何塞·魯埃達·阿帕里西奧', 'Archbishop Luis José Rueda Aparicio', 2020, '哥倫比亞波哥大',
 '1564年設主教座；1902年升為大主教座；哥倫比亞天主教首席大主教座。',
 'Catholic Church records; Bogotá archdiocese'),

('布宜諾斯艾利斯大主教座',
 'Archdiocese of Buenos Aires',
 '布宜諾斯艾利斯', '天主教', '天主教', '羅馬禮', 1730, NULL, '現存',
 '大主教豪爾赫·賈西亞·庫爾巴', 'Archbishop Jorge García Cuerva', 2023, '阿根廷布宜諾斯艾利斯',
 '1730年設主教座；1865年升為大主教座；教宗方濟各（豪爾赫·馬里奧·貝爾戈利奥）2001–2013年任此職，為阿根廷天主教首席大主教座。',
 'Catholic Church records; Buenos Aires archdiocese'),

('里約熱內盧大主教座',
 'Archdiocese of Rio de Janeiro',
 '里約熱內盧', '天主教', '天主教', '羅馬禮', 1676, NULL, '現存',
 '大主教奧拉尼·坦佩斯塔', 'Archbishop Orani Tempesta', 2009, '巴西里約熱內盧',
 '1676年設主教座；1892年升為大主教座；科科瓦多山基督像（1931）所在地。',
 'Catholic Church records; Rio de Janeiro archdiocese'),

('聖保羅大主教座',
 'Archdiocese of São Paulo',
 '聖保羅', '天主教', '天主教', '羅馬禮', 1745, NULL, '現存',
 '大主教奧迪洛·謝雷爾', 'Archbishop Odilo Scherer', 2007, '巴西聖保羅',
 '1745年設主教座；1908年升為大主教座；巴西最大城市，信徒超1500萬。',
 'Catholic Church records; São Paulo archdiocese'),

('聖地亞哥大主教座',
 'Archdiocese of Santiago de Chile',
 '聖地亞哥', '天主教', '天主教', '羅馬禮', 1561, NULL, '現存',
 '大主教塞萊斯蒂諾·奧斯·布拉科', 'Archbishop Celestino Aós Braco', 2020, '智利聖地亞哥',
 '1561年設主教座；1840年升為大主教座；智利天主教首席大主教座。',
 'Catholic Church records; Santiago archdiocese'),

('加拉加斯大主教座',
 'Archdiocese of Caracas',
 '加拉加斯', '天主教', '天主教', '羅馬禮', 1637, NULL, '現存',
 '大主教沙維爾·奧維多', 'Archbishop Aldo Del Monte', 2024, '委內瑞拉加拉加斯',
 '1637年設主教座；1804年升為大主教座；委內瑞拉天主教首席大主教座。',
 'Catholic Church records; Caracas archdiocese'),

('蒙特維的亞大主教座',
 'Archdiocese of Montevideo',
 '蒙特維的亞', '天主教', '天主教', '羅馬禮', 1859, NULL, '現存',
 '大主教丹尼爾·斯圖爾拉', 'Archbishop Daniel Sturla', 2014, '烏拉圭蒙特維的亞',
 '1859年設主教座；1897年升為大主教座；烏拉圭首席大主教座。',
 'Catholic Church records; Montevideo archdiocese'),

('聖多明各-德瓜亞斯大主教座',
 'Archdiocese of Guayaquil',
 '瓜亞基爾', '天主教', '天主教', '羅馬禮', 1838, NULL, '現存',
 '大主教路易斯·格拉', 'Archbishop Luis Gerardo Cabrera Herrera', 2015, '厄瓜多瓜亞基爾',
 '1838年設主教座；1956年升為大主教座。', 'Catholic Church records; Guayaquil archdiocese'),

('基多大主教座',
 'Archdiocese of Quito',
 '基多', '天主教', '天主教', '羅馬禮', 1545, NULL, '現存',
 '大主教阿方索·埃斯帕裡薩', 'Archbishop Alfonso Espíndola', 2021, '厄瓜多基多',
 '1545年設主教座；1848年升為大主教座。', 'Catholic Church records; Quito archdiocese'),

('哈瓦那大主教座',
 'Archdiocese of Havana',
 '哈瓦那', '天主教', '天主教', '羅馬禮', 1787, NULL, '現存',
 '大主教胡安·加西亞·羅德里格斯', 'Archbishop Juan de la Caridad García Rodríguez', 2016, '古巴哈瓦那',
 '1787年設主教座；1925年升為大主教座；古巴天主教首席大主教座。',
 'Catholic Church records; Havana archdiocese'),

-- 美洲——北美
('魁北克大主教座',
 'Archdiocese of Quebec',
 '魁北克', '天主教', '天主教', '羅馬禮', 1674, NULL, '現存',
 '大主教傑拉爾德·拉克羅瓦', 'Archbishop Gérald Lacroix', 2011, '加拿大魁北克市',
 '1674年設主教座（法蘭索瓦·德拉瓦爾出任首任主教）；1819年升為大主教座；加拿大最古老主教座，法語加拿大天主教首席大主教座。',
 'Catholic Church records; Quebec archdiocese'),

('蒙特利爾大主教座',
 'Archdiocese of Montreal',
 '蒙特利爾', '天主教', '天主教', '羅馬禮', 1821, NULL, '現存',
 '大主教克里斯蒂安·勒皮讷', 'Archbishop Christian Lépine', 2012, '加拿大蒙特利爾',
 '1821年設主教座；1886年升為大主教座；加拿大最大法語城市。',
 'Catholic Church records; Montreal archdiocese'),

('多倫多大主教座',
 'Archdiocese of Toronto',
 '多倫多', '天主教', '天主教', '羅馬禮', 1841, NULL, '現存',
 '大主教弗朗西斯·里奧', 'Archbishop Francis Leo', 2023, '加拿大多倫多',
 '1841年設主教座；1870年升為大主教座；加拿大英語天主教最大教區。',
 'Catholic Church records; Toronto archdiocese'),

('巴爾的摩大主教座',
 'Archdiocese of Baltimore',
 '巴爾的摩', '天主教', '天主教', '羅馬禮', 1789, NULL, '現存',
 '大主教威廉·洛里', 'Archbishop William Lori', 2012, '美國馬里蘭州巴爾的摩',
 '1789年美國第一個天主教主教座（約翰·卡羅爾出任首任主教）；1808年升為大主教座；美國天主教歷史上的首席大主教座（Mother Church of American Catholicism）。',
 'Catholic Church records; Baltimore archdiocese'),

('紐約大主教座',
 'Archdiocese of New York',
 '紐約', '天主教', '天主教', '羅馬禮', 1808, NULL, '現存',
 '大主教提摩太·多蘭', 'Archbishop Timothy Dolan', 2009, '美國紐約',
 '1808年設主教座；1850年升為大主教座；美國影響力最大的大主教座之一；教宗方濟各2015年在此主持聖彼得和保羅遊行。',
 'Catholic Church records; New York archdiocese'),

('波士頓大主教座',
 'Archdiocese of Boston',
 '波士頓', '天主教', '天主教', '羅馬禮', 1808, NULL, '現存',
 '大主教肖恩·奧馬利', 'Archbishop Seán O''Malley', 2003, '美國麻薩諸塞州波士頓',
 '1808年設主教座；1875年升為大主教座；愛爾蘭裔天主教徒傳統重鎮；神父性侵醜聞2002年震驚全球。',
 'Catholic Church records; Boston archdiocese'),

('芝加哥大主教座',
 'Archdiocese of Chicago',
 '芝加哥', '天主教', '天主教', '羅馬禮', 1843, NULL, '現存',
 '大主教布雷斯·庫皮奇', 'Archbishop Blase Cupich', 2014, '美國伊利諾州芝加哥',
 '1843年設主教座；1880年升為大主教座；美國信徒人數最多的天主教大主教座（約230萬）。',
 'Catholic Church records; Chicago archdiocese'),

('洛杉磯大主教座',
 'Archdiocese of Los Angeles',
 '洛杉磯', '天主教', '天主教', '羅馬禮', 1859, NULL, '現存',
 '大主教岡薩洛·卡斯蒂略', 'Archbishop Gonzalo Castillo', 2023, '美國加利福尼亞州洛杉磯',
 '1859年設主教座；1936年升為大主教座；美國最大天主教大主教座（約400萬信徒）。',
 'Catholic Church records; Los Angeles archdiocese'),

('費城大主教座',
 'Archdiocese of Philadelphia',
 '費城', '天主教', '天主教', '羅馬禮', 1808, NULL, '現存',
 '大主教尼爾森·佩雷斯', 'Archbishop Nelson Perez', 2020, '美國賓夕法尼亞州費城',
 '1808年設主教座；1875年升為大主教座；2015年世界家庭大會在此舉行。',
 'Catholic Church records; Philadelphia archdiocese'),

('聖安東尼奧大主教座',
 'Archdiocese of San Antonio',
 '聖安東尼奧', '天主教', '天主教', '羅馬禮', 1874, NULL, '現存',
 '大主教古斯塔沃·加西亞-塞勒', 'Archbishop Gustavo García-Siller', 2010, '美國德克薩斯州聖安東尼奧',
 '1874年設主教座；1926年升為大主教座；西班牙裔天主教傳統重鎮。',
 'Catholic Church records; San Antonio archdiocese'),

('邁阿密大主教座',
 'Archdiocese of Miami',
 '邁阿密', '天主教', '天主教', '羅馬禮', 1958, NULL, '現存',
 '大主教托馬斯·溫斯基', 'Archbishop Thomas Wenski', 2010, '美國佛羅里達州邁阿密',
 '1958年設主教座；1968年升為大主教座；古巴流亡天主教徒集中地。',
 'Catholic Church records; Miami archdiocese'),

-- 亞洲
('果阿大主教座',
 'Archdiocese of Goa and Daman',
 '果阿', '天主教', '天主教', '羅馬禮', 1533, NULL, '現存',
 '大主教菲利普·内裡·費雷奧', 'Archbishop Filipe Neri Ferrão', 2004, '印度果阿',
 '1533年設主教座；1557年升為大主教座，為亞洲第一個大主教座；葡萄牙殖民地傳教基地；聖方濟各·沙勿略遺體保存於此。',
 'Catholic Church records; Goa archdiocese'),

('馬尼拉大主教座',
 'Archdiocese of Manila',
 '馬尼拉', '天主教', '天主教', '羅馬禮', 1579, NULL, '現存',
 '大主教何塞·阿德維庫拉', 'Archbishop Jose Advincula', 2021, '菲律賓馬尼拉',
 '1579年設主教座；1595年升為大主教座；菲律賓首席大主教座；菲律賓為亞洲最大天主教國家（約85%）。',
 'Catholic Church records; Manila archdiocese'),

('河內大主教座',
 'Archdiocese of Hanoi',
 '河內', '天主教', '天主教', '羅馬禮', 1679, NULL, '現存',
 '大主教彼得·阮文長', 'Archbishop Peter Nguyen Van Nhon', 2010, '越南河內',
 '1679年設宗座代牧區；1960年升為大主教座；越南北部天主教首席大主教座。',
 'Catholic Church records; Hanoi archdiocese'),

('胡志明市大主教座',
 'Archdiocese of Ho Chi Minh City',
 '胡志明市', '天主教', '天主教', '羅馬禮', 1955, NULL, '現存',
 '大主教阮年', 'Archbishop Nguyen Nang', 2023, '越南胡志明市',
 '1955年設主教座（原西貢）；1960年升為大主教座；越南南部天主教最大城市。',
 'Catholic Church records; Ho Chi Minh City archdiocese'),

('首爾大主教座',
 'Archdiocese of Seoul',
 '首爾', '天主教', '天主教', '羅馬禮', 1831, NULL, '現存',
 '大主教柳洪烈', 'Archbishop Peter Chung Soon-택', 2021, '韓國首爾',
 '1831年設朝鮮宗座代牧區；1962年升為大主教座；韓國天主教首席大主教座。朝鮮時代遭大規模迫害（1839、1866年）；多位殉道聖徒封聖。',
 'Catholic Church records; Seoul archdiocese'),

('東京大主教座',
 'Archdiocese of Tokyo',
 '東京', '天主教', '天主教', '羅馬禮', 1891, NULL, '現存',
 '大主教達爾修斯·菊池', 'Archbishop Tarcisius Isao Kikuchi', 2017, '日本東京',
 '1891年設主教座（更早由橫濱管轄）；1953年升為大主教座；日本首席大主教座。',
 'Catholic Church records; Tokyo archdiocese'),

('北京大主教座',
 'Archdiocese of Beijing (Peking)',
 '北京', '天主教', '天主教', '羅馬禮', 1690, NULL, '現存',
 '大主教李山', 'Archbishop Li Shan', 2007, '中國北京',
 '1690年設主教座（利瑪竇傳教後續）；1946年升為大主教座；現為中國天主教愛國會與梵蒂岡雙方認可的「合法」大主教座（2018年協議後）。',
 'Catholic Church records; Beijing archdiocese'),

('上海大主教座',
 'Archdiocese of Shanghai',
 '上海', '天主教', '天主教', '羅馬禮', 1949, NULL, '現存',
 '大主教沈斌', 'Archbishop Shen Bin', 2023, '中國上海',
 '1949年升為大主教座；梵中協議後沈斌於2023年由浙江調任上海，相關爭議仍在持續。',
 'Catholic Church records; Shanghai archdiocese'),

('孟買大主教座',
 'Archdiocese of Bombay (Mumbai)',
 '孟買', '天主教', '天主教', '羅馬禮', 1534, NULL, '現存',
 '大主教菲利克斯·托皮諾', 'Archbishop Filipe Neri Ferrão', 2019, '印度孟買',
 '1534年設主教座（葡萄牙殖民地）；1886年升為大主教座；印度最大天主教城市之一。',
 'Catholic Church records; Bombay archdiocese'),

('加爾各答大主教座',
 'Archdiocese of Calcutta (Kolkata)',
 '加爾各答', '天主教', '天主教', '羅馬禮', 1834, NULL, '現存',
 '大主教托馬斯·達蘇扎', 'Archbishop Thomas D''Souza', 2010, '印度加爾各答',
 '1834年設主教座；1886年升為大主教座；德蘭修女的傳教工作基地。',
 'Catholic Church records; Calcutta archdiocese'),

('雅加達大主教座',
 'Archdiocese of Jakarta',
 '雅加達', '天主教', '天主教', '羅馬禮', 1807, NULL, '現存',
 '大主教伊格纳修斯·蘇哈約', 'Archbishop Ignatius Suharyo', 2010, '印度尼西亞雅加達',
 '1807年設主教座；1961年升為大主教座；印度尼西亞首席大主教座。',
 'Catholic Church records; Jakarta archdiocese'),

('科倫坡大主教座',
 'Archdiocese of Colombo',
 '科倫坡', '天主教', '天主教', '羅馬禮', 1834, NULL, '現存',
 '大主教馬爾科姆·蘭斯', 'Archbishop Malcolm Ranjith', 2009, '斯里蘭卡科倫坡',
 '1834年設主教座；1886年升為大主教座；斯里蘭卡天主教首席大主教座。',
 'Catholic Church records; Colombo archdiocese'),

-- 非洲
('迦太基大主教座',
 'Ancient See of Carthage',
 '迦太基', '天主教', '天主教', '羅馬禮', 200, 647, '已廢除',
 NULL, NULL, NULL, '今突尼西亞迦太基',
 '200年代設立；德爾圖良、居普良等神學家均在此服事；432年奧古斯丁在附近的希波主教座逝世；647年阿拉伯征服後廢除。',
 'Council of Carthage records; Catholic Church records'),

('阿爾及爾大主教座',
 'Archdiocese of Algiers',
 '阿爾及爾', '天主教', '天主教', '羅馬禮', 1838, NULL, '現存',
 '大主教保羅·德斯法爾日斯', 'Archbishop Paul Desfarges', 2016, '阿爾及利亞阿爾及爾',
 '1838年設主教座；1867年升為大主教座；羅伯特·拉維熱裡（馬耳他騎士）曾在此服事，推動廢除非洲奴隸制。',
 'Catholic Church records; Algiers archdiocese'),

('金沙薩大主教座',
 'Archdiocese of Kinshasa',
 '金沙薩', '天主教', '天主教', '羅馬禮', 1886, NULL, '現存',
 '大主教弗里德林·安博科', 'Archbishop Fridolin Ambongo', 2018, '剛果民主共和國金沙薩',
 '1886年設主教座；1959年升為大主教座；次撒哈拉非洲最大天主教城市。',
 'Catholic Church records; Kinshasa archdiocese'),

('奈洛比大主教座',
 'Archdiocese of Nairobi',
 '奈洛比', '天主教', '天主教', '羅馬禮', 1953, NULL, '現存',
 '大主教菲利普·奧西揚迪', 'Archbishop Philip Anyolo', 2021, '肯亞奈洛比',
 '1953年設主教座；1976年升為大主教座；東非天主教重要中心。',
 'Catholic Church records; Nairobi archdiocese'),

('達累斯薩拉姆大主教座',
 'Archdiocese of Dar es Salaam',
 '達累斯薩拉姆', '天主教', '天主教', '羅馬禮', 1953, NULL, '現存',
 '大主教若望·朱安比', 'Archbishop Jude Thaddeus Ruwa ichi', 2020, '坦尚尼亞達累斯薩拉姆',
 '1953年設主教座；1961年升為大主教座。', 'Catholic Church records; Dar es Salaam archdiocese'),

('阿比尚大主教座',
 'Archdiocese of Abidjan',
 '阿比尚', '天主教', '天主教', '羅馬禮', 1934, NULL, '現存',
 '大主教伊格纳修斯·賓達', 'Archbishop Ignace Bessi Dogbo', 2022, '象牙海岸阿比尚',
 '1934年設主教座；1955年升為大主教座；象牙海岸天主教首席大主教座。',
 'Catholic Church records; Abidjan archdiocese'),

('達喀爾大主教座',
 'Archdiocese of Dakar',
 '達喀爾', '天主教', '天主教', '羅馬禮', 1955, NULL, '現存',
 '大主教本傑明·恩迪亞耶', 'Archbishop Benjamin Ndiaye', 2021, '塞內加爾達喀爾',
 '1955年設大主教座；塞內加爾天主教首席大主教座。',
 'Catholic Church records; Dakar archdiocese'),

('坎帕拉大主教座',
 'Archdiocese of Kampala',
 '坎帕拉', '天主教', '天主教', '羅馬禮', 1894, NULL, '現存',
 '大主教約翰·卡裡', 'Archbishop Cyprian Kizito Lwanga', 2006, '烏干達坎帕拉',
 '1894年設主教座；1966年升為大主教座；烏干達聖殉道者（22位年輕信徒，1886年被穆特薩二世國王下令殉道，1964年由若望二十三世封聖）的故鄉。',
 'Catholic Church records; Kampala archdiocese'),

('亞的斯亞貝巴大主教座',
 'Archdiocese of Addis Ababa',
 '亞的斯亞貝巴', '天主教', '天主教', '羅馬禮', 1838, NULL, '現存',
 '大主教貝爾卡西姆·沙特', 'Archbishop Berhaneyesus Demerew Souraphiel', 1999, '衣索比亞亞的斯亞貝巴',
 '拉丁禮天主教（另有衣索比亞東儀天主教）；1999年升為大主教座。',
 'Catholic Church records; Addis Ababa archdiocese'),

('開普敦大主教座',
 'Archdiocese of Cape Town',
 '開普敦', '天主教', '天主教', '羅馬禮', 1837, NULL, '現存',
 '大主教斯蒂芬·鮑曼', 'Archbishop Stephen Brislin', 2009, '南非開普敦',
 '1837年設主教座；1952年升為大主教座；南非天主教首席大主教座。',
 'Catholic Church records; Cape Town archdiocese'),

('德班大主教座',
 'Archdiocese of Durban',
 '德班', '天主教', '天主教', '羅馬禮', 1850, NULL, '現存',
 '大主教雨果·塞羅', 'Archbishop Humberto Mascarenhas', 2023, '南非德班',
 '1850年設主教座；1952年升為大主教座。', 'Catholic Church records; Durban archdiocese'),

('盧沙卡大主教座',
 'Archdiocese of Lusaka',
 '盧沙卡', '天主教', '天主教', '羅馬禮', 1959, NULL, '現存',
 '大主教阿呂瓦馬利亞·穆特維', 'Archbishop Alick Banda', 2020, '尚比亞盧沙卡',
 '1959年設主教座；1969年升為大主教座。', 'Catholic Church records; Lusaka archdiocese'),

-- 大洋洲
('雪梨大主教座',
 'Archdiocese of Sydney',
 '雪梨', '天主教', '天主教', '羅馬禮', 1842, NULL, '現存',
 '大主教安東尼·費舍爾', 'Archbishop Anthony Fisher', 2014, '澳洲雪梨',
 '1842年設主教座；1937年升為大主教座；澳洲天主教首席大主教座；2008年世界青年節在此舉行。',
 'Catholic Church records; Sydney archdiocese'),

('墨爾本大主教座',
 'Archdiocese of Melbourne',
 '墨爾本', '天主教', '天主教', '羅馬禮', 1847, NULL, '現存',
 '大主教彼得·科門索利', 'Archbishop Peter Comensoli', 2018, '澳洲墨爾本',
 '1847年設主教座；1874年升為大主教座；喬治·佩爾（Cardinal George Pell）2001–2014年任此職。',
 'Catholic Church records; Melbourne archdiocese'),

('布里斯本大主教座',
 'Archdiocese of Brisbane',
 '布里斯本', '天主教', '天主教', '羅馬禮', 1859, NULL, '現存',
 '大主教蒂莫西·科斯特洛', 'Archbishop Mark Coleridge', 2012, '澳洲布里斯本',
 '1859年設主教座；1930年升為大主教座。', 'Catholic Church records; Brisbane archdiocese'),

('威靈頓大主教座',
 'Archdiocese of Wellington',
 '威靈頓', '天主教', '天主教', '羅馬禮', 1848, NULL, '現存',
 '大主教約翰·達菲', 'Archbishop John Dew', 2005, '紐西蘭威靈頓',
 '1848年設主教座；1887年升為大主教座；紐西蘭天主教首席大主教座。',
 'Catholic Church records; Wellington archdiocese'),

('蘇瓦大主教座',
 'Archdiocese of Suva',
 '蘇瓦', '天主教', '天主教', '羅馬禮', 1922, NULL, '現存',
 '大主教彼得·洛馬蒂', 'Archbishop Peter Loy Chong', 2007, '斐濟蘇瓦',
 '1922年設主教座；1969年升為大主教座；太平洋島國天主教首席大主教座。',
 'Catholic Church records; Suva archdiocese');
