-- ============================================================
-- 格涅茲諾（波蘭首席大主教）及埃斯泰爾根（匈牙利首席大主教）傳承
-- ============================================================

INSERT INTO episcopal_succession
  (name_zh, name_en, see, church, succession_number, start_year, end_year, end_reason, appointed_by, status, sources) VALUES

-- ==============================
-- 格涅茲諾（波蘭天主教首席大主教）
-- ==============================
('聖拉迪姆（高德尼烏斯）', 'Saint Radim Gaudentius', '格涅茲諾', '天主教', 1, 1000, 1006, '逝世', '教宗西爾韋斯特二世', '正統', 'Gniezno records; brother of St Adalbert; first Archbishop'),
('希波利特', 'Hippolit', '格涅茲諾', '天主教', 2, 1010, 1027, '逝世', '教宗', '正統', 'Gniezno records'),
('博蘇塔', 'Bossuta', '格涅茲諾', '天主教', 3, 1027, 1040, '逝世', '波蘭公爵', '正統', 'Gniezno records'),
('阿隆', 'Aron of Kraków', '格涅茲諾', '天主教', 4, 1046, 1059, '逝世', '教宗利奧九世', '正統', 'Gniezno records'),
('博古米烏', 'Bogumił', '格涅茲諾', '天主教', 5, 1057, 1092, '辭職（退隱）', '教宗', '正統', 'Gniezno records; beatified'),
('馬爾欽', 'Marcin of Gniezno', '格涅茲諾', '天主教', 6, 1092, 1118, '逝世', '教宗', '正統', 'Gniezno records'),
('雅庫布·澤日內', 'Jakub ze Żnina', '格涅茲諾', '天主教', 7, 1124, 1149, '逝世', '教宗卡利克斯圖斯二世', '正統', 'Gniezno records; important church reformer'),
('揚一世', 'Jan I of Gniezno', '格涅茲諾', '天主教', 8, 1149, 1167, '逝世', '教宗', '正統', 'Gniezno records'),
('彼得', 'Piotr of Gniezno', '格涅茲諾', '天主教', 9, 1176, 1180, '逝世', '教宗', '正統', 'Gniezno records'),
('彼得二世', 'Piotr II Popiełuszko', '格涅茲諾', '天主教', 10, 1184, 1198, '逝世', '教宗', '正統', 'Gniezno records'),
('亨利克·基耶特利奇', 'Henryk Kietlicz', '格涅茲諾', '天主教', 11, 1199, 1219, '逝世', '教宗英諾森三世', '正統', 'Gniezno records; church independence reform'),
('温琴蒂·尼亞萊克', 'Wincenty Niałek', '格涅茲諾', '天主教', 12, 1220, 1232, '逝世', '教宗霍諾里烏斯三世', '正統', 'Gniezno records'),
('培爾卡', 'Pełka', '格涅茲諾', '天主教', 13, 1232, 1258, '逝世', '教宗額我略九世', '正統', 'Gniezno records'),
('雅努什·蘇奇維爾克', 'Janusz Suchywilk I', '格涅茲諾', '天主教', 14, 1258, 1271, '逝世', '教宗', '正統', 'Gniezno records'),
('雅庫布·斯文卡', 'Jakub Świnka', '格涅茲諾', '天主教', 15, 1283, 1314, '逝世', '教宗尼古拉三世', '正統', 'Gniezno records; supported Polish unification'),
('博日斯拉夫', 'Borzysław', '格涅茲諾', '天主教', 16, 1314, 1317, '逝世', '教宗克萊孟五世', '正統', 'Gniezno records'),
('雅尼斯拉夫', 'Janisław', '格涅茲諾', '天主教', 17, 1317, 1341, '逝世', '教宗若望二十二世', '正統', 'Gniezno records; crowned Władysław I Łokietek 1320'),
('雅羅斯拉夫·博格裡亞', 'Jarosław Bogoria Skotnicki', '格涅茲諾', '天主教', 18, 1342, 1374, '逝世', '教宗克萊孟六世', '正統', 'Gniezno records; crowned Casimir the Great; important canon law'),
('雅努什·蘇奇維爾克二世', 'Janusz Suchywilk II', '格涅茲諾', '天主教', 19, 1374, 1382, '逝世', '教宗額我略十一世', '正統', 'Gniezno records; also Chancellor of Poland'),
('博汀塔', 'Bodzanta Poraj', '格涅茲諾', '天主教', 20, 1382, 1388, '逝世', '教宗烏爾班六世', '正統', 'Gniezno records'),
('多布羅戈斯特·諾沃德沃爾斯基', 'Dobrogost Nowodworski', '格涅茲諾', '天主教', 21, 1389, 1401, '逝世', '教宗博尼法斯九世', '正統', 'Gniezno records'),
('米科拉伊·庫羅夫斯基', 'Mikołaj Kurowski', '格涅茲諾', '天主教', 22, 1402, 1411, '逝世', '教宗博尼法斯九世', '正統', 'Gniezno records'),
('米科拉伊·特隆巴', 'Mikołaj Trąba', '格涅茲諾', '天主教', 23, 1412, 1422, '逝世', '教宗若望二十三世', '正統', 'Gniezno records; first Polish Cardinal; Council of Constance'),
('沃伊切赫·雅斯特瓦博維奇', 'Wojciech Jastrzębiec', '格涅茲諾', '天主教', 24, 1423, 1436, '逝世', '教宗馬丁五世', '正統', 'Gniezno records'),
('文茨拉夫·科齊亞納', 'Wincenty Kot', '格涅茲諾', '天主教', 25, 1436, 1448, '逝世', '教宗歐仁四世', '正統', 'Gniezno records'),
('揚·斯普羅夫斯基', 'Jan Sprowski', '格涅茲諾', '天主教', 26, 1450, 1464, '逝世', '教宗尼古拉五世', '正統', 'Gniezno records'),
('揚·格魯茲欽斯基', 'Jan Gruszczyński', '格涅茲諾', '天主教', 27, 1464, 1473, '逝世', '教宗庇護二世', '正統', 'Gniezno records'),
('雅庫布·濟斯科薩', 'Zbigniew Oleśnicki', '格涅茲諾', '天主教', 28, 1481, 1493, '逝世', '教宗', '正統', 'Gniezno records; Cardinal'),
('弗雷德里克·雅蓋降奇克', 'Fryderyk Jagiellończyk', '格涅茲諾', '天主教', 29, 1493, 1503, '逝世', '教宗亞歷山大六世', '正統', 'Gniezno records; son of King Casimir IV; Cardinal'),
('揚·沃亞斯基', 'Jan Łaski', '格涅茲諾', '天主教', 30, 1510, 1531, '逝世', '教宗利奧十世', '正統', 'Gniezno records; Commune incliti Poloniae Regni (1506); legal codification'),
('馬特烏什·德熱維茨基', 'Maciej Drzewicki', '格涅茲諾', '天主教', 31, 1531, 1535, '逝世', '教宗克萊孟七世', '正統', 'Gniezno records'),
('安德熱伊·克日茨基', 'Andrzej Krzycki', '格涅茲諾', '天主教', 32, 1535, 1537, '逝世', '教宗保羅三世', '正統', 'Gniezno records; humanist poet'),
('揚·拉塔爾斯基', 'Jan Latalski', '格涅茲諾', '天主教', 33, 1537, 1540, '逝世', '教宗保羅三世', '正統', 'Gniezno records'),
('彼得·加馬特', 'Piotr Gamrat', '格涅茲諾', '天主教', 34, 1541, 1545, '逝世', '教宗保羅三世', '正統', 'Gniezno records'),
('米科拉伊·傑熱格夫斯基', 'Mikołaj Dzierzgowski', '格涅茲諾', '天主教', 35, 1546, 1559, '逝世', '教宗保羅三世', '正統', 'Gniezno records; Council of Trent'),
('揚·普熱倫布斯基', 'Jan Przerębski', '格涅茲諾', '天主教', 36, 1559, 1562, '逝世', '教宗保羅四世', '正統', 'Gniezno records'),
('雅庫布·烏漢斯基', 'Jakub Uchański', '格涅茲諾', '天主教', 37, 1562, 1581, '逝世', '教宗庇護四世', '正統', 'Gniezno records; Polish Reformation controversies'),
('斯坦尼斯拉夫·卡爾科夫斯基', 'Stanisław Karnkowski', '格涅茲諾', '天主教', 38, 1581, 1603, '逝世', '教宗額我略十三世', '正統', 'Gniezno records; Counter-Reformation champion; crowned Sigismund III'),
('揚·塔爾諾夫斯基', 'Jan Tarnowski', '格涅茲諾', '天主教', 39, 1603, 1605, '逝世', '教宗克萊孟八世', '正統', 'Gniezno records'),
('伯納德·馬切約夫斯基', 'Bernard Maciejowski', '格涅茲諾', '天主教', 40, 1606, 1606, '轉任', '教宗保羅五世', '正統', 'Gniezno records; Cardinal; later Bishop of Kraków'),
('沃伊切赫·巴拉諾夫斯基', 'Wojciech Baranowski', '格涅茲諾', '天主教', 41, 1608, 1615, '逝世', '教宗保羅五世', '正統', 'Gniezno records'),
('勞倫特·根比茨基', 'Laurenty Gembicki', '格涅茲諾', '天主教', 42, 1616, 1624, '逝世', '教宗保羅五世', '正統', 'Gniezno records'),
('亨里克·費爾萊伊', 'Henryk Firlej', '格涅茲諾', '天主教', 43, 1624, 1626, '逝世', '教宗烏爾班八世', '正統', 'Gniezno records'),
('揚·韋日克', 'Jan Wężyk', '格涅茲諾', '天主教', 44, 1627, 1638, '逝世', '教宗烏爾班八世', '正統', 'Gniezno records; Council of Trent implementation'),
('馬切伊·烏比延斯基', 'Maciej Łubieński', '格涅茲諾', '天主教', 45, 1641, 1652, '逝世', '教宗烏爾班八世', '正統', 'Gniezno records'),
('安德熱伊·萊辛斯基', 'Andrzej Leszczyński', '格涅茲諾', '天主教', 46, 1653, 1658, '逝世', '教宗英諾森十世', '正統', 'Gniezno records; Swedish Wars era'),
('萬卡夫·萊辛斯基', 'Wacław Leszczyński', '格涅茲諾', '天主教', 47, 1659, 1666, '逝世', '教宗英諾森十世', '正統', 'Gniezno records'),
('米科拉伊·普拉日莫夫斯基', 'Mikołaj Prażmowski', '格涅茲諾', '天主教', 48, 1666, 1673, '逝世', '教宗亞歷山大七世', '正統', 'Gniezno records'),
('揚·斯特凡·維德扎', 'Jan Stefan Wydżga', '格涅茲諾', '天主教', 49, 1679, 1685, '逝世', '教宗英諾森十一世', '正統', 'Gniezno records'),
('斯坦尼斯拉夫·維特維茨基', 'Stanisław Witwicki', '格涅茲諾', '天主教', 50, 1688, 1698, '逝世', '教宗英諾森十一世', '正統', 'Gniezno records'),
('斯坦尼斯拉夫·辛比克', 'Stanisław Szembek', '格涅茲諾', '天主教', 51, 1707, 1720, '逝世', '教宗克萊孟十一世', '正統', 'Gniezno records; Northern War era'),
('泰奧多爾·波托茨基', 'Teodor Potocki', '格涅茲諾', '天主教', 52, 1723, 1738, '逝世', '教宗英諾森十三世', '正統', 'Gniezno records; interrex 1733'),
('克日什托夫·辛比克', 'Krzysztof Szembek', '格涅茲諾', '天主教', 53, 1739, 1748, '逝世', '教宗克萊孟十二世', '正統', 'Gniezno records'),
('亞當·伊格納齊·科莫羅夫斯基', 'Adam Ignacy Komorowski', '格涅茲諾', '天主教', 54, 1749, 1759, '逝世', '教宗本篤十四世', '正統', 'Gniezno records; Cardinal'),
('瓦迪斯拉夫·烏比延斯基', 'Władysław Łubieński', '格涅茲諾', '天主教', 55, 1759, 1767, '逝世', '教宗克萊孟十三世', '正統', 'Gniezno records'),
('加布里埃爾·波多斯基', 'Gabriel Podoski', '格涅茲諾', '天主教', 56, 1767, 1777, '逝世', '教宗克萊孟十四世', '正統', 'Gniezno records; Russian influence era'),
('安東尼·卡齊米日·奧斯特羅夫斯基', 'Antoni Kazimierz Ostrowski', '格涅茲諾', '天主教', 57, 1777, 1784, '逝世', '教宗庇護六世', '正統', 'Gniezno records'),
('米哈烏·波尼亞托夫斯基', 'Michał Poniatowski', '格涅茲諾', '天主教', 58, 1784, 1794, '逝世', '教宗庇護六世', '正統', 'Gniezno records; brother of King Stanislaus Augustus; Enlightenment reformer'),
('伊格納齊·拉琴斯基', 'Ignacy Raczyński', '格涅茲諾', '天主教', 59, 1806, 1818, '逝世', '教宗庇護七世', '正統', 'Gniezno records; Napoleonic era'),
('提莫特烏什·戈任斯基', 'Tymoteusz Gorzeński', '格涅茲諾', '天主教', 60, 1819, 1825, '逝世', '教宗庇護七世', '正統', 'Gniezno records; Prussian partition'),
('馬爾辛·邓博夫斯基', 'Marcin Dunin', '格涅茲諾', '天主教', 61, 1831, 1842, '逝世', '教宗額我略十六世', '正統', 'Gniezno records; resisted Prussian Kulturkampf'),
('利昂·普里日武斯基', 'Leon Przyłuski', '格涅茲諾', '天主教', 62, 1845, 1865, '逝世', '教宗額我略十六世', '正統', 'Gniezno records'),
('米奇斯拉夫·萊多霍夫斯基', 'Mieczysław Ledóchowski', '格涅茲諾', '天主教', 63, 1866, 1886, '廢黜（文化鬥爭）', '教宗庇護九世', '正統', 'Gniezno records; Cardinal; imprisoned and expelled by Bismarck'),
('尤利烏斯·迪因德爾', 'Julius Dinder', '格涅茲諾', '天主教', 64, 1886, 1890, '逝世', '教宗利奧十三世', '正統', 'Gniezno records; Kulturkampf aftermath'),
('弗洛裡安·斯塔布列夫斯基', 'Florian Stablewski', '格涅茲諾', '天主教', 65, 1891, 1906, '逝世', '教宗利奧十三世', '正統', 'Gniezno records; Polish national defender'),
('愛德蒙·達爾博爾', 'Edmund Dalbor', '格涅茲諾', '天主教', 66, 1915, 1926, '逝世', '教宗本篤十五世', '正統', 'Gniezno records; first Archbishop after Polish independence 1918; Cardinal'),
('奧古斯特·赫隆德', 'August Hlond', '格涅茲諾', '天主教', 67, 1926, 1948, '逝世', '教宗庇護十一世', '正統', 'Gniezno records; WWII; Cardinal; fled Nazi Germany, returned after war'),
('斯特凡·維辛斯基（千禧年首席主教）', 'Stefan Wyszyński (Primate of the Millennium)', '格涅茲諾', '天主教', 68, 1948, 1981, '逝世', '教宗庇護十二世', '正統', 'Gniezno records; Cardinal; imprisoned by communists 1953-1956; led Polish national-Catholic resistance; beatified 2021'),
('約瑟夫·格萊普', 'Józef Glemp', '格涅茲諾', '天主教', 69, 1981, 2009, '退休', '教宗若望保祿二世', '正統', 'Gniezno records; Cardinal; Solidarity era; controversy over Jewish relations'),
('亨里克·穆辛斯基', 'Henryk Muszyński', '格涅茲諾', '天主教', 70, 2009, 2010, '退休', '教宗本篤十六世', '正統', 'Gniezno records'),
('約瑟夫·科瓦爾奇克', 'Józef Kowalczyk', '格涅茲諾', '天主教', 71, 2010, 2014, '退休', '教宗本篤十六世', '正統', 'Gniezno records; former Apostolic Nuncio to Poland'),
('沃伊切赫·波拉克', 'Wojciech Polak', '格涅茲諾', '天主教', 72, 2014, NULL, NULL, '教宗方濟各', '正統', 'Gniezno records'),

-- ==============================
-- 埃斯泰爾根（匈牙利天主教首席大主教）
-- ==============================
('安那斯坦修斯（阿斯特里克）', 'Anastasius (Astrik)', '埃斯泰爾根', '天主教', 1, 1001, 1007, '逝世', '教宗西爾韋斯特二世', '正統', 'Esztergom records; brought the Holy Crown to Stephen I; first Archbishop'),
('多穆尼烏斯', 'Domonkos', '埃斯泰爾根', '天主教', 2, 1009, 1030, '逝世', '教宗若望十八世', '正統', 'Esztergom records'),
('布希格蘭', 'Besclin (Brezelan)', '埃斯泰爾根', '天主教', 3, 1030, 1046, '逝世', '教宗', '正統', 'Esztergom records'),
('里昂提烏斯', 'Leontius', '埃斯泰爾根', '天主教', 4, 1050, 1055, '逝世', '教宗', '正統', 'Esztergom records'),
('尼古拉斯一世', 'Miklós I', '埃斯泰爾根', '天主教', 5, 1055, 1067, '逝世', '教宗', '正統', 'Esztergom records'),
('德西德裡烏斯', 'Dezső', '埃斯泰爾根', '天主教', 6, 1067, 1083, '逝世', '教宗', '正統', 'Esztergom records; Canonization of Stephen I, Ladislaus I'),
('塞拉芬', 'Szerafin', '埃斯泰爾根', '天主教', 7, 1083, 1099, '逝世', '教宗烏爾班二世', '正統', 'Esztergom records'),
('洛倫特', 'Lőrinc', '埃斯泰爾根', '天主教', 8, 1100, 1105, '逝世', '教宗', '正統', 'Esztergom records'),
('約翰尼斯', 'Joannis I', '埃斯泰爾根', '天主教', 9, 1105, 1114, '逝世', '教宗', '正統', 'Esztergom records'),
('馬爾塞利烏斯', 'Marcellius', '埃斯泰爾根', '天主教', 10, 1114, 1137, '逝世', '教宗帕斯加爾二世', '正統', 'Esztergom records'),
('費洛培爾圖斯', 'Felicián Fülöp', '埃斯泰爾根', '天主教', 11, 1137, 1139, '逝世', '教宗', '正統', 'Esztergom records'),
('烏羅什', 'Uros', '埃斯泰爾根', '天主教', 12, 1141, 1158, '逝世', '教宗英諾森二世', '正統', 'Esztergom records'),
('盧卡斯', 'Lukács', '埃斯泰爾根', '天主教', 13, 1158, 1181, '逝世', '教宗亞歷山大三世', '正統', 'Esztergom records; resistance to Béla III; canonized later'),
('米卡', 'Mik', '埃斯泰爾根', '天主教', 14, 1181, 1183, '逝世', '教宗盧修斯三世', '正統', 'Esztergom records'),
('博薩', 'Boleszló', '埃斯泰爾根', '天主教', 15, 1183, 1184, '逝世', '教宗', '正統', 'Esztergom records'),
('若博', 'Jób', '埃斯泰爾根', '天主教', 16, 1185, 1204, '逝世', '教宗盧修斯三世', '正統', 'Esztergom records; crowned Imre I and Andrew II'),
('揚·約翰', 'János', '埃斯泰爾根', '天主教', 17, 1205, 1222, '逝世', '教宗英諾森三世', '正統', 'Esztergom records; Golden Bull 1222'),
('烏格林', 'Ugrin Csák', '埃斯泰爾根', '天主教', 18, 1219, 1241, '殉道（蒙古入侵）', '教宗霍諾里烏斯三世', '正統', 'Esztergom records; died in Battle of Mohi against Mongols'),
('伊斯特凡·班薩伊', 'István Báncsa', '埃斯泰爾根', '天主教', 19, 1242, 1254, '轉任', '教宗英諾森四世', '正統', 'Esztergom records; Cardinal; first Hungarian Cardinal'),
('法爾卡斯', 'Farkas', '埃斯泰爾根', '天主教', 20, 1256, 1262, '逝世', '教宗亞歷山大四世', '正統', 'Esztergom records'),
('菲利普', 'Fülöp Türje', '埃斯泰爾根', '天主教', 21, 1262, 1272, '逝世', '教宗烏爾班四世', '正統', 'Esztergom records'),
('尼古拉斯·卡洽', 'Miklós Kán', '埃斯泰爾根', '天主教', 22, 1273, 1274, '逝世', '教宗額我略十世', '正統', 'Esztergom records'),
('盧多維科', 'Ladomér', '埃斯泰爾根', '天主教', 23, 1279, 1298, '逝世', '教宗尼古拉三世', '正統', 'Esztergom records'),
('格雷高里', 'Gergely Bicskei', '埃斯泰爾根', '天主教', 24, 1298, 1303, '廢黜', '教宗博尼法斯八世', '正統', 'Esztergom records; conflict with Pope over appointment'),
('托馬斯', 'Tamás Bakócz', '埃斯泰爾根', '天主教', 30, 1497, 1521, '逝世', '教宗亞歷山大六世', '正統', 'Esztergom records; Cardinal; almost elected pope 1513; Estergom Basilica donor'),
('利帕依·格爾吉', 'György Lippay', '埃斯泰爾根', '天主教', 39, 1642, 1666, '逝世', '教宗烏爾班八世', '正統', 'Esztergom records; Cardinal; resisted Habsburgs'),
('塞勒佩岑尼·捷爾吉', 'György Szelepcsényi', '埃斯泰爾根', '天主教', 40, 1666, 1685, '逝世', '教宗亞歷山大七世', '正統', 'Esztergom records; Cardinal; Primate during Turkish Wars'),
('科洛尼奇·利波特', 'Lipót Kollonich', '埃斯泰爾根', '天主教', 41, 1695, 1707, '逝世', '教宗英諾森十二世', '正統', 'Esztergom records; Cardinal; opposed Protestant nobles'),
('佐伊奇·普日莫斯拉夫', 'Imre Esterházy', '埃斯泰爾根', '天主教', 43, 1725, 1745, '逝世', '教宗本篤十三世', '正統', 'Esztergom records; Cardinal'),
('鮑爾科齊·費倫茨', 'Ferenc Barkóczy', '埃斯泰爾根', '天主教', 46, 1761, 1765, '逝世', '瑪麗亞·特蕾莎', '正統', 'Esztergom records'),
('巴達尼·約瑟夫', 'József Batthyány', '埃斯泰爾根', '天主教', 47, 1776, 1799, '逝世', '教宗庇護六世', '正統', 'Esztergom records; Cardinal'),
('魯德納伊·桑多爾', 'Sándor Rudnay', '埃斯泰爾根', '天主教', 49, 1820, 1831, '逝世', '教宗庇護七世', '正統', 'Esztergom records; Cardinal; moved Primate see from Trnava back to Esztergom'),
('科帕齊·約瑟夫', 'József Kopácsy', '埃斯泰爾根', '天主教', 50, 1838, 1847, '逝世', '教宗額我略十六世', '正統', 'Esztergom records; Cardinal'),
('西托夫斯基·亞諾什', 'János Scitovszky', '埃斯泰爾根', '天主教', 51, 1849, 1866, '逝世', '教宗庇護九世', '正統', 'Esztergom records; Cardinal; 1848 Revolution era'),
('西莫爾·亞諾什', 'János Simor', '埃斯泰爾根', '天主教', 52, 1867, 1891, '逝世', '教宗庇護九世', '正統', 'Esztergom records; Cardinal; First Vatican Council'),
('瓦薩里·科洛什', 'Kolos Vaszary', '埃斯泰爾根', '天主教', 53, 1891, 1912, '退休', '教宗利奧十三世', '正統', 'Esztergom records; Cardinal'),
('澤爾諾奇·亞諾什', 'János Csernoch', '埃斯泰爾根', '天主教', 54, 1913, 1927, '逝世', '教宗庇護十世', '正統', 'Esztergom records; Cardinal; WWI era'),
('塞雷迪·尤斯廷·喬科', 'Jusztinián Serédi', '埃斯泰爾根', '天主教', 55, 1927, 1945, '逝世', '教宗庇護十一世', '正統', 'Esztergom records; Cardinal; WWII; protested deportation of Jews'),
('明德森提·約瑟夫', 'József Mindszenty', '埃斯泰爾根', '天主教', 56, 1945, 1973, '辭職（受壓）', '教宗庇護十二世', '正統', 'Esztergom records; Cardinal; tortured and imprisoned by communists 1948-1956; refugee in US Embassy 15 years; retired to Vienna; beatified 2019'),
('萊卡伊·拉斯洛', 'László Lékai', '埃斯泰爾根', '天主教', 57, 1976, 1986, '逝世', '教宗保羅六世', '正統', 'Esztergom records; Cardinal; policy of "small steps" with communists'),
('帕斯卡伊·拉斯洛', 'László Paskai', '埃斯泰爾根', '天主教', 58, 1987, 2002, '退休', '教宗若望保祿二世', '正統', 'Esztergom records; Cardinal'),
('厄爾道·彼得', 'Péter Erdő', '埃斯泰爾根', '天主教', 59, 2002, NULL, NULL, '教宗若望保祿二世', '正統', 'Esztergom records; Cardinal; canon law scholar; CCEE President');

-- 設定 predecessor_id（各 see 內連鏈）
UPDATE episcopal_succession es
SET predecessor_id = prev.id
FROM (
  SELECT id,
    LAG(id) OVER (PARTITION BY see, church ORDER BY succession_number) AS prev_id
  FROM episcopal_succession
  WHERE see IN ('格涅茲諾', '埃斯泰爾根')
) prev
WHERE es.id = prev.id AND prev.prev_id IS NOT NULL;
