#!/usr/bin/env python3
"""Pick one OpenMoji picture per Greek flashcard, or leave the card blank.

Same rule as the Hebrew deck: a wrong picture on a printed card teaches a sense
the word does not carry, so the matcher would rather leave a blank. Greek adds
one pass the Hebrew deck could not use.

The two decks share a Chinese gloss vocabulary. When a Greek word's Chinese
meaning is one a Hebrew card already carries, the Hebrew card's picture is the
right picture for it too — πῦρ and אֵשׁ are both 「火」 and both want the flame.
That transfer costs nothing and inherits the hand-curation already done.

After it come the same English-name pass and the same refusal to guess.

Licence: OpenMoji 17.0.0, CC BY-SA 4.0 (https://openmoji.org).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from match_flashcard_images import (  # noqa: E402
    AMBIGUOUS_EN,
    CACHE,
    IMAGE_DIR,
    english_candidates,
    ensure_openmoji,
    image_path,
    load_openmoji,
)

ROOT = Path(__file__).resolve().parents[1]
VOCAB = ROOT / "data/originalReaders/vocabulary/greek-2000.json"
GLOSSES = ROOT / "output/source-cache/original-readers/greek-full/greek-2000-gloss-zh-by-lemma.json"
HEBREW_IMAGES = CACHE / "hebrew-card-images.json"
OUTPUT = CACHE / "greek-card-images.json"

# Greek words whose picture is worth naming by hand: the ones every reader meets
# first, and the function words no English gloss will match.
OVERRIDES: dict[str, str] = {
    "θεός": "palms up together",
    "κύριος": "crown",
    "Ἰησοῦς": "person",
    "ἄνθρωπος": "person",
    "ἀνήρ": "man",
    "γυνή": "woman",
    "υἱός": "boy",
    "θυγάτηρ": "girl",
    "πατήρ": "man",
    "μήτηρ": "woman",
    "ἀδελφός": "men holding hands",
    "ἀδελφή": "women holding hands",
    "τέκνον": "child",
    "παιδίον": "child",
    "λαός": "busts in silhouette",
    "ὄχλος": "busts in silhouette",
    "βασιλεύς": "crown",
    "δοῦλος": "construction worker",
    "ἄγγελος": "envelope with arrow",
    "προφήτης": "loudspeaker",
    "ἀπόστολος": "outbox tray",
    "μαθητής": "graduation cap",
    "ἱερεύς": "raising hands",
    "οἶκος": "house",
    "οἰκία": "house",
    "πόλις": "cityscape",
    "ἱερόν": "classical building",
    "ναός": "classical building",
    "θύρα": "door",
    "ὁδός": "motorway",
    "γῆ": "globe showing Europe-Africa",
    "οὐρανός": "cloud",
    "θάλασσα": "water wave",
    "ὄρος": "mountain",
    "ἔρημος": "desert",
    "ὕδωρ": "droplet",
    "πῦρ": "fire",
    "φῶς": "light bulb",
    "σκοτία": "new moon",
    "ἥλιος": "sun",
    "ἀστήρ": "star",
    "ἡμέρα": "sun",
    "νύξ": "night with stars",
    "ὥρα": "hourglass done",
    "ἔτος": "spiral calendar",
    "χρόνος": "hourglass done",
    "ἄρτος": "bread",
    "οἶνος": "wine glass",
    "ἰχθύς": "fish",
    "πρόβατον": "ewe",
    "ἀμνός": "ewe",
    "ποιμήν": "dog",
    "καρδία": "red heart",
    "ὀφθαλμός": "eye",
    "στόμα": "mouth",
    "χείρ": "hand with fingers splayed",
    "πούς": "foot",
    "κεφαλή": "brain",
    "οὖς": "ear",
    "αἷμα": "drop of blood",
    "σάρξ": "cut of meat",
    "σῶμα": "person standing",
    "ψυχή": "lungs",
    "πνεῦμα": "wind face",
    "φωνή": "speaker high volume",
    "λόγος": "speech balloon",
    "ῥῆμα": "speech balloon",
    "ὄνομα": "name badge",
    "βιβλίον": "open book",
    "γραφή": "scroll",
    "νόμος": "scroll",
    "ἐπιστολή": "envelope with arrow",
    "ἀργύριον": "coin",
    "χρυσός": "gem stone",
    "ἱμάτιον": "t-shirt",
    "ὑπόδημα": "man’s shoe",
    "μάχαιρα": "dagger",
    "σταυρός": "latin cross",
    "ποτήριον": "cup with straw",
    "τράπεζα": "fork and knife",
    "θρόνος": "chair",
    "λίθος": "rock",
    "δένδρον": "deciduous tree",
    "καρπός": "red apple",
    "σπέρμα": "seedling",
    "ἀγρός": "sheaf of rice",
    "ἄμπελος": "grapes",
    "λέγω": "speech balloon",
    "λαλέω": "speaking head",
    "ἀκούω": "ear",
    "βλέπω": "eyes",
    "ὁράω": "eyes",
    "γινώσκω": "brain",
    "οἶδα": "brain",
    "πιστεύω": "handshake",
    "ἀγαπάω": "two hearts",
    "φιλέω": "two hearts",
    "μισέω": "angry face",
    "θέλω": "thinking face",
    "ἔρχομαι": "door",
    "πορεύομαι": "person walking",
    "περιπατέω": "person walking",
    "τρέχω": "person running",
    "ἵστημι": "person standing",
    "κάθημαι": "chair",
    "ἐσθίω": "fork and knife",
    "πίνω": "cup with straw",
    "γράφω": "writing hand",
    "δίδωμι": "wrapped gift",
    "λαμβάνω": "raised fist",
    "ἀποστέλλω": "outbox tray",
    "εὑρίσκω": "magnifying glass tilted left",
    "ζητέω": "magnifying glass tilted left",
    "ποιέω": "hammer and wrench",
    "ἐργάζομαι": "hammer and wrench",
    "οἰκοδομέω": "building construction",
    "ἀποθνῄσκω": "skull",
    "θάνατος": "skull",
    "ζάω": "beating heart",
    "ζωή": "seedling",
    "γεννάω": "baby",
    "σῴζω": "ring buoy",
    "σωτηρία": "ring buoy",
    "κρίνω": "balance scale",
    "κρίσις": "balance scale",
    "δικαιοσύνη": "balance scale",
    "δίκαιος": "smiling face with halo",
    "ἅγιος": "sparkles",
    "ἁμαρτία": "broken heart",
    "ἁμαρτάνω": "broken heart",
    "εἰρήνη": "dove",
    "χαρά": "partying face",
    "χαίρω": "partying face",
    "κλαίω": "crying face",
    "φοβέομαι": "fearful face",
    "προσεύχομαι": "folded hands",
    "εὐχαριστέω": "raising hands",
    "δόξα": "glowing star",
    "δύναμις": "flexed biceps",
    "ἐξουσία": "crown",
    "σοφία": "brain",
    "ἀλήθεια": "hundred points",
    "πίστις": "handshake",
    "ἐλπίς": "seedling",
    "ἀγάπη": "two hearts",
    "χάρις": "wrapped gift",
    "διαθήκη": "handshake",
    "βασιλεία": "castle",
    "ἐκκλησία": "busts in silhouette",
    "εὐαγγέλιον": "megaphone",
    "πόλεμος": "crossed swords",
    "διάβολος": "smiling face with horns",
    "πονηρός": "smiling face with horns",
    "κακός": "angry face",
    "ἀγαθός": "thumbs up",
    "καλός": "thumbs up",
    "μέγας": "snow-capped mountain",
    "μικρός": "ant",
    "πολύς": "chart increasing",
    "πρῶτος": "1st place medal",
    "δεύτερος": "2nd place medal",
    "τρίτος": "3rd place medal",
    # 上冊高頻補列
    "ἔσχατος": "end arrow",
    "κόσμος": "globe with meridians",
    "αἰών": "infinity",
    "αἰώνιος": "infinity",
    "καιρός": "timer clock",
    "ὥρα": "timer clock",
    "ὁ": "label",
    "ἀρχή": "play button",
    "ἄρχομαι": "play button",
    "εἶπεν": "speech balloon",
    "ἀπό": "left arrow",
    "ἦν": "BACK arrow",
    "παρά": "backhand index pointing left",
    "παραβολή": "thought balloon",
    "θέλημα": "thinking face",
    "πρός": "right arrow",
    "ἀγαπητός": "smiling face with hearts",
    "ἀλλήλων": "people holding hands",
    "ἐμός": "person raising hand",
    "μοῦ": "person raising hand",
    "κἀγώ": "person raising hand",
    "ἑαυτοῦ": "mirror",
    "καθώς": "heavy equals sign",
    "ὡς": "heavy equals sign",
    "νεκρός": "skull",
    "πιστός": "handshake",
    "εἰ μή": "shuffle tracks button",
    "εἴτε": "shuffle tracks button",
    "ἤ": "shuffle tracks button",
    "ἄν": "shuffle tracks button",
    "περί": "clockwise vertical arrows",
    "τὶς": "bust in silhouette",
    "οὐδέ": "prohibited",
    "οὔτε": "prohibited",
    "μηδέ": "prohibited",
    "οὐχί": "prohibited",
    "διδάσκαλος": "teacher",
    "διδάσκω": "teacher",
    "εὐθύς": "straight ruler",
    "μέν": "check mark",
    "ὑπάρχω": "check mark",
    "μηδείς": "hole",
    "μόνος": "keycap: 1",
    "ὅπως": "bullseye",
    "ὅσος": "red question mark",
    "πῶς": "red question mark",
    "ἐρωτάω": "red question mark",
    "πάλιν": "repeat button",
    "ἔτι": "repeat button",
    "ὑπέρ": "up arrow",
    "ἀνίστημι": "up arrow",
    "δώδεκα": "input numbers",
    "μακάριος": "star-struck",
    "σημεῖον": "sparkles",
    "ἐνώπιον": "eyes",
    "θεωρέω": "eyes",
    "ἐπαγγελία": "handshake",
    "κατά": "down arrow",
    "ὅς": "link",
    "ὅστις": "link",
    "ὅτε": "alarm clock",
    "ὅταν": "alarm clock",
    "πλοῖον": "sailboat",
    "λύω": "unlocked",
    "ἀνοίγω": "unlocked",
    "ὅπου": "round pushpin",
    "τυφλός": "person with white cane",
    "δαιμόνιον": "ghost",
    "καλέω": "loudspeaker",
    "κράζω": "loudspeaker",
    "πλείων": "chart increasing",
    "μείζων": "chart increasing",
    "μᾶλλον": "chart increasing",
    "δεῖ": "red exclamation mark",
    "συνάγω": "busts in silhouette",
    "ἐκκλησία": "busts in silhouette",
    "ὅλος": "bar chart",
    "ἕκαστος": "bar chart",
    "προσκυνέω": "person kneeling",
    "ἀποκτείνω": "skull and crossbones",
    "βαπτίζω": "droplet",
    "ἐγείρω": "sunrise",
    "ἀνάστασις": "sunrise",
    "ἐκβάλλω": "outbox tray",
    "μένω": "house",
    "ἀκολουθέω": "footprints",
    "γίνομαι": "counterclockwise arrows button",
    "εἰσέρχομαι": "door",
    "προσέρχομαι": "right arrow",
    "ἄγω": "right arrow",
    "κηρύσσω": "megaphone",
    "εὐαγγελίζω": "megaphone",
    "ἀπαγγέλλω": "megaphone",
    "αἰτέω": "folded hands",
    "μαρτυρέω": "speaking head",
    "πείθω": "speaking head",
    "ἀρχιερεύς": "raising hands",
    "δεξιός": "backhand index pointing right",
    "παρακαλέω": "people hugging",
    "ἀσπάζομαι": "waving hand",
    "ἀπολύω": "waving hand",
    "γραμματεύς": "writing hand",
    "σπείρω": "seedling",
    "δέχομαι": "open hands",
    "διακονία": "open hands",
    "δοκέω": "thinking face",
    "φέρω": "package",
    "λοιπός": "package",
    "πρεσβύτερος": "older person",
    "μέλλω": "SOON arrow",
    "ἀπόλλυμι": "wilted flower",
    "παραδίδωμι": "wrapped gift",
    "ἁγιάζω": "sparkles",
    "ἁμαρτωλός": "broken heart",
    "δικαιόω": "balance scale",
    "θλῖψις": "cloud with lightning",
    "σταυρόω": "latin cross",
    "σωτήρ": "ring buoy",
    "φανερόω": "light bulb",
    "φόβος": "fearful face",
    # 上冊補列（二）
    "δέ": "left-right arrow",
    "μέσος": "left-right arrow",
    "πλήν": "left-right arrow",
    "ἀφίημι": "unlocked",
    "δείκνυμι": "index pointing up",
    "ἴδιος": "mirror",
    "σεαυτοῦ": "mirror",
    "τίθημι": "pushpin",
    "φημί": "speech balloon",
    "ἄρα": "end arrow",
    "τέλος": "end arrow",
    "παραλαμβάνω": "open hands",
    "χρεία": "red exclamation mark",
    "ἀποδίδωμι": "counterclockwise arrows button",
    "μετανοέω": "counterclockwise arrows button",
    "ἔμπροσθεν": "eyes",
    "ποῦ": "red question mark",
    "ποῖος": "red question mark",
    "πόθεν": "red question mark",
    "πόσος": "red question mark",
    "κρατέω": "raised fist",
    "οὐκέτι": "prohibited",
    "χωρίς": "prohibited",
    "μήτε": "prohibited",
    "ἀρνέομαι": "prohibited",
    "καταργέω": "prohibited",
    "πρό": "BACK arrow",
    "ὀπίσω": "BACK arrow",
    "προσφέρω": "wrapped gift",
    "θηρίον": "lion",
    "καθίζω": "chair",
    "οὐαί": "warning",
    "σκανδαλίζω": "warning",
    "διώκω": "person running",
    "φεύγω": "person running",
    "ὅμοιος": "heavy equals sign",
    "ὥσπερ": "heavy equals sign",
    "ὁμοίως": "heavy equals sign",
    "ἐπιγινώσκω": "brain",
    "συνείδησις": "brain",
    "γνῶσις": "brain",
    "κατοικέω": "house with garden",
    "δέω": "chains",
    "διέρχομαι": "bridge at night",
    "θαυμάζω": "astonished face",
    "θεραπεύω": "adhesive bandage",
    "φωνέω": "loudspeaker",
    "ἐπικαλέω": "loudspeaker",
    "προσκαλέω": "loudspeaker",
    "προφητεύω": "loudspeaker",
    "καινός": "NEW button",
    "πάσχω": "face with head-bandage",
    "ἄξιος": "check mark",
    "ἱκανός": "check mark",
    "ναί": "check mark",
    "ἔξεστιν": "check mark",
    "πάντοτε": "repeat button",
    "παρίστημι": "person standing",
    "σήμερον": "calendar",
    "τιμή": "money bag",
    "ὀφείλω": "money bag",
    "μισθός": "money bag",
    "πλούσιος": "money bag",
    "ἑτοιμάζω": "package",
    "βαστάζω": "package",
    "λογίζομαι": "abacus",
    "μνημεῖον": "coffin",
    "ὀλίγος": "ant",
    "ἐπιτίθημι": "up arrow",
    "περισσεύω": "chart increasing",
    "πλανάω": "drooling face",
    "ἐπιθυμία": "drooling face",
    "πράσσω": "hammer and wrench",
    "πειράζω": "smiling face with horns",
    "Σατανᾶς": "smiling face with horns",
    "ὑποτάσσω": "person bowing",
    "ἄρχων": "crown",
    "ἡγέομαι": "crown",
    "βούλομαι": "thinking face",
    "ἐκεῖθεν": "left arrow",
    "καλῶς": "thumbs up",
    "καυχάομαι": "flexed biceps",
    "δυνατός": "flexed biceps",
    "ἰσχυρός": "flexed biceps",
    "ἰσχύω": "flexed biceps",
    "παῤῥησία": "flexed biceps",
    "μαρτυρία": "speaking head",
    "μάρτυς": "speaking head",
    "παραγίνομαι": "door",
    "εὐθέως": "high voltage",
    "ὀργή": "anger symbol",
    "ἐπιτιμάω": "anger symbol",
    "περιτομή": "scissors",
    "ἅπας": "bar chart",
    "βλασφημέω": "face with symbols on mouth",
    "μέλος": "leg",
    "πτωχός": "hole",
    "ἀσθενέω": "face with thermometer",
    "ἀκάθαρτος": "biohazard",
    "ἀναγινώσκω": "open book",
    "ἐχθρός": "angry face with horns",
    "ἀδικέω": "angry face",
    "ὑπομονή": "hourglass not done",
    "ποτέ": "hourglass done",
    "ἄνεμος": "wind face",
    "ἐγγύς": "right arrow",
    "ἐλπίζω": "seedling",
    "καθαρίζω": "soap",
    "καθαρός": "soap",
    "φαίνω": "light bulb",
    "φυλή": "busts in silhouette",
    "συνέρχομαι": "busts in silhouette",
    "ἀγοράζω": "shopping bags",
    "διδαχή": "teacher",
    "διάκονος": "construction worker",
    "παράκλησις": "people hugging",
    "ἐλεέω": "people hugging",
    "ἔλεος": "people hugging",
    "παρέρχομαι": "dashing away",
    "πάσχα": "ewe",
    "θυσία": "goat",
    "φίλος": "handshake",
    "ἀληθινός": "hundred points",
    "γαμέω": "wedding",
    "μυστήριον": "crystal ball",
    "νικάω": "trophy",
    "χώρα": "world map",
    "ἐνδύω": "t-shirt",
    "κώμη": "houses",
    # 下冊（教父詞彙）補列
    "φύσις": "dna",
    "δαίμων": "ghost",
    "τοσοῦτος": "chart increasing",
    "μάλιστα": "chart increasing",
    "θεῖος": "sparkles",
    "θεότης": "sparkles",
    "ἐπιφάνεια": "sparkles",
    "μανθάνω": "graduation cap",
    "ἡμέτερος": "people holding hands",
    "ὁμόνοια": "people holding hands",
    "λίαν": "collision",
    "ἀνθρώπινος": "person",
    "ὅλως": "bar chart",
    "πάντως": "bar chart",
    "τάγμα": "bar chart",
    "εἶτα": "SOON arrow",
    "προερέω": "SOON arrow",
    "κτίσις": "hammer and wrench",
    "δημιουργός": "hammer and wrench",
    "χράομαι": "hammer and wrench",
    "ὄργανον": "hammer and wrench",
    "κἄν": "shuffle tracks button",
    "ὁμολογέω": "speaking head",
    "λοιπόν": "package",
    "ἐπειδή": "right arrow curving down",
    "αἰτία": "right arrow curving down",
    "δηλόω": "light bulb",
    "γνωρίζω": "light bulb",
    "φανερός": "light bulb",
    "νομίζω": "thinking face",
    "φρονέω": "thinking face",
    "ξηρός": "desert",
    "ἐπίσκοπος": "eyes",
    "ἐπισκοπέω": "eyes",
    "αἴσθησις": "eyes",
    "ὅθεν": "end arrow",
    "οἷος": "red question mark",
    "ἀγνοέω": "red question mark",
    "χλωρός": "green circle",
    "λευκός": "white circle",
    "ποικίλος": "rainbow",
    "μέχρι": "stop sign",
    "τυγχάνω": "raised fist",
    "ἐπιτυγχάνω": "raised fist",
    "κοινός": "handshake",
    "μεταλαμβάνω": "handshake",
    "ἀληθῶς": "hundred points",
    "τέλειος": "hundred points",
    "ἀξιόω": "check mark",
    "πρέπω": "check mark",
    "ἀπόδειξις": "check mark",
    "πάρειμι": "round pushpin",
    "πάθος": "face with head-bandage",
    "ἐπιδίδωμι": "wrapped gift",
    "ἄφεσις": "unlocked",
    "κατανοέω": "brain",
    "νοῦς": "brain",
    "ἀφθαρσία": "infinity",
    "ἀθάνατος": "infinity",
    "ἄφθαρτος": "infinity",
    "κινέω": "dashing away",
    "παρέχω": "open hands",
    "πρόνοια": "open hands",
    "προσδέχομαι": "open hands",
    "κολάζω": "hammer",
    "βάσανος": "hammer",
    "ἀόρατος": "hole",
    "τιμάω": "raising hands",
    "βοτάνη": "herb",
    "ἀδύνατος": "prohibited",
    "ἄπιστος": "prohibited",
    "ἄνευ": "prohibited",
    "τύπος": "label",
    "σημαίνω": "label",
    "φαῦλος": "angry face",
    "καταφρονέω": "angry face",
    "ὕλη": "wood",
    "λύπη": "crying face",
    "ἀπάτη": "lying face",
    "ἀπατάω": "lying face",
    "κεῖμαι": "bed",
    "ζῆλος": "fire",
    "τίμιος": "gem stone",
    "τρυφή": "gem stone",
    "θνητός": "skull",
    "ἀνάγκη": "red exclamation mark",
    "ὦ": "red exclamation mark",
    "οἰκουμένη": "globe with meridians",
    "πανταχοῦ": "world map",
    "ἁπλῶς": "keycap: 1",
    "πρότερος": "BACK arrow",
    "πάλαι": "hourglass done",
    "μνημονεύω": "thought balloon",
    "γνώμη": "thought balloon",
    "κυρία": "woman",
    "ἀήρ": "wind face",
    "πνευματικός": "wind face",
    "θαυμαστός": "astonished face",
    "ἄτοπος": "confused face",
    "παρουσία": "door",
    "προσδοκάω": "hourglass not done",
    "ἐπιδείκνυμι": "index pointing up",
    "χωρέω": "basket",
    "ἀρετή": "smiling face with halo",
    "σχισμή": "scissors",
    "προλέγω": "warning",
    "ἐπουράνιος": "cloud",
    "ἀποτίθημι": "wastebasket",
    "ἀποβάλλω": "wastebasket",
    "τροφή": "fork and knife",
    "ἐπιθυμέω": "drooling face",
    "προφητικός": "loudspeaker",
    "κάτω": "down arrow",
    "ἄνωθεν": "up arrow",
    "σέβομαι": "person kneeling",
    "ποιητής": "writing hand",
    "ἀκοή": "ear",
    "κἀκεῖνος": "backhand index pointing right",
    "ἔντευξις": "folded hands",
    "φθαρτός": "wilted flower",
    "ἀπέχω": "left-right arrow",
    "νόσος": "face with thermometer",
    "ἁρμόζω": "puzzle piece",
    "ὁρίζω": "straight ruler",
    "δόγμα": "scroll",
    # 虛詞以符號會意
    "οὐ (οὐκ": "prohibited",
    "οὐ": "prohibited",
    "μή": "prohibited",
    "εἰς": "right arrow",
    "ἐκ (ἐξ)": "left arrow",
    "ἐν": "input latin letters",
    "ἐπί": "up arrow",
    "ὑπό": "down arrow",
    "σύν": "handshake",
    "μετά": "handshake",
    "διά": "right arrow curving down",
    "γάρ": "right arrow curving down",
    "ὅτι": "right arrow curving down",
    "ἵνα": "bullseye",
    "ἐάν": "shuffle tracks button",
    "εἰ": "shuffle tracks button",
    "ὥστε": "end arrow",
    "οὖν": "end arrow",
    "καί": "plus",
    "ἀλλά": "left-right arrow",
    "νῦν": "alarm clock",
    "ἤδη": "repeat button",
    "ἰδού": "eyes",
    "ἴδε": "eyes",
    "ἐγώ": "person raising hand",
    "σύ": "index pointing at the viewer",
    "ἡμεῖς": "people holding hands",
    "ὑμεῖς": "busts in silhouette",
    "οὗτος": "backhand index pointing down",
    "ἐκεῖνος": "backhand index pointing right",
    "τίς": "red question mark",
    "πᾶς": "bar chart",
    "εἷς": "keycap: 1",
    "δύο": "keycap: 2",
    "τρεῖς": "keycap: 3",
    "ὧδε": "round pushpin",
    "ἐκεῖ": "round pushpin",
    "οὐδείς": "hole",
    "ἀμήν": "check mark",

# --- 2026-08-26 逐張補齊：以下由人工逐詞挑圖，目標是每張卡都有圖 ---------
    "ἱλαστήριον": "place of worship",
    "ἀποκαλύπτω": "eye in speech bubble",
    "ἀσθενής": "face with thermometer",
    "γέ": "check mark",
    "ἐπεί": "right arrow curving down",
    "ἥκω": "airplane arrival",
    "σέ": "index pointing at the viewer",
    "σοί": "index pointing at the viewer",
    "ὑμῶν": "busts in silhouette",
    "ὑμῖν": "busts in silhouette",
    "ὑμᾶς": "busts in silhouette",
    "μέ": "person raising hand",
    "μοι": "person raising hand",
    "ἐμέ": "person raising hand",
    "ἐμοί": "person raising hand",
    "ἡμᾶς": "people holding hands",
    "ἡμῖν": "people holding hands",
    "ἐνώπιος": "eyes",
    "ἐναντίον": "left-facing fist",
    "ἀποστρέφω": "left arrow curving right",
    "ὅδε": "backhand index pointing down",
    "σκηνή": "tent",
    "ἐντέλλομαι": "clipboard",
    "φοβέω": "fearful face",
    "σφόδρα": "hundred points",
    "πύλη": "door",
    "ἀνά": "input numbers",
    "διότι": "right arrow curving down",
    "παρεμβολή": "camping",
    "θυμός": "enraged face",
    "ἀλλόφυλος": "world map",
    "ξύλον": "wood",
    "προστίθημι": "plus",
    "δή": "check mark",
    "χρυσίον": "ring",
    "ἔναντι": "eyes",
    "ἐξαποστέλλω": "outbox tray",
    "ἀσεβής": "smiling face with horns",
    "ῥομφαία": "dagger",
    "εὐφραίνω": "partying face",
    "εἰσακούω": "ear with hearing aid",
    "κύκλῳ": "circled anticlockwise arrow",
    "τίκτω": "pregnant woman",
    "μόσχος": "cow",
    "συντρίβω": "collision",
    "ἀδικία": "cross mark",
    "ἀνομία": "prohibited",
    "ἐξάγω": "exit",
    "τρόπος": "signpost",
    "ἀφίστημι": "person walking",
    "ἐξολοθρεύω": "bomb",
    "ὁλοκαύτωμα": "warning fire",
    "ἔλαιον": "olive",
    "κοιμάω": "sleeping face",
    "χρύσεος": "gem stone",
    "πρωΐ": "sunrise",
    "τεῖχος": "brick",
    "παρεμβάλλω": "tent",
    "σοφός": "nerd face",
    "κριός": "ram",
    "ἐκλείπω": "chart decreasing",
    "καθίστημι": "name badge",
    "πεδίον": "national park",
    "ὡσεί": "heavy equals sign",
    "προσάγω": "palm up hand",
    "χεῖλος": "mouth",
    "πατριά": "family",
    "ἀριθμός": "input numbers",
    "βουλή": "thought balloon",
    "ἀντί": "counterclockwise arrows button",
    "ἐπισκέπτομαι": "person walking",
    "ἀλλότριος": "world map",
    "πρόσταγμα": "scroll",
    "ἀφαιρέω": "minus",
    "θανατόω": "skull",
    "ταπεινόω": "person kneeling",
    "ἀναφέρω": "raising hands",
    "δουλεύω": "construction worker",
    "ἐκκλίνω": "left arrow curving right",
    "κατεσθίω": "face savoring food",
    "εὐφροσύνη": "party popper",
    "εἰσάγω": "inbox tray",
    "μερίς": "pie",
    "ἐπάγω": "package",
    "δικαίωμα": "balance scale",
    "ἐκτείνω": "open hands",
    "ἐκλέγω": "check box with check",
    "ἐκχέω": "pouring liquid",
    "σωτήριος": "ring buoy",
    "ἄφρων": "clown face",
    "κλῆρος": "game die",
    "ἕνεκα": "right arrow curving down",
    "βοάω": "megaphone",
    "θύω": "kitchen knife",
    "μιαίνω": "splatter",
    "χάλκεος": "bell",
    "ἀμφότερος": "people holding hands",
    "διαβαίνω": "bridge at night",
    "ἕβδομος": "keycap: 7",
    "ἑσπέρα": "sunset",
    "ὀστέον": "bone",
    "συντάσσω": "clipboard",
    "ἐπάνω": "up arrow",
    "βραχίων": "flexed biceps",
    "σύνεσις": "brain",
    "ἄδικος": "cross mark",
    "προσέχω": "eyes",
    "ὕψιστος": "top arrow",
    "ἅμα": "handshake",
    "ἅπτομαι": "index pointing up",
    "ἐπιβλέπω": "eyes",
    "καθά": "heavy equals sign",
    "ἀναστρέφω": "person walking",
    "δεικνύω": "backhand index pointing right",
    "ἐξιλάσκομαι": "folded hands",
    "ἐπέρχομαι": "airplane arrival",
    "ἀνάγω": "up arrow",
    "νέος": "baby",
    "πέραν": "bridge at night",
    "λυτρόω": "broken chain",
    "ψευδής": "lying face",
    "συλλαμβάνω": "police officer",
    "ταράσσω": "cyclone",
    "χίλιοι": "input numbers",
    "λειτουργέω": "raising hands",
    "ἐκλεκτός": "check box with check",
    "ἄνομος": "prohibited",
    "κατάλοιπος": "hourglass not done",
    "κατισχύω": "flexed biceps",
    "πληγή": "adhesive bandage",
    "σκῦλον": "treasure chest",
    "ἐπακούω": "ear with hearing aid",
    "χειμάρρους": "water wave",
    "κατακαίω": "fire",
    "στέαρ": "butter",
    "οἰκέω": "house with garden",
    "εἰσφέρω": "inbox tray",
    "θλίβω": "weary face",
    "αἰσχύνω": "face with hand over mouth",
    "νεανίσκος": "boy",
    "καθαιρέω": "hammer",
    "θησαυρός": "treasure chest",
    "ὑποκάτω": "down arrow",
    "ἄκρον": "top arrow",
    "σάλπιγξ": "trumpet",
    "κυκλόθεν": "circled anticlockwise arrow",
    "πηγή": "fountain",
    "κυκλόω": "circled anticlockwise arrow",
    "μιμνήσκω": "thought balloon",
    "βοηθέω": "handshake",
    "ἐκδικέω": "balance scale",
    "τελευτάω": "headstone",
    "φείδομαι": "open hands",
    "πρᾶγμα": "briefcase",
    "κόπτω": "axe",
    "στολή": "woman’s clothes",
    "εἴδωλον": "moai",
    "λατρεύω": "folded hands",
    "γένος": "family",
    "προσήλυτος": "airplane arrival",
    "ἀφορίζω": "scissors",
    "διατίθεμαι": "handshake",
    "ῥίπτω": "baseball",
    "ἄμωμος": "white flower",
    "φάραγξ": "mountain",
    "κρέας": "cut of meat",
    "τραυματίας": "adhesive bandage",
    "σῖτος": "sheaf of rice",
    "ἡγεμών": "man judge",
    "βουλεύω": "thought balloon",
    "ἀφανίζω": "dashing away",
    "ὀσμή": "nose",
    "ἀνταποδίδωμι": "counterclockwise arrows button",
    "καίω": "fire",
    "νότος": "compass",
    "κατέναντι": "left-facing fist",
    "διάψαλμα": "musical note",
    "ἐκφέρω": "outbox tray",
    "ἀργύρεος": "coin",
    "σκήνωμα": "tent",
    "δέκατος": "keycap: 10",
    "μεγαλύνω": "chart increasing",
    "πένης": "empty nest",
    "χρίω": "lotion bottle",
    "διακόσιοι": "input numbers",
    "συνάντησις": "handshake",
    "ὀνειδισμός": "face with symbols on mouth",
    "δέησις": "folded hands",
    "αἰσχύνη": "face with hand over mouth",
    "παιδεία": "graduation cap",
    "εὐλογητός": "smiling face with halo",
    "γέννημα": "seedling",
    "μάταιος": "hole",
    "ἀπαρχή": "sheaf of rice",
    "σίκλος": "coin",
    "μέτρον": "straight ruler",
    "ἐξεγείρω": "alarm clock",
    "ἐκδίκησις": "balance scale",
    "ᾄδω": "microphone",
    "παύω": "stop button",
    "κενός": "hole",
    "κοίτη": "bed",
    "εὐοδόω": "chart increasing",
    "τράχηλος": "necktie",
    "ἐμβάλλω": "inbox tray",
    "κατάγω": "down arrow",
    "καταισχύνω": "face with hand over mouth",
    "ἀγαλλιάω": "partying face",
    "τριακόσιοι": "input numbers",
    "καταράομαι": "face with symbols on mouth",
    "ἐρημόω": "desert",
    "τρίβος": "footprints",
    "βάσις": "brick",
    "ἀσέβεια": "smiling face with horns",
    "ἐπιβάλλω": "palm down hand",
    "κακόω": "face with head-bandage",
    "δεῦρο": "backhand index pointing down",
    "ἐγκαταλείπω": "empty nest",
    "ἐξίστημι": "astonished face",
    "αιλαμ": "world map",
    "κατάσχεσις": "flagged point",
    "νόμιμος": "check mark button",
    "ἱππεύς": "horse riding",
    "ἔξοδος": "airplane departure",
    "ταπεινός": "person bowing",
    "ὅπλον": "shield",
    "ἑξακόσιοι": "input numbers",
    "διασπείρω": "leaf fluttering in wind",
    "ὀργίζω": "angry face",
    "μνημόσυνον": "reminder ribbon",
    "ἐφίστημι": "person standing",
    "ὑπομένω": "person climbing",
    "νεότης": "hatching chick",
    "σεμίδαλις": "flatbread",
    "περιβάλλω": "coat",
    "ὀσφύς": "jeans",
    "δρυμός": "evergreen tree",
    "ποτίζω": "glass of milk",
    "πρότερον": "back arrow",
    "ἀνάπαυσις": "person in bed",
    "ἀθετέω": "wastebasket",
    "σαβαώθ": "crossed swords",
    "ξηραίνω": "leafless tree",
    "δυσμή": "sunset",
    "πενθέω": "crying face",
    "διηγέομαι": "left speech bubble",
    "ἀναπαύω": "person in bed",
    "ἀνθίστημι": "right-facing fist",
    "κριτής": "judge",
    "ὑμνέω": "musical notes",
    "διάνοια": "thought balloon",
    "ἀρσενικός": "male sign",
    "ὄψις": "mirror",
    "μακράν": "telescope",
    "τάλαντον": "money bag",
    "πεντακόσιοι": "input numbers",
    "ἀριστερός": "leftwards hand",
    "σαλπίζω": "postal horn",
    "κατασκηνόω": "tent",
    "σκληρός": "nut and bolt",
    "ὀχυρός": "castle",
    "ἐνιαύσιος": "tear-off calendar",
    "ἁγίασμα": "sparkles",
    "κάρπωμα": "basket",
    "παράταξις": "assembly point",
    "περισπόριον": "national park",
    "γένεσις": "nest with eggs",
    "ἐπιβαίνω": "hiking boot",
    "σάκκος": "reusable bag",
    "ἐναντίος": "up-down arrow",
    "ὕβρις": "smirking face",
    "ἄρσην": "male sign",
    "θυμόω": "enraged face",
    "εὖ": "thumbs up",
    "σπεύδω": "person running",
    "αὔριον": "calendar",
    "περιαιρέω": "minus",
    "χίμαρος": "goat",
    "βοηθός": "handshake",
    "ὕπνος": "zzz",
    "κατακληρονομέω": "game die",
    "φρόνησις": "face with monocle",
    "κραταιόω": "flexed biceps",
    "πέμπτος": "keycap: 5",
    "ἀνατέλλω": "sunrise over mountains",
    "οἰκέτης": "construction worker",
    "τετρακόσιοι": "input numbers",
    "ἐμαυτοῦ": "person raising hand",
    "ὅρκος": "raised hand",
    "ἔνδοξος": "glowing star",
    "γλυπτός": "moai",
    "ψάλλω": "musical score",
    "ματαιότης": "hole",
    "δόλος": "disguised face",
    "ποιμαίνω": "dog",
    "ἀφανισμός": "dashing away",
    "θεμέλιος": "brick",
    "ἱερός": "sparkles",
    "σκιά": "bust in silhouette",
    "εὐδοκέω": "smiling face",
    "σταθμός": "station",
    "πλύνω": "wash hands",
    "ἑτοίμος": "ok hand",
    "ὀρφανός": "face holding back tears",
    "παραβαίνω": "no entry",
    "ἕκτος": "keycap: 6",
    "ἐκτρίβω": "wilted flower",
    "κατέχω": "clamp",
    "ἀθῷος": "dove",
    "συνετός": "brain",
    "φονεύω": "skull and crossbones",
    "ὅσπερ": "bullseye",
    "νηστεία": "person in lotus position",
    "τοι": "index pointing up",
    "ιν": "bullseye",
    "νηστεύω": "person in lotus position",
    "μέλας": "black circle",
    "βυθός": "water wave",
    "ἄλλως": "shuffle tracks button",
    "δοκιμάζω": "test tube",
    "δεινός": "fearful face",
    "εἶδος": "puzzle piece",
    "σελήνη": "full moon",
    "ἔννοια": "thought balloon",
    "μονογενής": "keycap: 1",
    "κράτος": "raised fist",
    "ἐάω": "open hands",
    "θῆλυς": "female sign",
    "σφραγίς": "locked with pen",
    "δικαίως": "balance scale",
    "δεσμός": "chains",
    "ἀσώματος": "wind face",
    "διαμένω": "infinity",
    "τρέφω": "baby bottle",
    "λαμπρός": "glowing star",
    "ἱλαρός": "smiling face with smiling eyes",
    "ἐνέργεια": "high voltage",
    "φιλοσοφέω": "thinking face",
    "ἄλογος": "confused face",
    "ἴσως": "thinking face",
    "εἰκότως": "check mark",
    "σεμνός": "top hat",
    "εὐσέβεια": "folded hands",
    "λειτουργία": "place of worship",
    "ἀντέχω": "raised fist",
    "λανθάνω": "see-no-evil monkey",
    "συνίστημι": "puzzle piece",
    "ἐπαινέω": "clapping hands",
    "βασανίζω": "face with head-bandage",
    "ἀπιστέω": "face with raised eyebrow",
    "ὁρατός": "eyes",
    "γράμμα": "input latin letters",
    "ἀκριβῶς": "straight ruler",
    "ἁπλότης": "white heart",
    "φωτίζω": "flashlight",
    "φαντασία": "crystal ball",
    "λυπέω": "pensive face",
    "καίπερ": "up-down arrow",
    "ἀναβλέπω": "eyes",
    "δίψυχος": "face with diagonal mouth",
    "μιμητής": "footprints",
    "ἐλάσσων": "chart decreasing",
    "ἁγνεία": "white flower",
    "ἀθανασία": "infinity",
    "ἐγκράτεια": "person in lotus position",
    "εὔχρηστος": "toolbox",
    "ἀνάξιος": "thumbs down",
    "ταχύς": "high-speed train",
    "κολλάω": "paperclip",
    "ἄνω": "up arrow",
    "ἐπίγειος": "globe showing Europe-Africa",
    "παλαιός": "hourglass done",
    "μελετάω": "thinking face",
    "προέρχομαι": "right arrow",
    "καταξιόω": "sports medal",
    "σχῆμα": "triangular ruler",
    "τρόπαιον": "trophy",
    "ἀπελαύνω": "no entry",
    "κοσμέω": "ribbon",
    "ὑπόκρισις": "performing arts",
    "ταχύ": "high-speed train",
    "ἀσύνετος": "confused face",
    "ἥττον": "chart decreasing",
    "τάξις": "sort",
    "σεμνότης": "top hat",
    "λογισμός": "abacus",
    "σπουδάζω": "person running",
    "παραφυάς": "herb",
    "ὄφις": "snake",
    "πλάνη": "cyclone",
    "φυτεύω": "seedling",
    "ἰδέα": "puzzle piece",
    "πτελέα": "deciduous tree",
    "θαῦμα": "star-struck",
    "βιόω": "person walking",
    "μακαρίζω": "smiling face with halo",
    "ἁγνός": "white flower",
    "ἡδέως": "smiling face with smiling eyes",
    "πολιτεία": "classical building",
    "ἔριον": "yarn",
    "ἀλαζονεία": "smirking face",
    "κίνδυνος": "warning",
    "δίχα": "divide",
    "διαλύω": "broken chain",
    "μορφή": "puzzle piece",
    "ἐλάχιστος": "pinching hand",
    "μαγεία": "magic wand",
    "ὁμοῦ": "handshake",
    "ἄθεος": "prohibited",
    "ἔξωθεν": "outbox tray",
    "κωλύω": "stop sign",
    "τέχνη": "hammer and wrench",
    "ἱματισμός": "woman’s clothes",
    "φοβερός": "fearful face",
    "φορά": "clockwise vertical arrows",
    "ἔθος": "repeat button",
    "ἔνθα": "round pushpin",
    "φιλανθρωπία": "heart hands",
    "κατέρχομαι": "down arrow",
    "γνώρισμα": "label",
    "βέβαιος": "anchor",
    "ἐπιτρέπω": "unlocked",
    "γενναῖος": "military medal",
    "δεῦτε": "backhand index pointing down",
    "ἀφροσύνη": "clown face",
    "εἰρηνεύω": "dove",
    "μάστιξ": "boxing glove",
    "καταλαλιά": "speaking head",
    "μοιχεία": "broken heart",
    "χλευάζω": "face with tongue",
    "μεταξύ": "left-right arrow",
    "θρησκεία": "place of worship",
    "ἅπαξ": "keycap: 1",
    "σωφροσύνη": "person in lotus position",
    "κρείσσων": "chart increasing",
    "ὑπερβάλλω": "top arrow",
    "ἄγνοια": "face without mouth",
    "παρατίθημι": "fork and knife with plate",
    "συμβαίνω": "collision",
    "μιμέομαι": "footprints",
    "ἀμελέω": "see-no-evil monkey",
    "ψευδοπροφήτης": "lying face",
    "ἄκανθα": "cactus",
    "φορέω": "t-shirt",
    "ὕστερον": "soon arrow",
    "νίκη": "trophy",
    "μεγαλοπρεπής": "castle",
    "ὀρθῶς": "straight ruler",
    "ὁσίως": "folded hands",
    "τελείως": "hundred points",
    "προσαγορεύω": "name badge",
    "ἀκακία": "white heart",
    "μεγαλωσύνη": "castle",
    "σύμπας": "bar chart",
    "δωρεά": "wrapped gift",
    "ἀνήκω": "puzzle piece",
    "αἰσχρός": "face with hand over mouth",
    "παραδέχομαι": "open hands",
    "ἄγριος": "lion",
    "διαφυλάσσω": "shield",
    "ἀδίκως": "cross mark",
    "στεφανόω": "crown",
    "στάδιον": "stadium",
    "ἀρέσκω": "smiling face",
    "μέγεθος": "straight ruler",
    "σαρκικός": "cut of meat",
    "ἀκόλουθος": "footprints",
    "συγχωρέω": "open hands",
    "εὔλογος": "check mark",
    "ἐλεύθερος": "broken chain",
    "κοινωνός": "handshake",
    "οἰκεῖος": "house with garden",
    "πραγματεία": "briefcase",
    "στρογγύλος": "white circle",
    "μίγνυμι": "cooking",
    "ὑγιής": "person lifting weights",
    "κατοικία": "house",
    "περισσός": "chart increasing",
    "ὄντως": "check mark",
    "μεταβάλλω": "counterclockwise arrows button",
    "ὀνομάζω": "name badge",
    "αὐτόματος": "gear",
    "φυσικός": "seedling",
    "οὐσία": "atom symbol",
    "μεγάλως": "hundred points",
    "ἐπιμελῶς": "magnifying glass tilted left",
    "ἄπειμι": "empty nest",
    "κόκκινος": "red circle",
    "ἐπιείκεια": "dove",
    "πραΰς": "dove",
    "κατηγορέω": "backhand index pointing right",
    "εὐεργεσία": "heart hands",
    "περιέχω": "circled anticlockwise arrow",
    "διάφορος": "puzzle piece",
    "ἀναγκαῖος": "exclamation question mark",
    "χάρισμα": "wrapped gift",
    "ἐπινοέω": "light bulb",
    "βάθος": "hole",
    "ἐπιφέρω": "palm down hand",
    "πλήρωμα": "full moon",
    "ἐπιμένω": "anchor",
    "σιωπάω": "shushing face",
    "ῥώννυμι": "flexed biceps",
    "σωματικός": "person standing",
    "βρῶσις": "fork and knife with plate",
    "πονηρεύομαι": "smiling face with horns",
    "σχεδόν": "pinching hand",
    "ἀποφέρω": "package",
    "πολλάκις": "repeat button",
    "τετράγωνος": "white large square",
    "σύγγραμμα": "scroll",
    "βάρβαρος": "world map",
    "ἀθεότης": "prohibited",
    "μηνύω": "megaphone",
    "μάγος": "mage",
    "συγγραφεύς": "writing hand",
    "περιλαμβάνω": "open hands",
    "σώφρων": "person in lotus position",
    "πολιτεύω": "classical building",
    "ὑποφέρω": "person climbing",
    "δρόμος": "person running",
    "μετρέω": "straight ruler",
    "ἡσύχιος": "shushing face",
    "ἄκακος": "white heart",
    "εἰρηνικός": "dove",
    "βελτίων": "chart increasing",
    "κτίστης": "artist palette",
    "χορός": "man dancing",
    "ταπεινοφροσύνη": "person bowing",
    "ἀφορμή": "door",
    "χαρακτήρ": "fingerprint",
    "ἀργός": "sleeping face",
    "ἀπειθέω": "person gesturing no",
    "πρόκειμαι": "backhand index pointing down",
    "λύκος": "wolf",
    "λῃστής": "detective",
    "ἄτρεπτος": "anchor",
    "οὔπω": "hourglass not done",
    "προλαμβάνω": "fast-forward button",
    "συμφωνέω": "handshake",
    "χρῶμα": "artist palette",
    "οἰκονομία": "ledger",
    "ἡλικία": "straight ruler",
    "ἀντιλέγω": "person gesturing no",
    "ἀπαιτέω": "palm up hand",
    "πότερος": "red question mark",
    "κεράμιον": "amphora",
    "δεκτός": "ok hand",
    "σύμβουλος": "people dialogue",
    "ἀναχωρέω": "back arrow",
    "ἀδίστακτος": "anchor",
    "αἴτημα": "folded hands",
    "ἀμέλεια": "see-no-evil monkey",
    "δαπανάω": "money with wings",
    "τρυφάω": "tropical drink",
    "μνήμη": "reminder ribbon",
    "διαφέρω": "puzzle piece",
    "χείρων": "chart decreasing",
    "κωφός": "deaf person",
    "φιλάνθρωπος": "heart hands",
    "παράδεισος": "house with garden",
    "μανία": "face with spiral eyes",
    "χωλός": "crutches",
    "προβάλλω": "backhand index pointing right",
    "οὐδαμοῦ": "hole",
    "κοινωνία": "people hugging",
    "καλάμη": "sheaf of rice",
    "πανταχόθεν": "compass",
    "εἴπερ": "shuffle tracks button",
    "τάχα": "thinking face",
    "τριάς": "keycap: 3",
    "μεστός": "full moon",
    "πεποίθησις": "anchor",
    "ἀγών": "boxing glove",
    "φθόνος": "face with rolling eyes",
    "ἄτιμος": "thumbs down",
    "ἱνατί": "red question mark",
    "ἐπίκειμαι": "palm down hand",
    "λούω": "shower",
    "λευκαίνω": "white circle",
    "προσπίπτω": "person kneeling",
    "μετατίθημι": "move",
    "ταπείνωσις": "person bowing",
    "ἄβυσσος": "hole",
    "συνόχωκα": "clamp",
    "ἀπόλαυσις": "face savoring food",
    "ἀξίως": "sports medal",
    "ἴσος": "heavy equals sign",
    "φύλλον": "maple leaf",
    "ἐξαίφνης": "high voltage",
    "τολμάω": "lion",
    "αὐξάνω": "chart increasing",
    "παρίημι": "open hands",
    "πλεονεξία": "money-mouth face",
    "σιγάω": "shushing face",
    "ὑπολαμβάνω": "thought balloon",
    "κολλάομαι": "paperclip",
    "ἐξηγέομαι": "left speech bubble",
    "ἐνίστημι": "airplane arrival",
    "ἀμείνων": "chart increasing",
    "ἀπειλή": "warning",
    "πεινάω": "drooling face",
    "ἀμίαντος": "white flower",
    "στέφανος": "crown",
    "καταρτίζω": "toolbox",
    "ἀπαθής": "face without mouth",
    "ἐξαπατάω": "disguised face",
    "ἀπάγω": "left arrow",
    "πρᾳότης": "dove",
    "κλάδος": "herb",
    "οὐδέποτε": "prohibited",
    "ἀκίνητος": "anchor",
    "καταγγέλλω": "megaphone",
    "πρεσβεία": "envelope with arrow",
    "δίκη": "balance scale",
    "πορνεία": "broken heart",
    "εἰδωλολατρία": "moai",
    "μακρόθυμος": "hourglass not done",
    "πικρία": "lemon",
    "μνησικακέω": "unamused face",
    "γλυκύς": "honey pot",
    "κήρυγμα": "megaphone",
    "μηδέποτε": "prohibited",
    "ἀναγράφω": "writing hand",
    "θρίξ": "curly hair",
    "παραφέρω": "package",
    "στοιχεῖον": "atom symbol",
    "ῥᾴδιος": "thumbs up",
    "χαμαί": "down arrow",
    "δυσκόλως": "person climbing",
    "τραχύς": "rock",
    "κάμνω": "tired face",
    "τρίβολος": "cactus",
    "ἀνθύπατος": "man judge",
    "φύλαξ": "guard",
    "ἀπόκειμαι": "locked",
    "φάσκω": "speech balloon",
    "σύμβολον": "scroll",
    "πῶλος": "horse",
    "μείρομαι": "pie",
    "λουτρόν": "bathtub",
    "πρόφασις": "disguised face",
    "ἐπιβουλή": "detective",
    "νοσέω": "face with thermometer",
    "φυσάω": "wind face",
    "φιλοξενία": "hotel",
    "ἀσφαλής": "locked",
    "προθυμία": "fire",
    "κατεργάζομαι": "hammer and wrench",
    "ἀρχαῖος": "hourglass done",
    "ὑπόδειγμα": "footprints",
    "κῆρυξ": "megaphone",
    "νουθετέω": "index pointing up",
    "χιών": "snowflake",
    "διοἰκέω": "gear",
    "διατάσσω": "clipboard",
    "εὐεργετέω": "heart hands",
    "ἀνόητος": "clown face",
    "προηγέομαι": "1st place medal",
    "πραΰτης": "dove",
    "γυμνός": "footprints",
    "μεγαλειότης": "castle",
    "ὑπερήφανος": "smirking face",
    "αὐθάδεια": "raised fist",
    "φλόξ": "fire",
    "βιβρώσκω": "worm",
    "ἐξαίρετος": "1st place medal",
    "ἀμέμπτως": "white flower",
    "εὐάρεστος": "smiling face",
    "πατρίς": "house with garden",
    "γόνυ": "leg",
    "σπλαγχνίζομαι": "heart hands",
    "ῥήγνυμι": "collision",
    "ἀσύμφορος": "thumbs down",
    "βάπτισμα": "droplet",
    "πυκνός": "repeat button",
    "συντόμως": "pinching hand",
    "ἀσκέω": "person lifting weights",
    "σύνδουλος": "men holding hands",
    "ὀνίνημι": "handshake",
    "πρεσβυτέριον": "people dialogue",
    "ὑστερέω": "empty nest",
    "αἵρεσις": "shuffle tracks button",
    "ἰατρός": "health worker",
    "ἀδιαλείπτως": "infinity",
    "ἥμερος": "dove",
    "ἀντίψυχος": "counterclockwise arrows button",
    "μερισμός": "divide",
    "φανερῶς": "flashlight",
    "καρποφορέω": "red apple",
    "χαλεπός": "person climbing",
    "βῆμα": "judge",
    "ὑποκριτής": "performing arts",
    "φόνος": "skull and crossbones",
    "πλάσμα": "artist palette",
    "ἁγνῶς": "white flower",
    "αἰσθάνομαι": "nose",
    "βίαιος": "collision",
    "ἐκπετάννυμι": "open hands",
    "ὄγδοος": "keycap: 8",
    "ποθέω": "growing heart",
    "κατορθόω": "check mark button",
    "ἐνδεής": "empty nest",
    "κολοβόω": "scissors",
    "ἄχρηστος": "wastebasket",
    "κτίσμα": "seedling",
    "ἔνοχος": "balance scale",
    "πολυτέλεια": "gem stone",
    "εὐπρεπής": "top hat",
    "δεῖπνον": "fork and knife with plate",
    "μάτην": "hole",
    "σκιρτάω": "man dancing",
    "παντελῶς": "hundred points",
    "ἰτέα": "deciduous tree",
    "πλεῖστος": "bar chart",
    "φάσις": "speech balloon",
    "προθύμως": "fire",
    "τύραννος": "crown",
    "σπουδή": "person running",
    "δεισιδαιμονία": "crystal ball",
    "παραιτέομαι": "person gesturing no",
    "ὑφίστημι": "person climbing",
    "βραχύς": "pinching hand",
    "τέμνω": "kitchen knife",
    "γείτων": "houses",
    "γενετή": "nest with eggs",
    "ὁρμάω": "person running",
    "γνώριμος": "name badge",
    "ὑπόκειμαι": "down arrow",
    "αὐτάρκης": "ok hand",
    "πάντῃ": "compass",
    "βραδύς": "snail",
    "αὐθάδης": "raised fist",
    "ὑπάρχοντα": "money bag",
    "ἐπιεικής": "dove",
    "ἱκετεύω": "folded hands",
    "ἀκαταστασία": "cyclone",
    "ἔντιμος": "gem stone",
    "δουλεία": "chains",
    "λειτουργός": "raising hands",
    "βούλημα": "thought balloon",
    "ὑπακοή": "ok hand",
    "ψεύδω": "lying face",
    "πιστόω": "check mark button",
    "τραυματίζω": "adhesive bandage",
    "σκώληξ": "worm",
    "ῥύπος": "splatter",
    "βάτος": "cactus",
    "ἀγαλλίασις": "party popper",
    "ταλαίπωρος": "weary face",
    "ἄνθος": "hibiscus",
    "μεγαλεῖος": "castle",
    "ὁσιότης": "folded hands",
    "ὁμοίωσις": "heavy equals sign",
    "ἐργάτης": "farmer",
    "πανάγιος": "sparkles",
    "ὑποπόδιον": "seat",
    "σής": "worm",
    "ἵλεως": "smiling face with smiling eyes",
    "σφραγίζω": "locked with pen",
    "φιλαδελφία": "two hearts",
    "ἐξεῖπον": "speech balloon",
    "τάχος": "high-speed train",
    "κινδυνεύω": "warning",
    "νήπιος": "baby",
    "στείρος": "leafless tree",
    "φιλαργυρία": "money-mouth face",
    "κομίζω": "package",
    "ἔσω": "inbox tray",
    "μῦθος": "books",
    "ἐλεημοσύνη": "coin",
    "πλουτέω": "money bag",
    "ἀδιάκριτος": "heavy equals sign",
    "συνήθεια": "repeat button",
    "εὐταξία": "sort",
    "συγχαίρω": "partying face",
    "πότος": "clinking beer mugs",
    "σύνδεσμος": "link",
    "ἑκών": "victory hand",
    "συνέχω": "clamp",
    "τύπτω": "oncoming fist",
    "σπουδαῖος": "fire",
    "χιτών": "kimono",
    "μοιχεύω": "broken heart",
    "ἐκπλήσσω": "astonished face",
    "ἐμβλέπω": "eyes",
    "πολυτελής": "gem stone",
    "γάλα": "glass of milk",
    "ζῳοποιέω": "anatomical heart",
    "ἐπικατάρατος": "face with symbols on mouth",
    "περιτίθημι": "knot",
    "χοῖρος": "pig",
    "μέλω": "heart hands",
    "ὀρύσσω": "shovel",
    "ἐνδόξως": "glowing star",
    "ἐκκόπτω": "axe",
    "ἐπισπάομαι": "magnet",
    "θεμελιόω": "brick",
    "προδίδωμι": "dagger",
    "προδότης": "dagger",
    "ὅραμα": "eye in speech bubble",
    "περιζώννυμι": "ribbon",
    "βλαβερός": "biohazard",
    "ἰός": "microbe",
    "μέριμνα": "worried face",
    "ἰσχυρῶς": "flexed biceps",
    "φιλία": "revolving hearts",
    "κρεμάννυμι": "hook",
    "εὐθαλής": "potted plant",
    "ἀπορέω": "confused face",
    "ποικιλία": "rainbow",
    "δειλία": "fearful face",
    "ἔοικα": "wavy dash",
    "φιλοσοφία": "thinking face",
    "πατρικός": "man",
    "ὕμνος": "musical notes",
    "διαφορά": "divide",
    "ἤπερ": "up-right arrow",
    "θεῖον": "volcano",
    "φθέγγομαι": "speaker high volume",
    "γελοῖος": "face with tears of joy",
    "ἀπολογία": "memo",
    "ὑγρός": "sweat droplets",
    "θειότης": "palms up together",
    "ἀκολουθία": "sort",
    "λογικός": "abacus",
    "πατριάρχης": "older person",
    "κίνησις": "locomotion",
    "ἱλάσκομαι": "folded hands",
    "συμφορά": "landslide",
    "μιαρός": "splatter",
    "ἦθος": "fingerprint",
    "καθήκω": "check mark",
    "κανών": "straight ruler",
    "σεμνῶς": "top hat",
    "ἀδελφότης": "men holding hands",
    "ἀκέραιος": "white heart",
    "ἡσυχάζω": "shushing face",
    "ἀναγκάζω": "exclamation question mark",
    "ἀθλητής": "man running",
    "ἀπαλλαξείω": "broken chain",
    "ὑπομιμνῄσκω": "thought balloon",
    "φροντίς": "heart hands",
    "διελέγχω": "right anger bubble",
    "ἐξαριθμέω": "input numbers",
    "ὑπήκοος": "ok hand",
    "βλάβη": "biohazard",
    "μαλακίζω": "sponge",
    "μώλωψ": "adhesive bandage",
    "κείρω": "scissors",
    "ἄφωνος": "muted speaker",
    "σποδός": "volcano ashes",
    "ἄμεμπτος": "white flower",
    "κρύφιος": "closed book",
    "ἄπειρος": "hatching chick",
    "ἐρευνάω": "magnifying glass tilted right",
    "ταμεῖον": "file cabinet",
    "συμβάλλω": "collaboration",
    "σταφυλή": "grapes",
    "προγίνομαι": "back arrow",
    "ψεύδομαι": "lying face",
    "στερέωμα": "milky way",
    "ἁγιασμός": "sparkles",
    "λαμπρότης": "glowing star",
    "κενοδοξία": "smirking face",
    "μοιχός": "broken heart",
    "σκάνδαλον": "mouse trap",
    "γεύομαι": "tongue",
    "αὔρα": "wind face",
    "δίαιτα": "bowl with spoon",
    "ἐμπίπτω": "down-right arrow",
    "ἱερωσύνη": "raising hands",
    "ἐγγράφω": "writing hand",
    "διαστρέφω": "curly loop",
    "ἀποκαθίστημι": "recycling symbol",
    "ἐξήγησις": "left speech bubble",
    "καταγινώσκω": "backhand index pointing right",
    "ἐντεῦθεν": "round pushpin",
    "θόρυβος": "anger symbol",
    "σύστασις": "puzzle piece",
    "ἐνάρετος": "military medal",
    "σαφῶς": "flashlight",
    "τάχιον": "high-speed train",
    "ἀντιμισθία": "receipt",
    "περίκειμαι": "circled anticlockwise arrow",
    "ὠδίνω": "pregnant woman",
    "παρακούω": "hear-no-evil monkey",
    "σβέννυμι": "fire extinguisher",
    "ἀπαλλάσσω": "broken chain",
    "βλάπτω": "biohazard",
    "παράμονος": "infinity",
    "κιθάρα": "harp",
    "ἐντός": "inbox tray",
    "διακρίνω": "filter",
    "ἔθω": "repeat button",
    "περιφέρω": "backpack",
    "περίψημα": "wastebasket",
    "ἀποστερέω": "minus",
    "κρυπτός": "closed book",
    "καινότης": "sparkler",
    "φάρμακον": "pill",
    "προκρίνω": "1st place medal",
    "συνέδριον": "people dialogue",
    "διάγω": "person walking",
    "συγκόπτω": "axe",
    "προάγω": "man walking",
    "ἀξιόπιστος": "check mark button",
    "ἑνότης": "link",
    "χειροτονέω": "raising hands",
    "ἀμοιβή": "receipt",
    "φροντίζω": "heart hands",
    "πλέω": "sailboat",
    "ἐπίτροπος": "ledger",
    "ψευδομαρτυρία": "lying face",
    "ὁπλίζομαι": "shield",
    "σιαγών": "tooth",
    "ἀρεστός": "smiling face",
    "νουμηνία": "crescent moon",
    "λίθινος": "rock",
    "δάκτυλος": "backhand index pointing up",
    "ὄξος": "glass bottle",
    "διέξοδος": "exit",
    "ἀκροατής": "ear with hearing aid",
    "βιβλάριον": "notebook",
    "ἀσέλγεια": "tropical drink",
}


def first_sense(gloss: str) -> str:
    return gloss.split("；")[0].strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="替希臘文單字卡挑圖，挑不到就留空")
    parser.add_argument(
        "--uncovered",
        type=int,
        default=0,
        help="列出前 N 張沒有配圖的卡（依冊次課次），供人工挑圖",
    )
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    ensure_openmoji()
    entries = json.loads(VOCAB.read_text(encoding="utf-8"))["entries"]
    glosses = {
        lemma: record["glossZh"]
        for lemma, record in json.loads(GLOSSES.read_text(encoding="utf-8"))["glosses"].items()
    }
    by_name = load_openmoji()

    hebrew = json.loads(HEBREW_IMAGES.read_text(encoding="utf-8"))["images"]
    # Chinese meaning -> picture, taken from the Hebrew deck's curated choices.
    by_meaning: dict[str, str] = {}
    for record in hebrew.values():
        for key in (record["glossZh"].strip(), first_sense(record["glossZh"])):
            by_meaning.setdefault(key, record["hexcode"])

    assigned: dict[str, dict] = {}
    unresolved: list[str] = []
    sources = {"override": 0, "zh_transfer": 0, "annotation": 0, "none": 0}

    for entry in entries:
        lemma = entry["lemma"]
        gloss = glosses.get(lemma, "")
        chosen = None
        source = "none"

        wanted = OVERRIDES.get(lemma)
        if wanted:
            found = by_name.get(wanted.lower())
            if found and image_path(found["hexcode"]):
                chosen, source = found["hexcode"], "override"
            else:
                unresolved.append(f"{lemma} -> {wanted!r}")

        if not chosen and gloss:
            for key in (gloss.strip(), first_sense(gloss)):
                hexcode = by_meaning.get(key)
                if hexcode and image_path(hexcode):
                    chosen, source = hexcode, "zh_transfer"
                    break

        if not chosen:
            for candidate in english_candidates(entry.get("glossEn") or ""):
                if candidate in AMBIGUOUS_EN:
                    continue
                found = by_name.get(candidate)
                if found and image_path(found["hexcode"]):
                    chosen, source = found["hexcode"], "annotation"
                    break

        sources[source] += 1
        if chosen:
            assigned[lemma] = {
                "hexcode": chosen,
                "file": image_path(chosen).name,
                "source": source,
                "glossZh": gloss,
                "volume": entry["volume"],
            }

    # Second transfer pass, now including the Greek cards just settled.  Volume 2
    # is patristic vocabulary and shares far more of its Chinese with volume 1
    # than with the Hebrew deck, so this is where most of its pictures come from.
    for record in list(assigned.values()):
        for key in (record["glossZh"].strip(), first_sense(record["glossZh"])):
            if key:
                by_meaning.setdefault(key, record["hexcode"])
    for entry in entries:
        lemma = entry["lemma"]
        if lemma in assigned:
            continue
        gloss = glosses.get(lemma, "")
        if not gloss:
            continue
        for key in (gloss.strip(), first_sense(gloss)):
            hexcode = by_meaning.get(key)
            if hexcode and image_path(hexcode):
                assigned[lemma] = {
                    "hexcode": hexcode,
                    "file": image_path(hexcode).name,
                    "source": "zh_transfer",
                    "glossZh": gloss,
                    "volume": entry["volume"],
                }
                sources["zh_transfer"] += 1
                sources["none"] -= 1
                break

    total = len(entries)
    print(f"  人工指定 {sources['override']}，中文詞義轉移 {sources['zh_transfer']}，"
          f"本名比對 {sources['annotation']}，留空 {sources['none']}")
    print(f"  有圖合計 {len(assigned)} / {total} = {len(assigned) * 100 // total}%")
    for volume in (1, 2):
        in_volume = [entry for entry in entries if entry["volume"] == volume]
        covered = sum(1 for entry in in_volume if entry["lemma"] in assigned)
        print(f"      第{volume}冊 {covered}/{len(in_volume)}")
    if args.uncovered:
        blanks = [
            entry for entry in entries if entry["lemma"] not in assigned
        ]
        blanks.sort(key=lambda item: (item["volume"], item["lesson"], item["lessonSlot"]))
        print()
        print(f"  未配圖 {len(blanks)} 張，依冊次課次排列：")
        for entry in blanks[: args.uncovered]:
            gloss = glosses.get(entry["lemma"], "")
            print(f"    v{entry['volume']} L{entry['lesson']:>2} {entry['lemma']}	{gloss}")

    if unresolved:
        print(f"  ⚠ 人工指定但查無此圖：{len(unresolved)}")
        for item in sorted(set(unresolved))[:20]:
            print(f"      {item}")

    if args.write:
        OUTPUT.write_text(
            json.dumps(
                {
                    "schemaVersion": "1.0.0",
                    "source": "OpenMoji 17.0.0",
                    "licence": "CC BY-SA 4.0 — https://openmoji.org",
                    "note": "每張卡最多一張圖，取該詞最常見的義項；挑不到就留空。"
                            "zh_transfer 表示沿用中文詞義相同的希伯來卡用圖。",
                    "images": assigned,
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        print(f"\n已寫出 {OUTPUT}")
    else:
        print("\n（未寫檔；加 --write 才會輸出）")


if __name__ == "__main__":
    main()
