"""
Scrape Vatican I (1869-70) dogmatic constitutions to markdown txt files:

  - Dei Filius (DF, 1870-04-24) — Constitutio dogmatica de fide catholica
  - Pastor Aeternus (PA, 1870-07-18) — Constitutio dogmatica prima de ecclesia Christi

Sources:
  - Latin:   vatican.va archive (separate page per document)
  - English: papalencyclicals.net/councils/ecum20.htm (combined page, split by session)

Output:
  data/creeds/ecumenical-councils/vatican-i/{df,pa}-{latin,english}.txt

Chinese (df-chinese.txt / pa-chinese.txt) NOT generated by this script —
vatican.va has no Chinese for Vatican I; must be sourced manually from
《梵蒂岡第一屆大公會議文獻》(主教團 / 思高).

Run from project root:
  python -X utf8 scripts/rebuild_vatican_i_html.py
"""
import os
import re
from bs4 import BeautifulSoup, NavigableString, Tag
import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TXT_DIR = os.path.join(ROOT, "data", "creeds", "ecumenical-councils", "vatican-i")

VATICAN_VA_LATIN = {
    "df": "https://www.vatican.va/archive/hist_councils/i-vatican-council/documents/vat-i_const_18700424_dei-filius_la.html",
    "pa": "https://www.vatican.va/archive/hist_councils/i-vatican-council/documents/vat-i_const_18700718_pastor-aeternus_la.html",
}

PAPAL_ENCYCLICALS_EN = "https://www.papalencyclicals.net/councils/ecum20.htm"


def fetch_html(url: str) -> str:
    r = requests.get(
        url,
        timeout=60,
        headers={"User-Agent": "Mozilla/5.0 know-graph-lab/1.0 (creeds/vatican-i)"},
    )
    r.raise_for_status()
    r.encoding = r.apparent_encoding or "utf-8"
    return r.text


# ─────────────────────────────────────────────────────────────
# Latin parser (vatican.va)
# ─────────────────────────────────────────────────────────────

def parse_vatican_va_latin(html: str) -> str:
    """
    vatican.va Vatican I Latin structure:
      - <strong> wraps chapter titles, canon section titles
      - <p> wraps paragraphs (some begin numerically '1.', '2.', etc.)
      - 'Caput I.' / 'Canones' style headings often inside <strong>
    Strategy: walk body, treat <strong>-only-content <p> as heading,
    otherwise emit as paragraph.
    """
    soup = BeautifulSoup(html, "html.parser")

    body = soup.find("body") or soup
    # remove header / nav / footer noise
    for tag in body.find_all(["script", "style"]):
        tag.decompose()

    lines: list[str] = []
    seen_first_strong = False  # skip Vatican logo + header noise before content

    for p in body.find_all(["p", "h1", "h2", "h3", "h4"]):
        text = p.get_text(" ", strip=True)
        if not text:
            continue
        # Filter common navigational / boilerplate text
        if text.lower().startswith(("english", "français", "italiano", "espa")):
            continue
        if "vatican.va" in text.lower() and len(text) < 80:
            continue

        # Detect heading: <p> whose text is wholly inside <strong> / <b>
        is_heading = False
        strong_tags = p.find_all(["strong", "b"])
        if strong_tags:
            stripped_text_no_emph = "".join(
                "" if isinstance(c, Tag) and c.name in ("strong", "b") else (c.string or "" if isinstance(c, NavigableString) else "")
                for c in p.children
            ).strip()
            inside_emph_text = " ".join(s.get_text(" ", strip=True) for s in strong_tags).strip()
            if inside_emph_text and inside_emph_text.replace(" ", "") == text.replace(" ", ""):
                is_heading = True

        if is_heading:
            seen_first_strong = True
            # Normalize whitespace, drop trailing punctuation noise
            heading = re.sub(r"\s+", " ", text).strip()
            lines.append("")
            lines.append(f"## {heading}")
            lines.append("")
            continue

        if not seen_first_strong:
            # Pre-content header junk; skip until we hit the first strong heading
            # but keep the doc opening 'PIUS EPISCOPUS' / preamble lines if no headings yet
            # — vatican.va Vat I usually starts content right away
            pass

        # Collapse whitespace and emit
        para = re.sub(r"\s+", " ", text).strip()
        lines.append(para)
        lines.append("")

    # Trim leading blanks
    while lines and not lines[0].strip():
        lines.pop(0)
    return "\n".join(lines).rstrip() + "\n"


# ─────────────────────────────────────────────────────────────
# English parser (papalencyclicals.net)
# ─────────────────────────────────────────────────────────────

# Section anchors / markers within the combined page
SESSION_MARKER_RE = re.compile(r"^\s*SESSION\s+([1-4])\b", re.IGNORECASE)


def _normalize_for_subset(s: str) -> str:
    """Lowercase + collapse whitespace + strip punctuation for fuzzy substring check."""
    s = re.sub(r"[^\w\s]", " ", s.lower())
    return re.sub(r"\s+", " ", s).strip()


def parse_papalencyclicals_combined(html: str) -> dict[str, str]:
    """
    papalencyclicals.net/ecum20.htm holds all 4 Vatican I sessions in one page.
    We want:
      Session 3 → Dei Filius
      Session 4 → Pastor Aeternus
    Split on 'SESSION N' h-tag boundaries.

    The page reformats long canons into bulleted sub-phrases that duplicate
    parts of the preceding paragraph. We skip:
      - <li> elements (always redundant)
      - any <p> whose normalized text is a substring of the prior paragraph
      - "Return to Table of Contents" navigation links
      - footer sections (after "Want to be automatically notified")
    """
    soup = BeautifulSoup(html, "html.parser")
    body = soup.find("body") or soup
    for tag in body.find_all(["script", "style"]):
        tag.decompose()

    # Collect all relevant block-level elements in order.
    # papalencyclicals.net wraps each canon in <li>, with <p>/<li> sub-fragments after
    # that repeat parts of the canon for visual emphasis — dedup via substring check.
    blocks: list[tuple[str, str]] = []  # (kind, text); kind ∈ {heading, para}
    prev_para_norm = ""

    for el in body.find_all(["h1", "h2", "h3", "h4", "p", "li"]):
        text = el.get_text(" ", strip=True)
        if not text:
            continue
        text = re.sub(r"\s+", " ", text).strip()

        # Skip footer / navigation noise
        if text.lower().startswith("return to table of contents"):
            continue
        if "papalencyclicals" in text.lower() and len(text) < 80:
            continue
        if text.lower().startswith(("copyright", "all rights", "last updated")):
            continue

        # Heading detection: h-tags, or all-caps short text, or starts with 'SESSION N' / 'Chapter N'
        is_heading = (
            el.name in ("h1", "h2", "h3", "h4")
            or SESSION_MARKER_RE.match(text)
            or re.match(r"^(Chapter|CHAPTER)\s+\d+", text)
            or (text.isupper() and len(text) < 100)
        )

        # Check for <strong>/<b> wrapping
        if not is_heading and el.name == "p":
            strong_tags = el.find_all(["strong", "b"])
            if strong_tags:
                inside = " ".join(s.get_text(" ", strip=True) for s in strong_tags)
                if inside and inside.replace(" ", "") == text.replace(" ", ""):
                    is_heading = True

        # Substring-of-previous check (catches bullet rephrasings)
        if not is_heading:
            norm = _normalize_for_subset(text)
            if norm and prev_para_norm and norm in prev_para_norm:
                continue
            prev_para_norm = norm
        else:
            prev_para_norm = ""

        blocks.append(("heading" if is_heading else "para", text))

    # Truncate at footer markers
    cutoff = None
    for i, (kind, text) in enumerate(blocks):
        low = text.lower()
        if "want to be automatically notified" in low or "for more information about this site" in low:
            cutoff = i
            break
    if cutoff is not None:
        blocks = blocks[:cutoff]

    # Split into sessions
    sessions: dict[int, list[tuple[str, str]]] = {}
    current = None
    for kind, text in blocks:
        m = SESSION_MARKER_RE.match(text)
        if m:
            current = int(m.group(1))
            sessions.setdefault(current, []).append((kind, text))
            continue
        if current is None:
            continue
        sessions.setdefault(current, []).append((kind, text))

    def render(session_blocks: list[tuple[str, str]]) -> str:
        lines: list[str] = []
        for kind, text in session_blocks:
            if kind == "heading":
                lines.append("")
                lines.append(f"## {text}")
                lines.append("")
            else:
                lines.append(text)
                lines.append("")
        # cleanup
        while lines and not lines[0].strip():
            lines.pop(0)
        return "\n".join(lines).rstrip() + "\n"

    out = {}
    if 3 in sessions:
        out["df"] = render(sessions[3])
    if 4 in sessions:
        out["pa"] = render(sessions[4])
    return out


# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

def main() -> None:
    os.makedirs(TXT_DIR, exist_ok=True)

    # Latin
    for code, url in VATICAN_VA_LATIN.items():
        print(f"[latin {code.upper()}] fetching {url}")
        html = fetch_html(url)
        md = parse_vatican_va_latin(html)
        out_path = os.path.join(TXT_DIR, f"{code}-latin.txt")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(md)
        print(f"  → wrote {out_path} ({len(md):,} chars)")

    # English
    print(f"[english] fetching {PAPAL_ENCYCLICALS_EN}")
    html = fetch_html(PAPAL_ENCYCLICALS_EN)
    parts = parse_papalencyclicals_combined(html)
    for code, md in parts.items():
        out_path = os.path.join(TXT_DIR, f"{code}-english.txt")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(md)
        print(f"  → wrote {out_path} ({len(md):,} chars)")

    # Chinese placeholder (only create if missing — never overwrite)
    for code in ("df", "pa"):
        zh_path = os.path.join(TXT_DIR, f"{code}-chinese.txt")
        if not os.path.exists(zh_path):
            placeholder = (
                "（中文版尚未取得。vatican.va 對 Vatican I (1869-70) 僅提供 Italian + Latin，"
                "無中文官方版。\n"
                "可能來源：\n"
                "  - 中華民國天主教主教團《梵蒂岡第一屆大公會議文獻》中譯本\n"
                "  - 思高聖經學會編《大公會議信條彙編》\n"
                "  - 香港教區出版相關文獻\n"
                "取得後請手動覆蓋本檔。）\n"
            )
            with open(zh_path, "w", encoding="utf-8") as f:
                f.write(placeholder)
            print(f"  → placeholder {zh_path}")


if __name__ == "__main__":
    main()
