#!/usr/bin/env node
/**
 * 補完 wikidata-states.json 缺少中文名的條目：
 *   1) 規則翻譯：Kingdom of X → X 王國、Duchy of X → X 公國 等
 *   2) 人工翻譯表 MANUAL_TRANSLATIONS（歷史學常用譯名）
 *
 * 寫回 public/maps/wikidata-states.json
 */

import { readFileSync, writeFileSync } from 'node:fs'

const FILE = 'public/maps/wikidata-states.json'

// ===== 人工翻譯表（依歷史學界常用譯法）=====
// 涵蓋從蘇美城邦、古典近東、希臘羅馬、印度諸邦、中亞、伊斯蘭、中世紀歐洲、
// 非洲王國、前哥倫布美洲、東南亞、東亞分裂期等。持續可擴充。
const MANUAL_TRANSLATIONS = {
  // === 古代近東：蘇美／巴比倫／亞述／敘利亞城邦 ===
  'Namri': '南姆里',
  'Abarsal': '阿巴薩爾',
  'Old Kingdom of Egypt': '埃及古王國',
  'Middle Kingdom of Egypt': '埃及中王國',
  'New Kingdom of Egypt': '埃及新王國',
  'First Intermediate Period of Egypt': '埃及第一中間期',
  'Second Intermediate Period of Egypt': '埃及第二中間期',
  'Third Intermediate Period of Egypt': '埃及第三中間期',
  'Late Period of ancient Egypt': '埃及後期王朝',
  'Early Dynastic Period (Egypt)': '埃及早王朝時期',
  'Predynastic Egypt': '埃及前王朝時期',
  'Ptolemaic Kingdom': '托勒密王國',
  'Hatti': '哈梯（赫梯本部）',
  'Hattusa': '哈圖薩',
  'Mitanni': '米坦尼',
  'Isuwa': '伊蘇瓦',
  'Mira': '米拉',
  'Tuwanuwa': '圖瓦努瓦',
  'Ahhiyawa': '阿希亞瓦',
  'Khalitu': '哈利圖',
  'Gurgum': '古爾古姆',
  'Bit Bahiani': '比特巴希亞尼',
  'Bit Adini': '比特阿迪尼',
  'Bit-Adini': '比特阿迪尼',
  'Gandhāra': '犍陀羅',
  'Gandhara': '犍陀羅',
  'Philistia': '非利士',
  'Soli': '索利',
  'Ammon': '亞捫',
  'Moab': '摩押',
  'Edom': '以東',
  'Chaldea': '迦勒底',
  'Hamath': '哈馬特',
  'Hubushkia': '胡布什基亞',
  'Lapathus': '拉帕索斯',
  'Laqe': '拉凱',
  'Zamua': '扎穆阿',
  'Zobah': '瑣巴',
  'Alzi': '阿爾齊',
  'Daiaeni': '達伊埃尼',
  'Syrakousai': '敘拉古',
  'Syracuse': '敘拉古',
  'Medo-Persia': '米底-波斯',
  'Media': '米底',
  'Lydia': '呂底亞',
  'Phrygia': '弗里吉亞',
  'Lycia': '呂基亞',
  'Pamphylia': '潘菲利亞',
  'Cilicia': '奇里乞亞',
  'Cappadocia': '卡帕多西亞',
  'Pontus': '本都',
  'Bithynia': '比提尼亞',
  'Galatia': '加拉太',
  'Pergamum': '帕加馬',
  'Pergamon': '帕加馬',
  'Commagene': '康馬基尼',
  'Armenia Minor': '小亞美尼亞',
  'Sophene': '索菲尼',
  'Osroene': '奧斯洛尼',
  'Hatra': '哈特拉',
  'Adiabene': '阿迪亞貝尼',
  'Characene': '卡拉塞尼',
  'Elymais': '埃利邁斯',
  'Persis': '帕爾斯（波斯本土）',
  'Hyrcania': '希爾卡尼亞',
  'Parthia': '帕提亞',
  'Bactria': '巴克特里亞',
  'Sogdia': '粟特',
  'Sogdiana': '粟特',
  'Margiana': '馬爾吉亞那',
  'Hyrcanian Empire': '希爾卡尼亞帝國',
  'Aramean': '亞蘭',
  'Aramaeans': '亞蘭人',
  'Phoenicia': '腓尼基',
  'Tyre': '推羅',
  'Sidon': '西頓',
  'Byblos': '比布魯斯',
  'Ugarit': '烏加里特',
  'Carthage': '迦太基',
  'Numidia': '努米底亞',
  'Mauretania': '茅利塔尼亞',
  'Cyrenaica': '昔蘭尼加',
  'Cyrene': '昔蘭尼',

  // === 古典希臘 ===
  'Sparta': '斯巴達',
  'Athens': '雅典',
  'Thebes': '底比斯',
  'Corinth': '科林斯',
  'Argos': '阿爾戈斯',
  'Megara': '麥加拉',
  'Aetolian League': '埃托利亞同盟',
  'Achaean League': '亞該亞同盟',
  'Boeotian League': '波奧提亞同盟',
  'Delphic Amphictyony': '德爾斐近鄰同盟',
  'Magna Graecia': '大希臘',
  'Epirus (ancient state)': '伊庇魯斯王國',
  'Epirus': '伊庇魯斯',
  'Illyria': '伊利里亞',
  'Dalmatia': '達爾馬提亞',
  'Pannonia': '潘諾尼亞',
  'Dacia': '達契亞',
  'Thrace': '色雷斯',
  'Scythia': '斯基泰',
  'Sarmatia': '薩爾馬提亞',

  // === 印度／南亞 ===
  'Magadha': '摩揭陀',
  'Kosala': '憍薩羅',
  'Vatsa': '跋蹉',
  'Avanti': '阿槃提',
  'Anga': '鴦伽',
  'Vajji': '跋祇',
  'Malla': '末羅',
  'Chedi': '哲提',
  'Kuru': '俱盧',
  'Panchala': '般遮羅',
  'Matsya': '末蹉',
  'Surasena': '蘇羅薩那',
  'Ashmaka': '阿濕摩迦',
  'Kamboja': '劍洴沙',
  'Shakya': '釋迦',
  'Licchavi': '梨車',
  'Pala Empire': '波羅帝國',
  'Sena dynasty': '犀那王朝',
  'Chola dynasty': '注輦王朝',
  'Chola Empire': '注輦帝國',
  'Pandya dynasty': '潘地亞王朝',
  'Chera dynasty': '哲羅王朝',
  'Hoysala Empire': '曷薩拉帝國',
  'Kakatiya dynasty': '卡卡提亞王朝',
  'Rashtrakuta dynasty': '拉施特拉庫塔王朝',
  'Chalukya dynasty': '遮婁其王朝',
  'Pallava dynasty': '帕拉瓦王朝',
  'Satavahana dynasty': '百乘王朝',
  'Vakataka dynasty': '伐迦陀迦王朝',
  'Kushan Empire': '貴霜帝國',
  'Indo-Greek Kingdom': '印度-希臘王國',
  'Indo-Scythians': '印度-斯基泰',
  'Indo-Parthian Kingdom': '印度-帕提亞王國',
  'Western Satraps': '西薩特拉普',
  'Maurya Empire': '孔雀帝國',
  'Shunga Empire': '巽伽王朝',
  'Kanva dynasty': '甘華王朝',
  'Vijayanagara Empire': '毗奢耶那伽羅帝國',
  'Bahmani Sultanate': '巴赫曼尼蘇丹國',
  'Sultanate of Delhi': '德里蘇丹國',
  'Delhi Sultanate': '德里蘇丹國',
  'Tughlaq dynasty': '圖格魯克王朝',
  'Khilji dynasty': '卡爾吉王朝',
  'Lodi dynasty': '洛迪王朝',
  'Sayyid dynasty': '賽義德王朝',
  'Mamluk dynasty (Delhi)': '德里馬木留克王朝',
  'Maratha Confederacy': '馬拉塔聯盟',
  'Maratha Empire': '馬拉塔帝國',
  'Sikh Empire': '錫克帝國',
  'Mysore Kingdom': '邁索爾王國',
  'Kingdom of Mysore': '邁索爾王國',
  'Hyderabad State': '海得拉巴邦',
  'Jaipur State': '齋浦爾邦',
  'Jodhpur State': '焦特布爾邦',
  'Mewar': '梅瓦爾',
  'Marwar': '馬爾瓦',
  'Kingdom of Kandy': '康提王國',
  'Anuradhapura Kingdom': '阿努拉德普勒王國',
  'Polonnaruwa Kingdom': '波羅奈魯沃王國',
  'Jaffna Kingdom': '賈夫納王國',
  'Kingdom of Kotte': '科提王國',
  'Sinhalese kingdom': '錫蘭王國',

  // === 中亞 ===
  'Khanate of Bukhara': '布哈拉汗國',
  'Khanate of Khiva': '希瓦汗國',
  'Khanate of Kokand': '浩罕汗國',
  'Khwarazmian Empire': '花剌子模帝國',
  'Khwarezmian Empire': '花剌子模帝國',
  'Khwarezm': '花剌子模',
  'Khazar Khaganate': '可薩汗國',
  'Western Turkic Khaganate': '西突厥汗國',
  'Eastern Turkic Khaganate': '東突厥汗國',
  'Turkic Khaganate': '突厥汗國',
  'Türk Khaganate': '突厥汗國',
  'Uyghur Khaganate': '回鶻汗國',
  'Kyrgyz Khaganate': '黠戛斯汗國',
  'Khalifate of Cordoba': '科爾多瓦哈里發',
  'Caliphate of Córdoba': '科爾多瓦哈里發',
  'Caliphate of Cordoba': '科爾多瓦哈里發',

  // === 伊斯蘭 ===
  'Fatimid Caliphate': '法蒂瑪哈里發',
  'Ayyubid dynasty': '阿尤布王朝',
  'Almoravid dynasty': '阿穆瓦希德王朝',
  'Almohad Caliphate': '阿穆瓦希丁哈里發',
  'Marinid Sultanate': '馬林蘇丹國',
  'Hafsid dynasty': '哈夫斯王朝',
  'Zayyanid dynasty': '札尚王朝',
  'Wattasid dynasty': '瓦塔斯王朝',
  'Saadi dynasty': '薩阿德王朝',
  'Alaouite dynasty': '阿拉維王朝',
  'Idrisid dynasty': '伊德里斯王朝',
  'Aghlabid dynasty': '阿格拉布王朝',
  'Saffarid dynasty': '薩法爾王朝',
  'Tahirid dynasty': '塔希爾王朝',
  'Samanid Empire': '薩曼帝國',
  'Buyid dynasty': '布伊王朝',
  'Buwayhid dynasty': '布伊王朝',
  'Ghaznavid dynasty': '伽色尼王朝',
  'Ghurid dynasty': '古爾王朝',
  'Seljuk Empire': '塞爾柱帝國',
  'Sultanate of Rum': '羅姆蘇丹國',
  'Great Seljuq Empire': '塞爾柱大帝國',
  'Ilkhanate': '伊兒汗國',
  'Mamluk Sultanate': '馬木留克蘇丹國',
  'Mamluk Sultanate (Cairo)': '馬木留克蘇丹國（開羅）',
  'Bahri dynasty': '巴里王朝',
  'Burji dynasty': '布爾吉王朝',
  'Safavid Iran': '薩法維伊朗',
  'Safavid Empire': '薩法維帝國',
  'Safavid dynasty': '薩法維王朝',
  'Afsharid dynasty': '阿夫沙爾王朝',
  'Zand dynasty': '贊德王朝',
  'Qajar Iran': '卡扎爾伊朗',
  'Qajar dynasty': '卡扎爾王朝',
  'Pahlavi dynasty': '巴列維王朝',
  'Tahirid dynasty (Yemen)': '葉門塔希爾王朝',
  'Rasulid dynasty': '拉蘇里王朝',
  'Zaidi State': '宰德派國',
  'Sokoto Caliphate': '索科托哈里發',
  'Wassoulou Empire': '瓦索盧帝國',

  // === 拜占庭與後繼 ===
  'Latin Empire': '拉丁帝國',
  'Empire of Nicaea': '尼西亞帝國',
  'Empire of Trebizond': '特拉比松帝國',
  'Despotate of Epirus': '伊庇魯斯專制國',
  'Despotate of the Morea': '摩里亞專制國',
  'Tsardom of Bulgaria': '保加利亞沙皇國',
  'First Bulgarian Empire': '第一保加利亞帝國',
  'Second Bulgarian Empire': '第二保加利亞帝國',
  'Serbian Empire': '塞爾維亞帝國',
  'Bosnian Kingdom': '波士尼亞王國',

  // === 中世紀歐洲 ===
  'Frankish Empire': '法蘭克帝國',
  'East Francia': '東法蘭克',
  'West Francia': '西法蘭克',
  'Middle Francia': '中法蘭克',
  'Kingdom of the Lombards': '倫巴底王國',
  'Lombard Kingdom': '倫巴底王國',
  'Visigothic Kingdom': '西哥德王國',
  'Ostrogothic Kingdom': '東哥德王國',
  'Vandal Kingdom': '汪達爾王國',
  'Suebic Kingdom of Galicia': '加利西亞蘇維匯王國',
  'Kingdom of the Suebi': '蘇維匯王國',
  'Burgundian Kingdom': '勃艮第王國',
  'Kingdom of Asturias': '阿斯圖里亞斯王國',
  'Kingdom of León': '萊昂王國',
  'Kingdom of Galicia': '加利西亞王國',
  'Kingdom of Castile': '卡斯提爾王國',
  'Crown of Castile': '卡斯提爾王冠',
  'Kingdom of Aragon': '阿拉貢王國',
  'Crown of Aragon': '阿拉貢王冠',
  'Kingdom of Navarre': '納瓦拉王國',
  'County of Barcelona': '巴塞隆納伯國',
  'County of Toulouse': '土魯斯伯國',
  'Duchy of Aquitaine': '阿基坦公國',
  'Duchy of Normandy': '諾曼第公國',
  'Duchy of Burgundy': '勃艮第公國',
  'Duchy of Brittany': '布列塔尼公國',
  'Duchy of Gascony': '加斯科尼公國',
  'Duchy of Saxony': '薩克森公國',
  'Duchy of Bavaria': '巴伐利亞公國',
  'Duchy of Swabia': '士瓦本公國',
  'Duchy of Franconia': '法蘭克尼亞公國',
  'Duchy of Lorraine': '洛林公國',
  'Duchy of Brabant': '布拉班特公國',
  'Duchy of Bohemia': '波西米亞公國',
  'Kingdom of Bohemia': '波西米亞王國',
  'Kingdom of Hungary': '匈牙利王國',
  'Kingdom of Croatia': '克羅埃西亞王國',
  'Kingdom of Croatia (medieval)': '克羅埃西亞王國（中世紀）',
  'Banate of Bosnia': '波士尼亞班國',
  'Kingdom of Bosnia': '波士尼亞王國',
  'Kingdom of Serbia (medieval)': '塞爾維亞王國（中世紀）',
  'Principality of Serbia': '塞爾維亞親王國',
  'Grand Principality of Moscow': '莫斯科大公國',
  'Grand Duchy of Moscow': '莫斯科大公國',
  'Grand Duchy of Lithuania': '立陶宛大公國',
  'Polish–Lithuanian Commonwealth': '波蘭立陶宛聯邦',
  'Kingdom of Poland (1025–1385)': '波蘭王國（皮亞斯特）',
  'Kingdom of Poland (1385–1569)': '波蘭王國（雅蓋洛）',
  'Kingdom of Poland': '波蘭王國',
  'Crown of the Kingdom of Poland': '波蘭王國王冠',
  'Duchy of Saxony (HRE)': '神聖羅馬帝國薩克森公國',
  'Margraviate of Brandenburg': '布蘭登堡邊伯國',
  'Margraviate of Meissen': '邁森邊伯國',
  'Margraviate of Moravia': '摩拉維亞邊伯國',
  'Margraviate of Austria': '奧地利邊伯國',
  'Duchy of Austria': '奧地利公國',
  'Archduchy of Austria': '奧地利大公國',
  'Habsburg Monarchy': '哈布斯堡君主國',
  'Holy Roman Empire': '神聖羅馬帝國',
  'Frankish Kingdom': '法蘭克王國',
  'Merovingian dynasty': '墨洛溫王朝',
  'Carolingian dynasty': '加洛林王朝',
  'Capetian dynasty': '卡佩王朝',
  'Valois dynasty': '瓦盧瓦王朝',
  'Bourbon dynasty': '波旁王朝',
  'Plantagenet dynasty': '金雀花王朝',
  'House of Wessex': '韋塞克斯王朝',
  'Kingdom of Wessex': '韋塞克斯王國',
  'Kingdom of Mercia': '麥西亞王國',
  'Kingdom of Northumbria': '諾森布里亞王國',
  'Kingdom of East Anglia': '東盎格利亞王國',
  'Kingdom of Kent': '肯特王國',
  'Kingdom of Essex': '埃塞克斯王國',
  'Kingdom of Sussex': '蘇塞克斯王國',
  'Danelaw': '丹麥法區',
  'Kingdom of Jorvik': '約克王國',
  'Kingdom of Strathclyde': '斯特拉斯克萊德王國',
  'Kingdom of Alba': '阿爾巴王國',
  'Kingdom of Scotland': '蘇格蘭王國',
  'Kingdom of Ireland': '愛爾蘭王國',
  'Kingdom of England': '英格蘭王國',
  'Kingdom of Great Britain': '大不列顛王國',
  'United Kingdom of Great Britain and Ireland': '大不列顛及愛爾蘭聯合王國',
  'Republic of Venice': '威尼斯共和國',
  'Republic of Genoa': '熱那亞共和國',
  'Republic of Florence': '佛羅倫斯共和國',
  'Republic of Pisa': '比薩共和國',
  'Republic of Lucca': '盧卡共和國',
  'Republic of Siena': '錫耶納共和國',
  'Republic of Ragusa': '拉古薩共和國',
  'Republic of Amalfi': '阿馬爾菲共和國',
  'Most Serene Republic of Venice': '至尊威尼斯共和國',
  'Duchy of Milan': '米蘭公國',
  'Duchy of Mantua': '曼圖亞公國',
  'Duchy of Ferrara': '費拉拉公國',
  'Duchy of Parma': '帕爾馬公國',
  'Duchy of Modena': '摩德納公國',
  'Duchy of Savoy': '薩伏依公國',
  'Duchy of Tuscany': '托斯卡尼公國',
  'Grand Duchy of Tuscany': '托斯卡尼大公國',
  'Kingdom of Naples': '那不勒斯王國',
  'Kingdom of Sicily': '西西里王國',
  'Kingdom of Sardinia': '薩丁尼亞王國',
  'Kingdom of the Two Sicilies': '兩西西里王國',
  'Papal States': '教皇國',
  'Kingdom of Italy (1861–1946)': '義大利王國',
  'Kingdom of Italy': '義大利王國',
  'Cisalpine Republic': '齊薩爾皮恩共和國',
  'Italian Republic (Napoleonic)': '義大利共和國（拿破崙）',
  'First French Empire': '法蘭西第一帝國',
  'Second French Empire': '法蘭西第二帝國',
  'French Third Republic': '法蘭西第三共和',
  'French Fourth Republic': '法蘭西第四共和',
  'French Fifth Republic': '法蘭西第五共和',

  // === 北歐 ===
  'Kingdom of Denmark': '丹麥王國',
  'Kingdom of Norway': '挪威王國',
  'Kingdom of Sweden': '瑞典王國',
  'Swedish Empire': '瑞典帝國',
  'Calmar Union': '卡爾馬聯盟',
  'Kingdom of Iceland': '冰島王國',
  'Old Swiss Confederacy': '舊瑞士邦聯',
  'Swiss Confederation': '瑞士邦聯',

  // === 中亞蒙古 ===
  'Karakhanid Khanate': '喀喇汗國',
  'Kara-Khanid Khanate': '喀喇汗國',
  'Qara Khitai': '西遼',
  'Western Liao': '西遼',
  'Liao dynasty': '遼朝',
  'Western Xia': '西夏',
  'Jin dynasty (1115–1234)': '金朝（女真）',
  'Yuan dynasty': '元朝',
  'Northern Yuan': '北元',
  'Northern Yuan dynasty': '北元',
  'Mongol Empire': '蒙古帝國',
  'Golden Horde': '金帳汗國',
  'White Horde': '白帳汗國',
  'Blue Horde': '青帳汗國',
  'Chagatai Khanate': '察合台汗國',
  'Moghulistan': '東察合台汗國',
  'Timurid Empire': '帖木兒帝國',
  'Khanate of the Crimea': '克里米亞汗國',
  'Crimean Khanate': '克里米亞汗國',
  'Kazan Khanate': '喀山汗國',
  'Astrakhan Khanate': '阿斯特拉罕汗國',
  'Khanate of Sibir': '失必兒汗國',
  'Khanate of Kasimov': '卡西莫夫汗國',
  'Nogai Horde': '諾蓋部',
  'Oirats': '瓦剌',
  'Oirat Khanate': '瓦剌汗國',
  'Dzungar Khanate': '準噶爾汗國',
  'Zunghar Khanate': '準噶爾汗國',

  // === 中國朝代 ===
  'Shang dynasty': '商朝',
  'Zhou dynasty': '周朝',
  'Western Zhou': '西周',
  'Eastern Zhou': '東周',
  'Spring and Autumn period': '春秋',
  'Warring States period': '戰國',
  'Qin dynasty': '秦朝',
  'Western Han': '西漢',
  'Eastern Han': '東漢',
  'Xin dynasty': '新莽',
  'Three Kingdoms': '三國',
  'Cao Wei': '曹魏',
  'Shu Han': '蜀漢',
  'Eastern Wu': '東吳',
  'Jin dynasty (266–420)': '晉朝',
  'Western Jin': '西晉',
  'Eastern Jin': '東晉',
  'Sixteen Kingdoms': '十六國',
  'Southern and Northern dynasties': '南北朝',
  'Northern Wei': '北魏',
  'Eastern Wei': '東魏',
  'Western Wei': '西魏',
  'Northern Qi': '北齊',
  'Northern Zhou': '北周',
  'Liu Song dynasty': '劉宋',
  'Southern Qi': '南齊',
  'Liang dynasty': '梁朝',
  'Chen dynasty': '陳朝',
  'Sui dynasty': '隋朝',
  'Tang dynasty': '唐朝',
  'Wu Zhou': '武周',
  'Five Dynasties and Ten Kingdoms period': '五代十國',
  'Later Liang': '後梁',
  'Later Tang': '後唐',
  'Later Jin (Five Dynasties)': '後晉',
  'Later Han (Five Dynasties)': '後漢',
  'Later Zhou': '後周',
  'Song dynasty': '宋朝',
  'Northern Song': '北宋',
  'Southern Song': '南宋',
  'Ming dynasty': '明朝',
  'Southern Ming': '南明',
  'Qing dynasty': '清朝',
  'Later Jin (Manchu)': '後金',
  'Republic of China (1912–1949)': '中華民國',
  'Tibet (1912–1951)': '西藏（1912–1951）',
  'Mengjiang': '蒙疆',
  'Manchukuo': '滿洲國',

  // === 朝鮮／日本／越南 ===
  'Gojoseon': '古朝鮮',
  'Goguryeo': '高句麗',
  'Baekje': '百濟',
  'Silla': '新羅',
  'Unified Silla': '統一新羅',
  'Balhae': '渤海',
  'Later Silla': '後新羅',
  'Goryeo': '高麗',
  'Joseon': '朝鮮王朝',
  'Korean Empire': '大韓帝國',
  'Yamato': '大和',
  'Asuka period': '飛鳥時代',
  'Nara period': '奈良時代',
  'Heian period': '平安時代',
  'Kamakura shogunate': '鎌倉幕府',
  'Ashikaga shogunate': '室町幕府',
  'Muromachi period': '室町時代',
  'Tokugawa shogunate': '德川幕府',
  'Edo period': '江戶時代',
  'Empire of Japan': '大日本帝國',
  'Đại Việt': '大越',
  'Văn Lang': '文郎國',
  'Âu Lạc': '甌貉',
  'Nam Việt': '南越',
  'Nanyue': '南越',
  'Đại Cồ Việt': '大瞿越',
  'Champa': '占婆',
  'Funan': '扶南',
  'Chenla': '真臘',
  'Khmer Empire': '高棉帝國',
  'Lan Xang': '瀾滄王國',
  'Sukhothai Kingdom': '素可泰王國',
  'Ayutthaya Kingdom': '大城王朝',
  'Rattanakosin Kingdom': '曼谷王朝（拉達那哥欣）',
  'Toungoo dynasty': '東吁王朝',
  'Konbaung dynasty': '貢榜王朝',
  'Pagan Kingdom': '蒲甘王國',

  // === 東南亞海島 ===
  'Srivijaya': '室利佛逝',
  'Majapahit': '滿者伯夷',
  'Mataram Kingdom': '滿打蘭王國',
  'Sailendra dynasty': '夏連特拉王朝',
  'Sultanate of Malacca': '馬六甲蘇丹國',
  'Sultanate of Aceh': '亞齊蘇丹國',
  'Sultanate of Brunei': '汶萊蘇丹國',
  'Sultanate of Sulu': '蘇祿蘇丹國',
  'Sultanate of Mataram': '滿打蘭蘇丹國',
  'Sultanate of Demak': '德馬克蘇丹國',
  'Sultanate of Banten': '萬丹蘇丹國',
  'Maguindanao Sultanate': '馬京達瑙蘇丹國',
  'Bruneian Empire': '汶萊帝國',

  // === 非洲 ===
  'Kingdom of Aksum': '阿克蘇姆王國',
  'Aksumite Empire': '阿克蘇姆帝國',
  'Ethiopian Empire': '衣索比亞帝國',
  'Zagwe dynasty': '札格維王朝',
  'Solomonic dynasty': '所羅門王朝',
  'Kingdom of Kush': '庫施王國',
  'Kingdom of Meroë': '麥羅埃王國',
  'Kingdom of Makuria': '馬庫里亞王國',
  'Kingdom of Alodia': '阿洛迪亞王國',
  'Kingdom of Nobatia': '諾巴提亞王國',
  'Ghana Empire': '加納帝國',
  'Mali Empire': '馬利帝國',
  'Songhai Empire': '桑海帝國',
  'Bornu Empire': '博爾努帝國',
  'Kanem Empire': '卡涅姆帝國',
  'Kanem-Bornu Empire': '卡涅姆-博爾努帝國',
  'Hausa Kingdoms': '豪薩諸邦',
  'Kingdom of Kongo': '剛果王國',
  'Kingdom of Ndongo': '恩東戈王國',
  'Kingdom of Matamba': '馬坦巴王國',
  'Kingdom of Loango': '羅安戈王國',
  'Kingdom of Luba': '盧巴王國',
  'Kingdom of Lunda': '盧巴-倫達王國',
  'Lunda Empire': '倫達帝國',
  'Kingdom of Mutapa': '穆塔帕王國',
  'Mutapa Empire': '穆塔帕帝國',
  'Kingdom of Zimbabwe': '大津巴布韋王國',
  'Great Zimbabwe': '大津巴布韋',
  'Kingdom of Mapungubwe': '馬蓬古布韋王國',
  'Rozvi Empire': '羅茲維帝國',
  'Mwene Matapa': '穆韋內穆塔帕',
  'Kingdom of Zulu': '祖魯王國',
  'Zulu Kingdom': '祖魯王國',
  'Dahomey': '達荷美',
  'Kingdom of Dahomey': '達荷美王國',
  'Oyo Empire': '奧約帝國',
  'Benin Empire': '貝寧帝國',
  'Ashanti Empire': '阿散蒂帝國',
  'Buganda': '布干達',
  'Kingdom of Buganda': '布干達王國',
  'Kingdom of Rwanda': '盧安達王國',
  'Kingdom of Burundi': '蒲隆地王國',

  // === 美洲 ===
  'Inca Empire': '印加帝國',
  'Aztec Empire': '阿茲特克帝國',
  'Aztec Triple Alliance': '阿茲特克三聯盟',
  'Maya civilization': '馬雅文明',
  'Toltec Empire': '托爾特克帝國',
  'Olmec civilization': '奧爾梅克文明',
  'Zapotec civilization': '薩波特克文明',
  'Mixtec civilization': '米斯特克文明',
  'Mochica culture': '莫切文化',
  'Moche civilization': '莫切文明',
  'Chavin culture': '查文文化',
  'Chimor': '奇穆',
  'Tiwanaku Empire': '蒂瓦納庫帝國',
  'Tiwanaku': '蒂瓦納庫',
  'Wari Empire': '瓦里帝國',
  'Nazca culture': '納斯卡文化',
  'Norte Chico civilization': '小北文明',
  'Caral–Supe civilization': '卡拉爾-蘇佩文明',
  'Cultura Tarija': '塔里哈文化',
  'Mississippian culture': '密西西比文化',
  'Cahokia': '卡霍基亞',
  'Anasazi': '阿納薩齊',
  'Ancestral Puebloans': '普韋布洛先民',

  // === 太平洋 ===
  "Tu'i Tonga Empire": '東加帝國',
  'Hawaiian Kingdom': '夏威夷王國',
  'Kingdom of Hawaii': '夏威夷王國',
  'Kingdom of Tahiti': '大溪地王國',
  'Kingdom of Rarotonga': '拉羅東加王國',
  'Tongan Empire': '東加帝國',

  // === 其他重要近代 / 現代 ===
  'Confederate States of America': '美利堅聯盟國',
  'Republic of Texas': '德克薩斯共和國',
  'Republic of California': '加利福尼亞共和國',
  'Empire of Brazil': '巴西帝國',
  'Empire of Mexico': '墨西哥帝國',
  'First Mexican Empire': '第一墨西哥帝國',
  'Second Mexican Empire': '第二墨西哥帝國',
  'Soviet Union': '蘇聯',
  'Union of Soviet Socialist Republics': '蘇維埃社會主義共和國聯邦',
  'Russian Soviet Federative Socialist Republic': '俄羅斯蘇維埃聯邦社會主義共和國',
  'Russian Empire': '俄羅斯帝國',
  'Tsardom of Russia': '俄羅斯沙皇國',
  'Russian Republic': '俄羅斯共和國',
  'Russian Provisional Government': '俄羅斯臨時政府',
  'Republic of Weimar': '威瑪共和國',
  'Weimar Republic': '威瑪共和國',
  'Nazi Germany': '納粹德國',
  'German Reich': '德意志國',
  'German Empire': '德意志帝國',
  'North German Confederation': '北德意志邦聯',
  'German Confederation': '德意志邦聯',
  'Holy Roman Empire of the German Nation': '德意志民族神聖羅馬帝國',
  'Austria-Hungary': '奧匈帝國',
  'Austrian Empire': '奧地利帝國',
  'Kingdom of Yugoslavia': '南斯拉夫王國',
  'Yugoslavia': '南斯拉夫',
  'Socialist Federal Republic of Yugoslavia': '南斯拉夫社會主義聯邦共和國',
  'Czechoslovakia': '捷克斯洛伐克',
  'East Germany': '東德',
  'West Germany': '西德',
  'German Democratic Republic': '德意志民主共和國',
  'Federal Republic of Germany': '德意志聯邦共和國',
}

// ===== 規則翻譯 =====
const SUFFIX_DICT = {
  ' Kingdom': '王國',
  ' kingdom': '王國',
  ' Empire': '帝國',
  ' Khanate': '汗國',
  ' Caliphate': '哈里發',
  ' Sultanate': '蘇丹國',
  ' Republic': '共和國',
  ' Confederacy': '邦聯',
  ' Confederation': '邦聯',
  ' Federation': '聯邦',
  ' dynasty': '王朝',
  ' Dynasty': '王朝',
  ' Civilization': '文明',
  ' civilization': '文明',
  ' Culture': '文化',
  ' culture': '文化',
  ' League': '同盟',
  ' State': '邦',          // 印度王公邦 etc.
  ' state': '邦',
  ' Principality': '親王國',
  ' principality': '親王國',
  ' Province': '行省',
  ' province': '行省',
  ' County': '伯國',
  ' Duchy': '公國',
  ' Tsardom': '沙皇國',
  ' Shogunate': '幕府',
  ' shogunate': '幕府',
  ' Imamate': '伊瑪目國',
  ' imamate': '伊瑪目國',
  ' Voivodeship': '伏伊伏丁那',
  ' Banate': '班國',
  ' banate': '班國',
  ' Despotate': '專制國',
  ' despotate': '專制國',
  ' Patriarchate': '宗主教區',
  ' Lordship': '領主國',
  ' lordship': '領主國',
  ' Margraviate': '邊伯國',
  ' Landgraviate': '方伯國',
  ' Archduchy': '大公國',
  ' archduchy': '大公國',
  ' Grand Duchy': '大公國',
}

const PREFIX_DICT = {
  'Kingdom of ': { suffix: '王國' },
  'Empire of ': { suffix: '帝國' },
  'Duchy of ': { suffix: '公國' },
  'Grand Duchy of ': { suffix: '大公國' },
  'Principality of ': { suffix: '親王國' },
  'Republic of ': { suffix: '共和國' },
  'Sultanate of ': { suffix: '蘇丹國' },
  'Emirate of ': { suffix: '酋長國' },
  'Caliphate of ': { suffix: '哈里發' },
  'Khanate of ': { suffix: '汗國' },
  'County of ': { suffix: '伯國' },
  'Earldom of ': { suffix: '伯國' },
  'Margraviate of ': { suffix: '邊伯國' },
  'Landgraviate of ': { suffix: '方伯國' },
  'Lordship of ': { suffix: '領主國' },
  'Bishopric of ': { suffix: '主教區' },
  'Archbishopric of ': { suffix: '大主教區' },
  'Free City of ': { suffix: '自由市' },
  'Free Imperial City of ': { suffix: '帝國自由市' },
}

function ruleTranslate(name) {
  // Prefix 模式
  for (const [prefix, { suffix }] of Object.entries(PREFIX_DICT)) {
    if (name.startsWith(prefix)) {
      const place = name.slice(prefix.length).trim()
      // 地名本身若沒翻譯就保留英文（這時整體還是有「X 王國」格式，比 null 好）
      return place + ' ' + suffix
    }
  }
  // Suffix 模式
  for (const [suffix, zhSuffix] of Object.entries(SUFFIX_DICT)) {
    if (name.endsWith(suffix)) {
      const stem = name.slice(0, name.length - suffix.length).trim()
      return stem + zhSuffix
    }
  }
  return null
}

// ===== Main =====
const states = JSON.parse(readFileSync(FILE, 'utf8'))

let filledManual = 0
let filledRule = 0

for (const s of states) {
  if (s.name_zh) continue
  // 1) Manual
  if (MANUAL_TRANSLATIONS[s.name_en]) {
    s.name_zh = MANUAL_TRANSLATIONS[s.name_en]
    filledManual += 1
    continue
  }
  // 2) Rule
  const r = ruleTranslate(s.name_en)
  if (r) {
    s.name_zh = r
    filledRule += 1
  }
}

writeFileSync(FILE, JSON.stringify(states))
const withZh = states.filter(s => s.name_zh).length
console.log(`Filled by manual table: ${filledManual}`)
console.log(`Filled by rule patterns: ${filledRule}`)
console.log(`Total with zh: ${withZh} / ${states.length} (${(withZh*100/states.length).toFixed(1)}%)`)
