#!/usr/bin/env node
/**
 * 補完 wikidata-states.json 缺少中文名的條目：
 *   1) 規則翻譯：Kingdom of X → X 王國、Duchy of X → X 公國 等
 *   2) 人工翻譯表 MANUAL_TRANSLATIONS（歷史學常用譯名）
 *
 * 寫回 public/maps/wikidata-states.json
 */

import { readFileSync, writeFileSync } from 'node:fs'

const FILE = 'public/maps/wikidata-states.json'

// ===== 人工翻譯表（依歷史學界常用譯法）=====
// 涵蓋從蘇美城邦、古典近東、希臘羅馬、印度諸邦、中亞、伊斯蘭、中世紀歐洲、
// 非洲王國、前哥倫布美洲、東南亞、東亞分裂期等。持續可擴充。
const MANUAL_TRANSLATIONS = {
  // === 古代近東：蘇美／巴比倫／亞述／敘利亞城邦 ===
  'Namri': '南姆里',
  'Abarsal': '阿巴薩爾',
  'Old Kingdom of Egypt': '埃及古王國',
  'Middle Kingdom of Egypt': '埃及中王國',
  'New Kingdom of Egypt': '埃及新王國',
  'First Intermediate Period of Egypt': '埃及第一中間期',
  'Second Intermediate Period of Egypt': '埃及第二中間期',
  'Third Intermediate Period of Egypt': '埃及第三中間期',
  'Late Period of ancient Egypt': '埃及後期王朝',
  'Early Dynastic Period (Egypt)': '埃及早王朝時期',
  'Predynastic Egypt': '埃及前王朝時期',
  'Ptolemaic Kingdom': '托勒密王國',
  'Hatti': '哈梯（赫梯本部）',
  'Hattusa': '哈圖薩',
  'Mitanni': '米坦尼',
  'Isuwa': '伊蘇瓦',
  'Mira': '米拉',
  'Tuwanuwa': '圖瓦努瓦',
  'Ahhiyawa': '阿希亞瓦',
  'Khalitu': '哈利圖',
  'Gurgum': '古爾古姆',
  'Bit Bahiani': '比特巴希亞尼',
  'Bit Adini': '比特阿迪尼',
  'Bit-Adini': '比特阿迪尼',
  'Gandhāra': '犍陀羅',
  'Gandhara': '犍陀羅',
  'Philistia': '非利士',
  'Soli': '索利',
  'Ammon': '亞捫',
  'Moab': '摩押',
  'Edom': '以東',
  'Chaldea': '迦勒底',
  'Hamath': '哈馬特',
  'Hubushkia': '胡布什基亞',
  'Lapathus': '拉帕索斯',
  'Laqe': '拉凱',
  'Zamua': '扎穆阿',
  'Zobah': '瑣巴',
  'Alzi': '阿爾齊',
  'Daiaeni': '達伊埃尼',
  'Syrakousai': '敘拉古',
  'Syracuse': '敘拉古',
  'Medo-Persia': '米底-波斯',
  'Media': '米底',
  'Lydia': '呂底亞',
  'Phrygia': '弗里吉亞',
  'Lycia': '呂基亞',
  'Pamphylia': '潘菲利亞',
  'Cilicia': '奇里乞亞',
  'Cappadocia': '卡帕多西亞',
  'Pontus': '本都',
  'Bithynia': '比提尼亞',
  'Galatia': '加拉太',
  'Pergamum': '帕加馬',
  'Pergamon': '帕加馬',
  'Commagene': '康馬基尼',
  'Armenia Minor': '小亞美尼亞',
  'Sophene': '索菲尼',
  'Osroene': '奧斯洛尼',
  'Hatra': '哈特拉',
  'Adiabene': '阿迪亞貝尼',
  'Characene': '卡拉塞尼',
  'Elymais': '埃利邁斯',
  'Persis': '帕爾斯（波斯本土）',
  'Hyrcania': '希爾卡尼亞',
  'Parthia': '帕提亞',
  'Bactria': '巴克特里亞',
  'Sogdia': '粟特',
  'Sogdiana': '粟特',
  'Margiana': '馬爾吉亞那',
  'Hyrcanian Empire': '希爾卡尼亞帝國',
  'Aramean': '亞蘭',
  'Aramaeans': '亞蘭人',
  'Phoenicia': '腓尼基',
  'Tyre': '推羅',
  'Sidon': '西頓',
  'Byblos': '比布魯斯',
  'Ugarit': '烏加里特',
  'Carthage': '迦太基',
  'Numidia': '努米底亞',
  'Mauretania': '茅利塔尼亞',
  'Cyrenaica': '昔蘭尼加',
  'Cyrene': '昔蘭尼',

  // === 古典希臘 ===
  'Sparta': '斯巴達',
  'Athens': '雅典',
  'Thebes': '底比斯',
  'Corinth': '科林斯',
  'Argos': '阿爾戈斯',
  'Megara': '麥加拉',
  'Aetolian League': '埃托利亞同盟',
  'Achaean League': '亞該亞同盟',
  'Boeotian League': '波奧提亞同盟',
  'Delphic Amphictyony': '德爾斐近鄰同盟',
  'Magna Graecia': '大希臘',
  'Epirus (ancient state)': '伊庇魯斯王國',
  'Epirus': '伊庇魯斯',
  'Illyria': '伊利里亞',
  'Dalmatia': '達爾馬提亞',
  'Pannonia': '潘諾尼亞',
  'Dacia': '達契亞',
  'Thrace': '色雷斯',
  'Scythia': '斯基泰',
  'Sarmatia': '薩爾馬提亞',

  // === 印度／南亞 ===
  'Magadha': '摩揭陀',
  'Kosala': '憍薩羅',
  'Vatsa': '跋蹉',
  'Avanti': '阿槃提',
  'Anga': '鴦伽',
  'Vajji': '跋祇',
  'Malla': '末羅',
  'Chedi': '哲提',
  'Kuru': '俱盧',
  'Panchala': '般遮羅',
  'Matsya': '末蹉',
  'Surasena': '蘇羅薩那',
  'Ashmaka': '阿濕摩迦',
  'Kamboja': '劍洴沙',
  'Shakya': '釋迦',
  'Licchavi': '梨車',
  'Pala Empire': '波羅帝國',
  'Sena dynasty': '犀那王朝',
  'Chola dynasty': '注輦王朝',
  'Chola Empire': '注輦帝國',
  'Pandya dynasty': '潘地亞王朝',
  'Chera dynasty': '哲羅王朝',
  'Hoysala Empire': '曷薩拉帝國',
  'Kakatiya dynasty': '卡卡提亞王朝',
  'Rashtrakuta dynasty': '拉施特拉庫塔王朝',
  'Chalukya dynasty': '遮婁其王朝',
  'Pallava dynasty': '帕拉瓦王朝',
  'Satavahana dynasty': '百乘王朝',
  'Vakataka dynasty': '伐迦陀迦王朝',
  'Kushan Empire': '貴霜帝國',
  'Indo-Greek Kingdom': '印度-希臘王國',
  'Indo-Scythians': '印度-斯基泰',
  'Indo-Parthian Kingdom': '印度-帕提亞王國',
  'Western Satraps': '西薩特拉普',
  'Maurya Empire': '孔雀帝國',
  'Shunga Empire': '巽伽王朝',
  'Kanva dynasty': '甘華王朝',
  'Vijayanagara Empire': '毗奢耶那伽羅帝國',
  'Bahmani Sultanate': '巴赫曼尼蘇丹國',
  'Sultanate of Delhi': '德里蘇丹國',
  'Delhi Sultanate': '德里蘇丹國',
  'Tughlaq dynasty': '圖格魯克王朝',
  'Khilji dynasty': '卡爾吉王朝',
  'Lodi dynasty': '洛迪王朝',
  'Sayyid dynasty': '賽義德王朝',
  'Mamluk dynasty (Delhi)': '德里馬木留克王朝',
  'Maratha Confederacy': '馬拉塔聯盟',
  'Maratha Empire': '馬拉塔帝國',
  'Sikh Empire': '錫克帝國',
  'Mysore Kingdom': '邁索爾王國',
  'Kingdom of Mysore': '邁索爾王國',
  'Hyderabad State': '海得拉巴邦',
  'Jaipur State': '齋浦爾邦',
  'Jodhpur State': '焦特布爾邦',
  'Mewar': '梅瓦爾',
  'Marwar': '馬爾瓦',
  'Kingdom of Kandy': '康提王國',
  'Anuradhapura Kingdom': '阿努拉德普勒王國',
  'Polonnaruwa Kingdom': '波羅奈魯沃王國',
  'Jaffna Kingdom': '賈夫納王國',
  'Kingdom of Kotte': '科提王國',
  'Sinhalese kingdom': '錫蘭王國',

  // === 中亞 ===
  'Khanate of Bukhara': '布哈拉汗國',
  'Khanate of Khiva': '希瓦汗國',
  'Khanate of Kokand': '浩罕汗國',
  'Khwarazmian Empire': '花剌子模帝國',
  'Khwarezmian Empire': '花剌子模帝國',
  'Khwarezm': '花剌子模',
  'Khazar Khaganate': '可薩汗國',
  'Western Turkic Khaganate': '西突厥汗國',
  'Eastern Turkic Khaganate': '東突厥汗國',
  'Turkic Khaganate': '突厥汗國',
  'Türk Khaganate': '突厥汗國',
  'Uyghur Khaganate': '回鶻汗國',
  'Kyrgyz Khaganate': '黠戛斯汗國',
  'Khalifate of Cordoba': '科爾多瓦哈里發',
  'Caliphate of Córdoba': '科爾多瓦哈里發',
  'Caliphate of Cordoba': '科爾多瓦哈里發',

  // === 伊斯蘭 ===
  'Fatimid Caliphate': '法蒂瑪哈里發',
  'Ayyubid dynasty': '阿尤布王朝',
  'Almoravid dynasty': '阿穆瓦希德王朝',
  'Almohad Caliphate': '阿穆瓦希丁哈里發',
  'Marinid Sultanate': '馬林蘇丹國',
  'Hafsid dynasty': '哈夫斯王朝',
  'Zayyanid dynasty': '札尚王朝',
  'Wattasid dynasty': '瓦塔斯王朝',
  'Saadi dynasty': '薩阿德王朝',
  'Alaouite dynasty': '阿拉維王朝',
  'Idrisid dynasty': '伊德里斯王朝',
  'Aghlabid dynasty': '阿格拉布王朝',
  'Saffarid dynasty': '薩法爾王朝',
  'Tahirid dynasty': '塔希爾王朝',
  'Samanid Empire': '薩曼帝國',
  'Buyid dynasty': '布伊王朝',
  'Buwayhid dynasty': '布伊王朝',
  'Ghaznavid dynasty': '伽色尼王朝',
  'Ghurid dynasty': '古爾王朝',
  'Seljuk Empire': '塞爾柱帝國',
  'Sultanate of Rum': '羅姆蘇丹國',
  'Great Seljuq Empire': '塞爾柱大帝國',
  'Ilkhanate': '伊兒汗國',
  'Mamluk Sultanate': '馬木留克蘇丹國',
  'Mamluk Sultanate (Cairo)': '馬木留克蘇丹國（開羅）',
  'Bahri dynasty': '巴里王朝',
  'Burji dynasty': '布爾吉王朝',
  'Safavid Iran': '薩法維伊朗',
  'Safavid Empire': '薩法維帝國',
  'Safavid dynasty': '薩法維王朝',
  'Afsharid dynasty': '阿夫沙爾王朝',
  'Zand dynasty': '贊德王朝',
  'Qajar Iran': '卡扎爾伊朗',
  'Qajar dynasty': '卡扎爾王朝',
  'Pahlavi dynasty': '巴列維王朝',
  'Tahirid dynasty (Yemen)': '葉門塔希爾王朝',
  'Rasulid dynasty': '拉蘇里王朝',
  'Zaidi State': '宰德派國',
  'Sokoto Caliphate': '索科托哈里發',
  'Wassoulou Empire': '瓦索盧帝國',

  // === 拜占庭與後繼 ===
  'Latin Empire': '拉丁帝國',
  'Empire of Nicaea': '尼西亞帝國',
  'Empire of Trebizond': '特拉比松帝國',
  'Despotate of Epirus': '伊庇魯斯專制國',
  'Despotate of the Morea': '摩里亞專制國',
  'Tsardom of Bulgaria': '保加利亞沙皇國',
  'First Bulgarian Empire': '第一保加利亞帝國',
  'Second Bulgarian Empire': '第二保加利亞帝國',
  'Serbian Empire': '塞爾維亞帝國',
  'Bosnian Kingdom': '波士尼亞王國',

  // === 中世紀歐洲 ===
  'Frankish Empire': '法蘭克帝國',
  'East Francia': '東法蘭克',
  'West Francia': '西法蘭克',
  'Middle Francia': '中法蘭克',
  'Kingdom of the Lombards': '倫巴底王國',
  'Lombard Kingdom': '倫巴底王國',
  'Visigothic Kingdom': '西哥德王國',
  'Ostrogothic Kingdom': '東哥德王國',
  'Vandal Kingdom': '汪達爾王國',
  'Suebic Kingdom of Galicia': '加利西亞蘇維匯王國',
  'Kingdom of the Suebi': '蘇維匯王國',
  'Burgundian Kingdom': '勃艮第王國',
  'Kingdom of Asturias': '阿斯圖里亞斯王國',
  'Kingdom of León': '萊昂王國',
  'Kingdom of Galicia': '加利西亞王國',
  'Kingdom of Castile': '卡斯提爾王國',
  'Crown of Castile': '卡斯提爾王冠',
  'Kingdom of Aragon': '阿拉貢王國',
  'Crown of Aragon': '阿拉貢王冠',
  'Kingdom of Navarre': '納瓦拉王國',
  'County of Barcelona': '巴塞隆納伯國',
  'County of Toulouse': '土魯斯伯國',
  'Duchy of Aquitaine': '阿基坦公國',
  'Duchy of Normandy': '諾曼第公國',
  'Duchy of Burgundy': '勃艮第公國',
  'Duchy of Brittany': '布列塔尼公國',
  'Duchy of Gascony': '加斯科尼公國',
  'Duchy of Saxony': '薩克森公國',
  'Duchy of Bavaria': '巴伐利亞公國',
  'Duchy of Swabia': '士瓦本公國',
  'Duchy of Franconia': '法蘭克尼亞公國',
  'Duchy of Lorraine': '洛林公國',
  'Duchy of Brabant': '布拉班特公國',
  'Duchy of Bohemia': '波西米亞公國',
  'Kingdom of Bohemia': '波西米亞王國',
  'Kingdom of Hungary': '匈牙利王國',
  'Kingdom of Croatia': '克羅埃西亞王國',
  'Kingdom of Croatia (medieval)': '克羅埃西亞王國（中世紀）',
  'Banate of Bosnia': '波士尼亞班國',
  'Kingdom of Bosnia': '波士尼亞王國',
  'Kingdom of Serbia (medieval)': '塞爾維亞王國（中世紀）',
  'Principality of Serbia': '塞爾維亞親王國',
  'Grand Principality of Moscow': '莫斯科大公國',
  'Grand Duchy of Moscow': '莫斯科大公國',
  'Grand Duchy of Lithuania': '立陶宛大公國',
  'Polish–Lithuanian Commonwealth': '波蘭立陶宛聯邦',
  'Kingdom of Poland (1025–1385)': '波蘭王國（皮亞斯特）',
  'Kingdom of Poland (1385–1569)': '波蘭王國（雅蓋洛）',
  'Kingdom of Poland': '波蘭王國',
  'Crown of the Kingdom of Poland': '波蘭王國王冠',
  'Duchy of Saxony (HRE)': '神聖羅馬帝國薩克森公國',
  'Margraviate of Brandenburg': '布蘭登堡邊伯國',
  'Margraviate of Meissen': '邁森邊伯國',
  'Margraviate of Moravia': '摩拉維亞邊伯國',
  'Margraviate of Austria': '奧地利邊伯國',
  'Duchy of Austria': '奧地利公國',
  'Archduchy of Austria': '奧地利大公國',
  'Habsburg Monarchy': '哈布斯堡君主國',
  'Holy Roman Empire': '神聖羅馬帝國',
  'Frankish Kingdom': '法蘭克王國',
  'Merovingian dynasty': '墨洛溫王朝',
  'Carolingian dynasty': '加洛林王朝',
  'Capetian dynasty': '卡佩王朝',
  'Valois dynasty': '瓦盧瓦王朝',
  'Bourbon dynasty': '波旁王朝',
  'Plantagenet dynasty': '金雀花王朝',
  'House of Wessex': '韋塞克斯王朝',
  'Kingdom of Wessex': '韋塞克斯王國',
  'Kingdom of Mercia': '麥西亞王國',
  'Kingdom of Northumbria': '諾森布里亞王國',
  'Kingdom of East Anglia': '東盎格利亞王國',
  'Kingdom of Kent': '肯特王國',
  'Kingdom of Essex': '埃塞克斯王國',
  'Kingdom of Sussex': '蘇塞克斯王國',
  'Danelaw': '丹麥法區',
  'Kingdom of Jorvik': '約克王國',
  'Kingdom of Strathclyde': '斯特拉斯克萊德王國',
  'Kingdom of Alba': '阿爾巴王國',
  'Kingdom of Scotland': '蘇格蘭王國',
  'Kingdom of Ireland': '愛爾蘭王國',
  'Kingdom of England': '英格蘭王國',
  'Kingdom of Great Britain': '大不列顛王國',
  'United Kingdom of Great Britain and Ireland': '大不列顛及愛爾蘭聯合王國',
  'Republic of Venice': '威尼斯共和國',
  'Republic of Genoa': '熱那亞共和國',
  'Republic of Florence': '佛羅倫斯共和國',
  'Republic of Pisa': '比薩共和國',
  'Republic of Lucca': '盧卡共和國',
  'Republic of Siena': '錫耶納共和國',
  'Republic of Ragusa': '拉古薩共和國',
  'Republic of Amalfi': '阿馬爾菲共和國',
  'Most Serene Republic of Venice': '至尊威尼斯共和國',
  'Duchy of Milan': '米蘭公國',
  'Duchy of Mantua': '曼圖亞公國',
  'Duchy of Ferrara': '費拉拉公國',
  'Duchy of Parma': '帕爾馬公國',
  'Duchy of Modena': '摩德納公國',
  'Duchy of Savoy': '薩伏依公國',
  'Duchy of Tuscany': '托斯卡尼公國',
  'Grand Duchy of Tuscany': '托斯卡尼大公國',
  'Kingdom of Naples': '那不勒斯王國',
  'Kingdom of Sicily': '西西里王國',
  'Kingdom of Sardinia': '薩丁尼亞王國',
  'Kingdom of the Two Sicilies': '兩西西里王國',
  'Papal States': '教皇國',
  'Kingdom of Italy (1861–1946)': '義大利王國',
  'Kingdom of Italy': '義大利王國',
  'Cisalpine Republic': '齊薩爾皮恩共和國',
  'Italian Republic (Napoleonic)': '義大利共和國（拿破崙）',
  'First French Empire': '法蘭西第一帝國',
  'Second French Empire': '法蘭西第二帝國',
  'French Third Republic': '法蘭西第三共和',
  'French Fourth Republic': '法蘭西第四共和',
  'French Fifth Republic': '法蘭西第五共和',

  // === 北歐 ===
  'Kingdom of Denmark': '丹麥王國',
  'Kingdom of Norway': '挪威王國',
  'Kingdom of Sweden': '瑞典王國',
  'Swedish Empire': '瑞典帝國',
  'Calmar Union': '卡爾馬聯盟',
  'Kingdom of Iceland': '冰島王國',
  'Old Swiss Confederacy': '舊瑞士邦聯',
  'Swiss Confederation': '瑞士邦聯',

  // === 中亞蒙古 ===
  'Karakhanid Khanate': '喀喇汗國',
  'Kara-Khanid Khanate': '喀喇汗國',
  'Qara Khitai': '西遼',
  'Western Liao': '西遼',
  'Liao dynasty': '遼朝',
  'Western Xia': '西夏',
  'Jin dynasty (1115–1234)': '金朝（女真）',
  'Yuan dynasty': '元朝',
  'Northern Yuan': '北元',
  'Northern Yuan dynasty': '北元',
  'Mongol Empire': '蒙古帝國',
  'Golden Horde': '金帳汗國',
  'White Horde': '白帳汗國',
  'Blue Horde': '青帳汗國',
  'Chagatai Khanate': '察合台汗國',
  'Moghulistan': '東察合台汗國',
  'Timurid Empire': '帖木兒帝國',
  'Khanate of the Crimea': '克里米亞汗國',
  'Crimean Khanate': '克里米亞汗國',
  'Kazan Khanate': '喀山汗國',
  'Astrakhan Khanate': '阿斯特拉罕汗國',
  'Khanate of Sibir': '失必兒汗國',
  'Khanate of Kasimov': '卡西莫夫汗國',
  'Nogai Horde': '諾蓋部',
  'Oirats': '瓦剌',
  'Oirat Khanate': '瓦剌汗國',
  'Dzungar Khanate': '準噶爾汗國',
  'Zunghar Khanate': '準噶爾汗國',

  // === 中國朝代 ===
  'Shang dynasty': '商朝',
  'Zhou dynasty': '周朝',
  'Western Zhou': '西周',
  'Eastern Zhou': '東周',
  'Spring and Autumn period': '春秋',
  'Warring States period': '戰國',
  'Qin dynasty': '秦朝',
  'Western Han': '西漢',
  'Eastern Han': '東漢',
  'Xin dynasty': '新莽',
  'Three Kingdoms': '三國',
  'Cao Wei': '曹魏',
  'Shu Han': '蜀漢',
  'Eastern Wu': '東吳',
  'Jin dynasty (266–420)': '晉朝',
  'Western Jin': '西晉',
  'Eastern Jin': '東晉',
  'Sixteen Kingdoms': '十六國',
  'Southern and Northern dynasties': '南北朝',
  'Northern Wei': '北魏',
  'Eastern Wei': '東魏',
  'Western Wei': '西魏',
  'Northern Qi': '北齊',
  'Northern Zhou': '北周',
  'Liu Song dynasty': '劉宋',
  'Southern Qi': '南齊',
  'Liang dynasty': '梁朝',
  'Chen dynasty': '陳朝',
  'Sui dynasty': '隋朝',
  'Tang dynasty': '唐朝',
  'Wu Zhou': '武周',
  'Five Dynasties and Ten Kingdoms period': '五代十國',
  'Later Liang': '後梁',
  'Later Tang': '後唐',
  'Later Jin (Five Dynasties)': '後晉',
  'Later Han (Five Dynasties)': '後漢',
  'Later Zhou': '後周',
  'Song dynasty': '宋朝',
  'Northern Song': '北宋',
  'Southern Song': '南宋',
  'Ming dynasty': '明朝',
  'Southern Ming': '南明',
  'Qing dynasty': '清朝',
  'Later Jin (Manchu)': '後金',
  'Republic of China (1912–1949)': '中華民國',
  'Tibet (1912–1951)': '西藏（1912–1951）',
  'Mengjiang': '蒙疆',
  'Manchukuo': '滿洲國',

  // === 朝鮮／日本／越南 ===
  'Gojoseon': '古朝鮮',
  'Goguryeo': '高句麗',
  'Baekje': '百濟',
  'Silla': '新羅',
  'Unified Silla': '統一新羅',
  'Balhae': '渤海',
  'Later Silla': '後新羅',
  'Goryeo': '高麗',
  'Joseon': '朝鮮王朝',
  'Korean Empire': '大韓帝國',
  'Yamato': '大和',
  'Asuka period': '飛鳥時代',
  'Nara period': '奈良時代',
  'Heian period': '平安時代',
  'Kamakura shogunate': '鎌倉幕府',
  'Ashikaga shogunate': '室町幕府',
  'Muromachi period': '室町時代',
  'Tokugawa shogunate': '德川幕府',
  'Edo period': '江戶時代',
  'Empire of Japan': '大日本帝國',
  'Đại Việt': '大越',
  'Văn Lang': '文郎國',
  'Âu Lạc': '甌貉',
  'Nam Việt': '南越',
  'Nanyue': '南越',
  'Đại Cồ Việt': '大瞿越',
  'Champa': '占婆',
  'Funan': '扶南',
  'Chenla': '真臘',
  'Khmer Empire': '高棉帝國',
  'Lan Xang': '瀾滄王國',
  'Sukhothai Kingdom': '素可泰王國',
  'Ayutthaya Kingdom': '大城王朝',
  'Rattanakosin Kingdom': '曼谷王朝（拉達那哥欣）',
  'Toungoo dynasty': '東吁王朝',
  'Konbaung dynasty': '貢榜王朝',
  'Pagan Kingdom': '蒲甘王國',

  // === 東南亞海島 ===
  'Srivijaya': '室利佛逝',
  'Majapahit': '滿者伯夷',
  'Mataram Kingdom': '滿打蘭王國',
  'Sailendra dynasty': '夏連特拉王朝',
  'Sultanate of Malacca': '馬六甲蘇丹國',
  'Sultanate of Aceh': '亞齊蘇丹國',
  'Sultanate of Brunei': '汶萊蘇丹國',
  'Sultanate of Sulu': '蘇祿蘇丹國',
  'Sultanate of Mataram': '滿打蘭蘇丹國',
  'Sultanate of Demak': '德馬克蘇丹國',
  'Sultanate of Banten': '萬丹蘇丹國',
  'Maguindanao Sultanate': '馬京達瑙蘇丹國',
  'Bruneian Empire': '汶萊帝國',

  // === 非洲 ===
  'Kingdom of Aksum': '阿克蘇姆王國',
  'Aksumite Empire': '阿克蘇姆帝國',
  'Ethiopian Empire': '衣索比亞帝國',
  'Zagwe dynasty': '札格維王朝',
  'Solomonic dynasty': '所羅門王朝',
  'Kingdom of Kush': '庫施王國',
  'Kingdom of Meroë': '麥羅埃王國',
  'Kingdom of Makuria': '馬庫里亞王國',
  'Kingdom of Alodia': '阿洛迪亞王國',
  'Kingdom of Nobatia': '諾巴提亞王國',
  'Ghana Empire': '加納帝國',
  'Mali Empire': '馬利帝國',
  'Songhai Empire': '桑海帝國',
  'Bornu Empire': '博爾努帝國',
  'Kanem Empire': '卡涅姆帝國',
  'Kanem-Bornu Empire': '卡涅姆-博爾努帝國',
  'Hausa Kingdoms': '豪薩諸邦',
  'Kingdom of Kongo': '剛果王國',
  'Kingdom of Ndongo': '恩東戈王國',
  'Kingdom of Matamba': '馬坦巴王國',
  'Kingdom of Loango': '羅安戈王國',
  'Kingdom of Luba': '盧巴王國',
  'Kingdom of Lunda': '盧巴-倫達王國',
  'Lunda Empire': '倫達帝國',
  'Kingdom of Mutapa': '穆塔帕王國',
  'Mutapa Empire': '穆塔帕帝國',
  'Kingdom of Zimbabwe': '大津巴布韋王國',
  'Great Zimbabwe': '大津巴布韋',
  'Kingdom of Mapungubwe': '馬蓬古布韋王國',
  'Rozvi Empire': '羅茲維帝國',
  'Mwene Matapa': '穆韋內穆塔帕',
  'Kingdom of Zulu': '祖魯王國',
  'Zulu Kingdom': '祖魯王國',
  'Dahomey': '達荷美',
  'Kingdom of Dahomey': '達荷美王國',
  'Oyo Empire': '奧約帝國',
  'Benin Empire': '貝寧帝國',
  'Ashanti Empire': '阿散蒂帝國',
  'Buganda': '布干達',
  'Kingdom of Buganda': '布干達王國',
  'Kingdom of Rwanda': '盧安達王國',
  'Kingdom of Burundi': '蒲隆地王國',

  // === 美洲 ===
  'Inca Empire': '印加帝國',
  'Aztec Empire': '阿茲特克帝國',
  'Aztec Triple Alliance': '阿茲特克三聯盟',
  'Maya civilization': '馬雅文明',
  'Toltec Empire': '托爾特克帝國',
  'Olmec civilization': '奧爾梅克文明',
  'Zapotec civilization': '薩波特克文明',
  'Mixtec civilization': '米斯特克文明',
  'Mochica culture': '莫切文化',
  'Moche civilization': '莫切文明',
  'Chavin culture': '查文文化',
  'Chimor': '奇穆',
  'Tiwanaku Empire': '蒂瓦納庫帝國',
  'Tiwanaku': '蒂瓦納庫',
  'Wari Empire': '瓦里帝國',
  'Nazca culture': '納斯卡文化',
  'Norte Chico civilization': '小北文明',
  'Caral–Supe civilization': '卡拉爾-蘇佩文明',
  'Cultura Tarija': '塔里哈文化',
  'Mississippian culture': '密西西比文化',
  'Cahokia': '卡霍基亞',
  'Anasazi': '阿納薩齊',
  'Ancestral Puebloans': '普韋布洛先民',

  // === 太平洋 ===
  "Tu'i Tonga Empire": '東加帝國',
  'Hawaiian Kingdom': '夏威夷王國',
  'Kingdom of Hawaii': '夏威夷王國',
  'Kingdom of Tahiti': '大溪地王國',
  'Kingdom of Rarotonga': '拉羅東加王國',
  'Tongan Empire': '東加帝國',

  // === 其他重要近代 / 現代 ===
  'Confederate States of America': '美利堅聯盟國',
  'Republic of Texas': '德克薩斯共和國',
  'Republic of California': '加利福尼亞共和國',
  'Empire of Brazil': '巴西帝國',
  'Empire of Mexico': '墨西哥帝國',
  'First Mexican Empire': '第一墨西哥帝國',
  'Second Mexican Empire': '第二墨西哥帝國',
  'Soviet Union': '蘇聯',
  'Union of Soviet Socialist Republics': '蘇維埃社會主義共和國聯邦',
  'Russian Soviet Federative Socialist Republic': '俄羅斯蘇維埃聯邦社會主義共和國',
  'Russian Empire': '俄羅斯帝國',
  'Tsardom of Russia': '俄羅斯沙皇國',
  'Russian Republic': '俄羅斯共和國',
  'Russian Provisional Government': '俄羅斯臨時政府',
  'Republic of Weimar': '威瑪共和國',
  'Weimar Republic': '威瑪共和國',
  'Nazi Germany': '納粹德國',
  'German Reich': '德意志國',
  'German Empire': '德意志帝國',
  'North German Confederation': '北德意志邦聯',
  'German Confederation': '德意志邦聯',
  'Holy Roman Empire of the German Nation': '德意志民族神聖羅馬帝國',
  'Austria-Hungary': '奧匈帝國',
  'Austrian Empire': '奧地利帝國',
  'Kingdom of Yugoslavia': '南斯拉夫王國',
  'Yugoslavia': '南斯拉夫',
  'Socialist Federal Republic of Yugoslavia': '南斯拉夫社會主義聯邦共和國',
  'Czechoslovakia': '捷克斯洛伐克',
  'East Germany': '東德',
  'West Germany': '西德',
  'German Democratic Republic': '德意志民主共和國',
  'Federal Republic of Germany': '德意志聯邦共和國',

  // === 第二批：古典／中世紀小國 ===
  'Seha River Land': '塞哈河地（赫梯西部）',
  'Kolathunadu': '科拉杜納度',
  'Marion': '馬里翁',
  'Rhodes': '羅得島',
  'Rajouli': '拉卓里',
  'Scythia Minor (Crimea)': '小斯基泰（克里米亞）',
  'Hasmonean Judea': '哈斯蒙尼猶大',
  'Caucasian Albania': '高加索阿爾巴尼亞',
  "Kingdom K'antu": '坎圖王國',
  'Caucasian Albania (Sasanian province)': '高加索阿爾巴尼亞（薩珊省）',

  // === 愛爾蘭／威爾士古王國 ===
  'Airgíalla': '艾爾吉亞拉（愛爾蘭）',
  'Tyrconnell': '蒂爾康奈爾（愛爾蘭）',
  'Dogfeiling': '多格菲林（威爾士）',
  'Dunoding': '杜諾丁（威爾士）',
  'Dál nAraidi': '達爾納拉迪（愛爾蘭）',
  'Ailech': '艾立赫（愛爾蘭）',
  'East Breifne': '東布雷夫尼（愛爾蘭）',
  'West Breifne': '西布雷夫尼（愛爾蘭）',
  'Powys Fadog': '法多格波伊斯（威爾士）',
  'Powys Wenwynwyn': '文文溫波伊斯（威爾士）',
  'Bromfield and Yale': '布羅菲爾德與耶爾（威爾士）',
  'Kingdom of Strathclyde': '斯特拉斯克萊德王國',
  'Kingdom of Dál Riata': '達爾里亞達王國',

  // === 中世紀歐洲小國 ===
  'Burgundy': '勃艮第',
  'Verdun': '凡爾登',
  'Lotharingia': '洛塔林吉亞',
  'Pagania': '帕加尼亞',
  'Tournaisis': '圖爾奈',
  'Travunia': '特拉武尼亞',
  'Normannia': '諾曼第（諾爾曼尼亞）',
  'Donji Kraji': '頓伊克拉伊（波士尼亞）',
  'March of Milan': '米蘭邊區',
  'Counts of Berga': '貝爾加伯爵',
  'Tmutarakan Rus': '特穆塔拉坎羅斯',
  'Bethio': '貝蒂歐',
  'Montsoreau': '蒙索羅',
  'Umri': '烏姆里',
  'Viscounty of Léon': '萊昂子爵領',
  'Porhoët': '波奧埃（布列塔尼）',
  'County Pyrmont': '皮爾蒙特伯國',
  'Herrschaft Homburg': '洪堡領主國',
  'Ban de la Roche': '羅赫的班國',
  'Comune of Bologna': '波隆那城邦',
  'Riviera di San Giulio': '聖朱利奧河岸',
  'Federation of the Seven Communities': '七市聯盟',
  'Gengenbach Abbey': '根根巴赫修道院',
  'United Kingdom of Poland': '波蘭聯合王國',
  'Lands of the Bohemian Crown (1348–1526)': '波西米亞王冠領地（1348–1526）',
  'Palatinate of Rhine': '萊茵-普法爾茨選帝侯國',
  'Crown of Majorca': '馬約卡王冠',
  'An der Etsch': '阿迪傑河岸',
  'Free Imperial Knights': '帝國騎士團',
  'Knights Hospitaller': '醫院騎士團',
  'Sovereign Military Order of Malta': '馬爾他騎士團',
  'Nassau-Hadamar': '拿騷-哈達馬爾',
  'Nassau-Sonnenberg': '拿騷-松能堡',
  'Saxe-Coburg-Eisenach': '薩克森-科堡-艾森納赫',
  'Saxe-Marksuhl': '薩克森-馬克蘇爾',
  'Stolberg-Rossla': '施托爾貝格-羅斯拉',
  'Isenburg-Wächtersbach': '伊森堡-韋希特斯巴赫',
  'Hesse-Kassel': '黑森-卡塞爾',
  'Hesse-Darmstadt': '黑森-達姆施塔特',
  'Hanover': '漢諾威',
  'Electorate of Hanover': '漢諾威選帝侯國',
  'Electorate of Saxony': '薩克森選帝侯國',
  'Electorate of Brandenburg': '布蘭登堡選帝侯國',
  'Electorate of Bavaria': '巴伐利亞選帝侯國',
  'Electorate of the Palatinate': '普法爾茨選帝侯國',
  'Electorate of Trier': '特里爾選帝侯國',
  'Electorate of Cologne': '科隆選帝侯國',
  'Electorate of Mainz': '美因茲選帝侯國',
  'Albertine Duchy of Saxony (1485-1547)': '阿爾貝廷薩克森公國',
  'Calvinist Republic of Ghent': '根特喀爾文共和國',
  'Stad en Lande': '城市與土地（荷蘭）',
  'Staats-Brabant': '荷蘭布拉班特',
  'République des Sept-Dizains': '七鄉共和國',
  'Tribal Duchy of Bavaria': '部落巴伐利亞公國',
  'Old Saxony': '古撒克遜',

  // === 印度王公邦（轉寫）===
  'Mallabhum': '馬拉布姆',
  'Canasapura': '迦那薩普羅',
  'Diarra': '迪亞拉',
  'Jasrota': '賈斯羅塔',
  'Patan State, Rajasthan': '帕坦邦（拉賈斯坦）',
  'Torawati': '托拉瓦蒂',
  'Kampili': '坎皮利',
  'Zainabad': '扎依納巴德',
  'Chamba State': '昌巴邦',
  'Suket State': '蘇凱特邦',
  'Mewar': '梅瓦爾',
  'Marwar': '馬爾瓦',
  'Mukhrani': '穆赫拉尼（喬治亞）',
  'Varman dynasty of Kannauj': '瓦爾曼王朝（卡瑙季）',
  'Nalagarh': '納拉加爾',
  'Zamfara': '扎姆法拉',
  'Darkoti': '達爾科蒂',
  'Buhaya': '布哈雅',
  'Damot': '達莫特',
  'Dharmasraya': '達摩室羅耶',
  'Hkamti Long': '坎提朗（緬甸）',
  'Kazakh sultanate': '哈薩克蘇丹國',
  'Sambalpur District': '桑巴爾普爾',
  'Daspalla': '達斯帕拉',
  'Bhurshut': '布爾舒特',
  'Kotharia State, Rajasthan': '科塔里亞邦（拉賈斯坦）',
  'Kotharia State, Rajkot': '科塔里亞邦（拉吉科特）',
  'Vallabhi': '伐臘毗',
  'Kapshi Estate': '卡普希',
  'Lawa Thikana': '拉瓦塔卡納',
  'Sardargarh Bantva': '薩達加爾班特瓦',
  'Kurundvad Junior': '小庫倫達瓦',
  'Kurundvad Senior': '大庫倫達瓦',
  'Manda (zamindari)': '曼達札敏達里',
  'Daewiguk': '大為國',
  'Achrol': '阿赫羅爾',
  'Kuthar': '庫塔爾',
  'Datarpur': '達塔爾普爾',
  'Koriya': '科里亞',
  'Dhurwai': '杜爾瓦伊',
  'Hasht-Bhaiya': '哈什特巴亞',
  'Tori Fatehpur': '托里法特赫普爾',
  'Panarwa thikana': '帕納爾瓦塔卡納',
  'Rajoli Zamindari Estate': '拉卓里札敏達里',
  'Jeypore Estate': '傑普爾領地',
  'Kangra-Lambagraon': '康格拉-蘭巴格拉翁',
  'Barwani State': '巴爾瓦尼邦',

  // === 中東伊斯蘭朝代 ===
  'Tulunid Emirate of Egypt': '圖倫尼德埃及酋長國',
  'Hamdanid emirate of Aleppo': '哈姆達尼阿勒坡酋長國',
  'Mirdasid emirate of Aleppo': '米爾達斯阿勒坡酋長國',
  'Munqidhite emirate of Shaizar': '蒙基迪沙伊扎酋長國',
  'Uyunid Emirate': '烏雲尼德酋長國',
  'Seljuk State of Syria': '敘利亞塞爾柱',
  'Ayyubid Sultanate of Egypt': '阿尤布埃及蘇丹國',
  'Mount Lebanon Emirate': '黎巴嫩山酋長國',
  'Bani Khalid Emirate': '哈立德酋長國',
  'Bani Khalid': '哈立德部',
  'Banu Masala': '馬薩拉部',
  'Banu Khazrun': '哈茲倫部',
  'The Emirate of Zubarah': '祖巴拉酋長國',
  'Buraydah Emirate': '布賴達酋長國',
  'Unaizah Emirate': '昂奈札酋長國',
  'Bida Emirate': '比達酋長國',
  'Armenian Principality of Cilicia': '奇里乞亞亞美尼亞親王國',

  // === 北高加索 / 中亞 ===
  'Kaitag Utsmiate': '卡伊塔格烏斯米國',
  'Kazikumukh Shamkhalate': '卡濟庫穆赫沙姆哈爾國',
  'Kurakh Union': '庫拉赫聯盟',
  'Chirkland': '奇爾克蘭',
  'Vardan Khudahs': '瓦爾丹胡達赫',
  'North Caucasian Huns': '北高加索匈人',
  'Khongoray': '洪戈雷',
  'Shamshadil': '沙姆沙迪爾',
  'Shoragel sultanate': '紹拉格爾蘇丹國',
  'First Kingdom of Kakheti': '第一卡赫季王國',
  'Tagmadert': '塔格瑪德爾特',
  'Arzen': '阿爾澤恩',
  'Zvečan Fortress': '茨韋強堡',
  'Realm of Stefan Dragutin': '斯特凡德拉古汀王國',
  'Domain of the Dejanović noble family': '德楊諾維奇家族領地',

  // === 中國／東亞分裂時期 ===
  'Zheng': '鄭（春秋）',
  'Song': '宋（同名）',
  'Muyun': '慕容',
  'Holotan': '訶羅單',
  'Datianxing': '大田興',
  'Songhua': '松花',
  'Imperial Court of Japan': '日本朝廷',
  'Japan during the Rekkan Politics period': '日本攝關時期',
  'Japan during the Insei period': '日本院政時期',
  'old Pahang kingdom': '古彭亨王國',
  'Naning': '那寧',
  'Kingdom Saal': '薩爾王國',
  'Pachan kingdom': '帕昌王國',
  "Kingdom Tzu'": '茲烏王國',
  'Pangasinan (historical polity)': '邦阿西楠（歷史政體）',
  'Maona of Chios and Phocaea': '希俄斯與福西亞馬奧那',
  'Beylik of Tanrıbermiş': '坦里貝爾米什貝伊國',
  'Beylik of Berçemeoğulları': '貝爾切梅奧盧貝伊國',
  'Beylik of Sinop': '錫諾普貝伊國',
  'Beylik of Dobruja': '多布魯加貝伊國',
  'Beylik of Osman': '奧斯曼貝伊國',
  'Beylik of Kadi Burhan al-Din': '卡迪布爾漢丁貝伊國',
  'Kutlushahs': '庫圖盧沙赫',

  // === 西非 / 非洲 ===
  'Diarra': '迪亞拉',
  'Kaabu': '卡布',
  'Bundu': '邦杜',
  'Khasso': '卡索',
  'Mosquitia': '蚊子海岸',
  'Mosquito Coast': '蚊子海岸',
  'Tasik': '塔西克',
  'Mbwila': '姆布維拉',
  'Ngoyo': '恩戈約',
  'Nupe': '努佩',
  'Bailundu': '巴依倫杜',
  'Viye': '維耶',
  'Taqali': '塔卡利',
  'Uukwaluudhi': '烏夸盧迪',
  'Uukwanyama': '烏夸尼亞馬',
  'Dar Qimr': '達爾基姆爾',
  'Cokossi': '科科西',
  'Kombo': '康博',
  'Great Ardra': '大阿德拉',
  'Amarasi': '阿馬拉西',
  'Skewbald Horde': '雜色帳',
  'Saxe-Marksuhl': '薩克森-馬克蘇爾',

  // === 拉美 / 美洲早期 ===
  'Mosquito Coast': '蚊子海岸',
  'State of Brazil': '巴西邦',
  'State of Maranhão': '馬拉尼昂邦',
  'Portuguese Cochin': '葡屬科欽',
  'Dutch Loango-Angola': '荷屬羅安戈-安哥拉',
  'Spanish protectorate in Cambodia': '西班牙柬埔寨保護地',
  'French colonial empire': '法蘭西殖民帝國',
  'Brandenburg colonial empire': '布蘭登堡殖民帝國',
  'Rugiland': '魯吉蘭德（古日耳曼）',
  'Ringerike': '林格里克（挪威）',
  'Roman Libya': '羅馬利比亞',
  'Great Moravia': '大摩拉維亞',
  'Hkamti Long': '坎提朗',
  'Kingdom of Yorùbá': '約魯巴王國',
  'Yorubaland': '約魯巴蘭',
  'Cultura Tarija': '塔里哈文化',
  'Land': '蘭德',
  'ʻThr': '塞爾',
  'Cultura La Tolita': '拉托利塔文化',
  'Serbian Empire of Jovan Nenad': '約萬·涅納德塞爾維亞帝國',
  'Royal Lordship of Molina': '莫利納王領',
  'Despotate of Lovech': '洛維奇專制國',
  'Despotate of Angelokastron and Lepanto': '安傑洛卡斯特隆與勒班陀專制國',
  'Despotate of Arta': '阿爾塔專制國',
  'Despotate of the Morea': '摩里亞專制國',
  'Despotate of Epirus': '伊庇魯斯專制國',
  'Banate of Macsó': '馬奇瓦班國',
  'Banate of Bosnia': '波士尼亞班國',
  'principality of Kholm': '霍爾姆親王國',
  'Grand Principality of Perm': '彼爾姆大親王國',
  'Khanate of the Crimea': '克里米亞汗國',
  'Kingdom of Hejaz': '漢志王國',
  'Kingdom of Iraq': '伊拉克王國',
  'Kingdom of Egypt': '埃及王國',
  'Kingdom of Libya': '利比亞王國',
  'Kingdom of Greece': '希臘王國',
  'Kingdom of Yugoslavia': '南斯拉夫王國',
  'Kingdom of Romania': '羅馬尼亞王國',
  'Kingdom of Bulgaria': '保加利亞王國',
  'Kingdom of Albania': '阿爾巴尼亞王國',
  'Kingdom of Romania (1881–1947)': '羅馬尼亞王國',
  'Upper Austria': '上奧地利',
  'Lower Austria': '下奧地利',
  'Livonian confederation': '立窩尼亞邦聯',
  'Livonian Confederation': '立窩尼亞邦聯',
  'Teutonic Order': '條頓騎士團',
  'Livonian Order': '立窩尼亞騎士團',
  'Sword Brothers': '寶劍兄弟騎士團',

  // === 其他 ===
  'Sultanate of Egypt': '埃及蘇丹國',
  'Sultanate of Iconium': '羅姆蘇丹國（伊科尼烏姆）',
  'Sultanate of Granada': '格拉納達蘇丹國',
  'Nasrid Kingdom of Granada': '格拉納達奈斯爾王國',
  'Caliphate of Cordoba': '科爾多瓦哈里發',
  'Almoravid Empire': '阿穆瓦希德帝國',
  'Almohad Caliphate': '阿穆瓦希丁哈里發',
  'Marinid Sultanate': '馬林蘇丹國',
  'Saadi Sultanate': '薩阿德蘇丹國',
  'Wattasid Sultanate': '瓦塔斯蘇丹國',
  'Volga Bulgaria': '伏爾加保加利亞',
  'First Bulgarian Empire': '第一保加利亞帝國',
  'Second Bulgarian Empire': '第二保加利亞帝國',
  'Bosnian Banate': '波士尼亞班國',
  'Kingdom of Galicia–Volhynia': '加利西亞-沃里尼亞王國',
  'Galicia–Volhynia': '加利西亞-沃里尼亞',
  'Principality of Galicia': '加利西亞親王國',
  'Principality of Volhynia': '沃里尼亞親王國',
  'Principality of Kiev': '基輔親王國',
  'Principality of Novgorod': '諾夫哥羅德親王國',
  'Principality of Polotsk': '波羅茨克親王國',
  'Principality of Vladimir-Suzdal': '弗拉基米爾-蘇茲達爾親王國',
  'Vladimir-Suzdal': '弗拉基米爾-蘇茲達爾',
  'Khanate of Kazan': '喀山汗國',
  'Khanate of Astrakhan': '阿斯特拉罕汗國',
  'Bukharan Khanate': '布哈拉汗國',
  'Emirate of Bukhara': '布哈拉酋長國',
  'Emirate of Afghanistan': '阿富汗酋長國',
  'Kingdom of Afghanistan': '阿富汗王國',
  'Kingdom of Iran': '伊朗王國',
  'Imperial State of Iran': '伊朗帝國',
  'Sublime State of Iran': '伊朗崇高國',
  'Khedivate of Egypt': '埃及赫迪夫國',
  'Kingdom of Egypt and Sudan': '埃及與蘇丹王國',
  'Egypt Eyalet': '埃及艾雅勒',
  'Tunis Eyalet': '突尼斯艾雅勒',
  'Eyalet of Bosnia': '波士尼亞艾雅勒',
  'Eyalet of Egypt': '埃及艾雅勒',
  'Beylik of Tunis': '突尼斯貝伊國',
  'Beylik of Algiers': '阿爾及爾貝伊國',

  // === 第三批：剩餘小邦轉寫 ===
  'Taifa Tudela': '圖德拉泰法王國',
  'Barony of Castalla': '卡斯塔利亞男爵領',
  'Count of San Secondo': '聖塞孔多伯爵',
  'Menceyato of Anaga': '阿納加門塞亞托（加那利）',
  'Badis': '巴迪斯（摩洛哥）',
  'Fugger': '富格爾家族',
  'Baban': '巴班（庫德）',
  'Kartosuro': '卡爾托蘇羅',
  'Republic „Otto Luoghi"': '八地共和國',
  'Afsharid Iran': '阿夫沙爾伊朗',
  'Limbda': '林布達',
  'Bansda': '班斯達',
  'Bahrain and its Dependencies': '巴林及其屬地',
  'Banda': '班達',
  'Changbhakar': '昌巴卡爾',
  'Yauri Emirate': '亞烏里酋長國',
  'Akora': '阿科拉',
  'Al-Busi': '布西',
  'Bang Assu': '邦阿蘇',
  'Kengcheng': '景棟',
  'Batavian Commonwealth': '巴達維亞聯邦',
  'Batavian Republic': '巴達維亞共和國',
  'Electorate of Hesse': '黑森選帝侯國',
  'Salm-Horstmar': '薩爾姆-霍斯特馬爾',
  'Pataudi': '帕陶迪',
  'Principality Isenburg': '伊森堡親王國',
  'Free and Independent State of Cundinamarca': '昆迪納馬卡自由獨立邦',
  'Rewa Kantha Agency': '雷瓦坎塔特派區',
  'Bhaisunda': '拜松達',
  'Chaube Jagirs': '昌貝賈吉爾領地',
  'Kamta-Rajaula': '坎塔-拉約拉',
  'Pahra': '帕拉',
  'Free State of Antioquia': '安蒂奧基亞自由邦',
  'Dhami (state)': '達米邦',
  'Palanpur Agency': '巴蘭普爾特派區',
  'Second Bani Khalid Emirate': '第二哈立德酋長國',
  'Miraj Junior': '小米拉吉',
  'Miraj Senior': '大米拉吉',
  'Chota Nagpur States': '小那格普爾諸邦',
  'Military-Political System of Samos': '薩摩斯軍政體系',
  'Protectorate of San Martín': '聖馬丁保護國',
  'Pre-Colonial Basutoland': '前殖民巴蘇陀蘭',
  'United Provinces of Central America': '中美洲聯合省',
  'Duchy Saxony-Gotha': '薩克森-哥達公國',
  'Saxe-Gotha': '薩克森-哥達',
  'Saxe-Weimar': '薩克森-威瑪',
  'Saxe-Eisenach': '薩克森-艾森納赫',
  'Saxe-Meiningen': '薩克森-邁寧根',
  'Saxe-Altenburg': '薩克森-阿爾滕堡',
  'Saxe-Hildburghausen': '薩克森-希爾德堡豪森',
  'Saxe-Coburg-Gotha': '薩克森-科堡-哥達',
  'Phulra': '富爾拉',
  'Dar al Kuti': '達爾庫提',
  'Wahidi Azzan': '瓦希迪阿茲贊',
  'Wahidi Bir Ali': '瓦希迪比爾阿里',
  'Estado Libre del Istmo': '地峽自由邦',
  'Möng Leng': '勐冷',
  'Canada East': '加拿大東部',
  'Canada West': '加拿大西部',
  'First Republic (Dominican Republic)': '第一共和國（多明尼加）',
  'Provisional government of Lombardy': '倫巴底臨時政府',
  'Chan Santa Cruz': '聖十字克魯斯',
  'Alabama in the American Civil War': '阿拉巴馬（南北戰爭時期）',
  'Free State of Jones': '瓊斯自由邦',
  'Fuladu': '富拉杜',
  'Angadh Estate': '安加德領地',
  'Emirat de Gazni': '加茲尼酋長國',
  'United States of Stellaland': '斯特拉蘭合眾國',
  'Orissa Tributary States': '奧里薩附庸邦',
  'Confederation of Sedang': '塞當聯盟',
  'United States of Central America': '中美洲合眾國',
  'Nazargunj': '納扎爾岡吉',
  'Dedhrota': '德德羅塔',
  'Gordonia': '戈多尼亞',
  'Sheikhdom of al-Hawra': '哈拉酋長國',
  'Sheikhdom of al-ʽIrqa': '伊爾卡酋長國',
  'Islamic government of Laristan': '拉里斯坦伊斯蘭政府',
  'Union of South Africa': '南非聯邦',
  'Sheikdom of Upper Asir': '上阿西爾酋長國',
  'National-cultural autonomy of Muslim Turko-Tatars Inner Russia and Siberia': '內俄羅斯與西伯利亞穆斯林突厥-韃靼民族文化自治',
  'Soi︠u︡z obʺedinennykh gort︠s︡ev Gorskai︠a︡ Respublika': '北高加索山民聯盟共和國',
  'South-Eastern Union': '東南聯盟',
  'Centrocaspian Dictatorship': '中央裏海獨裁政府',
  'First Republic of Pińczów': '第一平丘夫共和國',
  'Free State of Saxe-Gotha': '薩克森-哥達自由邦',
  'Interwar Latvia': '兩戰間拉脫維亞',
  'Second Crimean Regional Government': '第二克里米亞地區政府',
  'Socialist Republic of Germany': '德意志社會主義共和國',
  "Worker's Socialist Respublic of Amur": '阿穆爾工人社會主義共和國',

  // === 拾遺 ===
  "Tu'i Tonga Empire": '東加帝國',
  "Tu'i Manuʻa": '圖伊馬努阿',
  'Free imperial city of Mühlhausen': '米爾豪森帝國自由市',
  'Free imperial city of Hamburg': '漢堡帝國自由市',
  'Free imperial city of Dortmund': '多特蒙德帝國自由市',
  'free imperial city of Strasbourg': '斯特拉斯堡帝國自由市',
  'Imperial City of Regensburg': '雷根斯堡帝國城市',
  'Imperial City of Windsheim': '溫德斯海姆帝國城市',
  'Imperial City of Schweinfurt': '施韋因富特帝國城市',
  'Imperial City of Rothenburg': '羅滕堡帝國城市',
  'free imperial city of Lindau': '林道帝國自由市',
  'free imperial city of Weil der Stadt': '魏爾斯塔特帝國自由市',
  'Free imperial city of Ravensburg': '拉芬斯堡帝國自由市',
  'free imperial city of Kaufbeuren': '考夫博伊倫帝國自由市',
  'Imperial City of Dinkelsbühl': '丁克爾斯比爾帝國城市',
  'free imperial city of Rottweil': '羅特韋爾帝國自由市',
  'free imperial city of St. Gallen': '聖加侖帝國自由市',
  'free imperial city of Friedberg': '弗里德貝格帝國自由市',
  'free imperial city of Turckheim': '蒂爾克海姆帝國自由市',
  'free imperial city of Gengenbach': '根根巴赫帝國自由市',
  'Imperial Abbey of Wissembourg': '維森堡帝國修道院',
  'Roman Catholic Diocese of Verden': '韋爾登天主教教區',
  'Prince-Bishopric of Speyer': '施派爾親王主教區',
  'Prince-Bishopric of Meissen': '邁森親王主教區',
  'Prince-Bishopric of Strasbourg': '斯特拉斯堡親王主教區',
  'Prince-Bishopric of Lausanne': '洛桑親王主教區',
  'Prince-Bishopric of Geneva': '日內瓦親王主教區',
  'Prince-Bishopric of Chur': '庫爾親王主教區',
  'Prince-Bishopric of Passau': '帕紹親王主教區',
  'Margraviate Hachberg-Sausenberg': '哈赫貝格-紹森貝格邊伯國',
  'Marquisate of Millesimo': '米萊西莫侯爵領',
  'Marquisate of Zuccarello': '祖卡雷洛侯爵領',
  'Marquisate of Scandiano': '斯坎迪亞諾侯爵領',
  'Marquisate of Zibello': '齊貝洛侯爵領',
  'Marquisate of Oristano': '奧里斯塔諾侯爵領',
  'countship of Scandiano': '斯坎迪亞諾伯國',
  'county of Lantarón': '蘭塔隆伯國',
  'county of Nordgau': '諾爾德高伯國',
  'county of Buren': '布倫伯國',
  'lordship of Caymont': '凱蒙領主國',
  'lordship of Lichtenberg': '利希滕貝格領主國',
  'lordship of Échéry': '埃舍里領主國',
  'Signoria of Milan': '米蘭領主國',
  'Signoria of Verona': '維羅納領主國',
  'Signoria of Volterra': '沃爾泰拉領主國',
  'Signoria di Correggio': '科雷焦領主國',
  'Signoria di Carrara': '卡拉拉領主國',
  'taifa of Algeciras and Ronda': '阿爾赫西拉斯與隆達泰法',
  'Taifa of Constantina and Hornachuelos': '科斯坦提那與奧爾納丘埃洛斯泰法',
  'Taifa of Saltés and Huelva': '薩爾特斯與烏埃爾瓦泰法',

  // === 第四批：20 世紀短命國／殖民地過渡實體 ===
  'Yakutia': '雅庫特',
  'Free State Bottleneck': '瓶頸自由邦',
  'Freistaat Schwenten': '施文騰自由邦',
  'Regional Government of Northwest Russia': '俄羅斯西北地區政府',
  'Alawite Territory': '阿拉維領地',
  'Independent State of Raqqa': '拉卡獨立國',
  'Socialist Soviet Republic of Armenia': '亞美尼亞蘇維埃社會主義共和國',
  'Socialist Soviet Republic of Georgia': '喬治亞蘇維埃社會主義共和國',
  'Lebanese Republic under French mandate': '法屬黎巴嫩共和國',
  'Syrian Republic under French mandate': '法屬敘利亞共和國',
  'Federal State of Austria': '奧地利聯邦邦',
  'Trust Territory of Nauru': '諾魯託管地',
  'Union of Burma (1948–1962)': '緬甸聯邦（1948–1962）',
  'South Vietnam': '南越',
  'North Vietnam': '北越',
  "People's Revolutionary Republic of Guinea": '幾內亞人民革命共和國',
  'Commonwealth realm of Tanganyika': '坦干伊喀英聯邦領',
  'Zaire': '薩伊',
  "Democratic People's Republic of Angola": '安哥拉人民民主共和國',
  'Federal Islamic Republic of the Comoros': '葛摩聯邦伊斯蘭共和國',
  'Community of Municipalities of Northern Dalmatia and Lika': '北達爾馬提亞與利卡市政共同體',
  'Kurdish Republic of Lachin': '拉欽庫德共和國',
  'Republika Srpska': '塞族共和國',
  'Kherson Oblast': '赫爾松州',
  'Zaporozhye Oblast': '札波羅熱州',
  'Territory of the Rapid Support Forces': '快速支援部隊轄區',
  'Aachener Reich': '亞琛帝國',

  // === 第四批：古代與中世紀小邦 ===
  'Abasgia': '阿巴斯吉亞',
  'Adansi': '阿丹西（迦納）',
  'Adzele': '阿茲萊（拉脫維亞）',
  'Agisymba': '阿吉辛巴',
  'Ahirwal': '阿希爾瓦爾',
  'Alampur': '阿蘭普爾',
  'Álfheimr': '阿爾夫海姆（北歐神話）',
  'Amoronkay': '阿莫龍凱',
  'Aram Rehob': '亞蘭利合',
  'Arewa': '阿雷瓦',
  'Ashkenaz': '阿什肯納茲',
  'Austrian Swabia': '奧屬士瓦本',
  'Bahdinan': '巴赫迪南（庫德）',
  'Banu Kathir': '卡蒂爾部',
  'Bīt-Purutaš': '比特普魯塔什',

  // === 印度王公邦（多為小邦轉寫）===
  'Babariawad': '巴巴里阿瓦德',
  'Badu': '巴杜',
  'Bafut Subdivision': '巴富特區（喀麥隆）',
  'Bakhatgarh': '巴赫加爾',
  'Banate': '班納特',
  'Barpali': '巴爾帕利',
  'Bentan': '本坦',
  'Bezaume': '貝佐姆',
  'Bhalala': '巴拉拉',
  'Bhandaria': '班達里亞',
  'Bharejda': '巴雷季達',
  'Bhayavadar': '巴亞瓦達爾',
  'Bhojavadar': '博賈瓦達爾',
  'Bidiga': '比迪加',
  'Boomi Sengkalan': '布米僧加蘭',
  'Bourbonnais': '波旁奈',
  'Brunei sultanate': '汶萊蘇丹國',
  'Caillè': '凱耶',
  'Cardo Pomarroso': '波馬羅索的卡多',
  'Cesna': '切斯納',
  'Chamlong': '查姆隆',
  'Charm Khel': '查爾姆赫爾',
  'Chitor': '奇托',
  'Chitorgarh': '奇托加爾',
  'Choghol': '喬戈爾',
  'Choka': '喬卡',
  'Chum': '楚姆',
  'Country of Wisbeche': '威斯比奇地',
  'Coxhead': '考克斯黑德',
  'Dehir-Wagam': '德希爾瓦甘',
  'Devalpur': '德瓦爾普爾',
  'Dhrol': '德羅爾',
  'Dom Pedrito': '東佩德里托',
  'Dramburg': '德蘭堡',
  'Eastern Liang': '東涼',
  'Eikenrod': '艾肯羅德',
  'Ekvera': '埃克韋拉',
  'Elimea': '埃利美亞',

  // === 北歐 / 中歐零散 ===
  'Estado Novo (Portugal)': '葡萄牙新國',
  'Estado Novo (Brazil)': '巴西新國',
  'Estado Português da Índia': '葡屬印度',
  'Eswatini': '史瓦帝尼',
  'Ottoman Tripolitania': '奧斯曼的黎波里塔尼亞',
  'Spanish Sahara': '西屬撒哈拉',
  'Italian Eritrea': '義屬厄利垂亞',
  'Italian Somaliland': '義屬索馬利亞',
  'Italian Libya': '義屬利比亞',
  'Italian East Africa': '義屬東非',
  'French Tunisia': '法屬突尼斯',
  'French Algeria': '法屬阿爾及利亞',
  'French Morocco': '法屬摩洛哥',
  'French Madagascar': '法屬馬達加斯加',
  'French Indochina': '法屬印度支那',
  'French West Africa': '法屬西非',
  'French Equatorial Africa': '法屬赤道非洲',
  'French Polynesia': '法屬玻里尼西亞',
  'French Mandate of Syria and Lebanon': '法屬敘黎委任統治',
  'British Mandate of Palestine': '英屬巴勒斯坦委任統治',
  'British India': '英屬印度',
  'British Raj': '英屬印度（拉吉）',
  'British Malaya': '英屬馬來亞',
  'British Burma': '英屬緬甸',
  'British Honduras': '英屬宏都拉斯',
  'British Cameroons': '英屬喀麥隆',
  'British East Africa': '英屬東非',
  'British Somaliland': '英屬索馬利蘭',
  'British Hong Kong': '英屬香港',
  'British Ceylon': '英屬錫蘭',
  'Dutch East Indies': '荷屬東印度',
  'Dutch West Indies': '荷屬西印度',
  'Dutch Brazil': '荷屬巴西',
  'Dutch Ceylon': '荷屬錫蘭',
  'Dutch Formosa': '荷屬福爾摩沙',
  'Dutch Gold Coast': '荷屬黃金海岸',
  'Belgian Congo': '比屬剛果',
  'Belgian Mandate of Ruanda-Urundi': '比屬盧安達-烏隆地',
  'Portuguese Mozambique': '葡屬莫三比克',
  'Portuguese Angola': '葡屬安哥拉',
  'Portuguese Macau': '葡屬澳門',
  'Portuguese Timor': '葡屬帝汶',
  'Portuguese Goa': '葡屬果阿',
  'Portuguese Empire': '葡萄牙帝國',
  'Spanish Empire': '西班牙帝國',
  'Spanish East Indies': '西屬東印度',
  'Spanish Florida': '西屬佛羅里達',
  'Spanish Louisiana': '西屬路易斯安那',
  'Spanish Netherlands': '西屬尼德蘭',
  'Spanish Cuba': '西屬古巴',
  'Spanish Guinea': '西屬幾內亞',
  'Spanish Philippines': '西屬菲律賓',
  'Habsburg Spain': '哈布斯堡西班牙',
  'Habsburg Netherlands': '哈布斯堡尼德蘭',

  // === 革命 / 短命邦 ===
  'Soviet Hungary': '蘇維埃匈牙利',
  'Hungarian Soviet Republic': '匈牙利蘇維埃共和國',
  'Bavarian Soviet Republic': '巴伐利亞蘇維埃共和國',
  'Slovak Soviet Republic': '斯洛伐克蘇維埃共和國',
  'Free Territory of Trieste': '的里雅斯特自由區',
  'Saar Protectorate': '薩爾保護國',
  'Western Sahara': '西撒哈拉',
  'Sahrawi Arab Democratic Republic': '撒哈拉阿拉伯民主共和國',
  'Wallachia': '瓦拉幾亞',
  'Moldavia': '摩爾達維亞',
  'Transylvania': '外西凡尼亞',
  'United Principalities of Moldavia and Wallachia': '羅馬尼亞聯合公國',
  'Kingdom of Romania (1881–1947)': '羅馬尼亞王國',
  'Tsardom of Bulgaria': '保加利亞沙皇國',

  // === Cushitic / 衣索比亞 / 索馬里 ===
  'Adal Sultanate': '阿達爾蘇丹國',
  'Sultanate of Ifat': '伊法特蘇丹國',
  'Sultanate of Showa': '紹瓦蘇丹國',
  'Sultanate of Mogadishu': '摩加迪沙蘇丹國',
  'Ajuran Sultanate': '阿瑞蘭蘇丹國',
  'Geledi Sultanate': '格萊迪蘇丹國',
  'Majeerteen Sultanate': '馬吉爾廷蘇丹國',
  'Sultanate of Hobyo': '霍比奧蘇丹國',
  'Warsangali Sultanate': '瓦桑加里蘇丹國',
  'Yejju dynasty': '葉朱王朝',
  'Damot': '達莫特',
  'Kingdom of Damot': '達莫特王國',
  'Kingdom of Shewa': '紹瓦王國',
  'Kingdom of Gondar': '貢德爾王國',
  'Kingdom of Gojjam': '戈賈姆王國',
  'Welayta Kingdom': '瓦萊塔王國',
  'Kaffa Kingdom': '卡法王國',
  'Janjero': '詹傑羅',
  'Hadiya Sultanate': '哈迪亞蘇丹國',
  'Bali Sultanate': '巴利蘇丹國',
}

// ===== 規則翻譯 =====
const SUFFIX_DICT = {
  ' Kingdom': '王國',
  ' kingdom': '王國',
  ' Empire': '帝國',
  ' Khanate': '汗國',
  ' Caliphate': '哈里發',
  ' Sultanate': '蘇丹國',
  ' Republic': '共和國',
  ' Confederacy': '邦聯',
  ' Confederation': '邦聯',
  ' Federation': '聯邦',
  ' dynasty': '王朝',
  ' Dynasty': '王朝',
  ' Civilization': '文明',
  ' civilization': '文明',
  ' Culture': '文化',
  ' culture': '文化',
  ' League': '同盟',
  ' State': '邦',          // 印度王公邦 etc.
  ' state': '邦',
  ' Principality': '親王國',
  ' principality': '親王國',
  ' Province': '行省',
  ' province': '行省',
  ' County': '伯國',
  ' Duchy': '公國',
  ' Tsardom': '沙皇國',
  ' Shogunate': '幕府',
  ' shogunate': '幕府',
  ' Imamate': '伊瑪目國',
  ' imamate': '伊瑪目國',
  ' Voivodeship': '伏伊伏丁那',
  ' Banate': '班國',
  ' banate': '班國',
  ' Despotate': '專制國',
  ' despotate': '專制國',
  ' Patriarchate': '宗主教區',
  ' Lordship': '領主國',
  ' lordship': '領主國',
  ' Margraviate': '邊伯國',
  ' Landgraviate': '方伯國',
  ' Archduchy': '大公國',
  ' archduchy': '大公國',
  ' Grand Duchy': '大公國',
}

const PREFIX_DICT = {
  'Kingdom of ': { suffix: '王國' },
  'kingdom of ': { suffix: '王國' },
  'Empire of ': { suffix: '帝國' },
  'empire of ': { suffix: '帝國' },
  'Duchy of ': { suffix: '公國' },
  'duchy of ': { suffix: '公國' },
  'Grand Duchy of ': { suffix: '大公國' },
  'grand duchy of ': { suffix: '大公國' },
  'Archduchy of ': { suffix: '大公國' },
  'Principality of ': { suffix: '親王國' },
  'principality of ': { suffix: '親王國' },
  'Grand Principality of ': { suffix: '大親王國' },
  'Republic of ': { suffix: '共和國' },
  'republic of ': { suffix: '共和國' },
  'Sultanate of ': { suffix: '蘇丹國' },
  'sultanate of ': { suffix: '蘇丹國' },
  'Emirate of ': { suffix: '酋長國' },
  'emirate of ': { suffix: '酋長國' },
  'Caliphate of ': { suffix: '哈里發' },
  'Khanate of ': { suffix: '汗國' },
  'khanate of ': { suffix: '汗國' },
  'Beylik of ': { suffix: '貝伊國' },
  'County of ': { suffix: '伯國' },
  'county of ': { suffix: '伯國' },
  'Countship of ': { suffix: '伯國' },
  'countship of ': { suffix: '伯國' },
  'Earldom of ': { suffix: '伯國' },
  'Margraviate of ': { suffix: '邊伯國' },
  'Margraviate ': { suffix: '邊伯國' },
  'margraviate of ': { suffix: '邊伯國' },
  'Landgraviate of ': { suffix: '方伯國' },
  'Marquisate of ': { suffix: '侯爵領' },
  'marquisate of ': { suffix: '侯爵領' },
  'Lordship of ': { suffix: '領主國' },
  'lordship of ': { suffix: '領主國' },
  'Bishopric of ': { suffix: '主教區' },
  'Prince-Bishopric of ': { suffix: '親王主教區' },
  'prince-bishopric of ': { suffix: '親王主教區' },
  'Archbishopric of ': { suffix: '大主教區' },
  'Roman Catholic Diocese of ': { suffix: '天主教教區' },
  'Free City of ': { suffix: '自由市' },
  'Free Imperial City of ': { suffix: '帝國自由市' },
  'Free imperial city of ': { suffix: '帝國自由市' },
  'free imperial city of ': { suffix: '帝國自由市' },
  'Imperial City of ': { suffix: '帝國城市' },
  'imperial city of ': { suffix: '帝國城市' },
  'Imperial Abbey of ': { suffix: '帝國修道院' },
  'Imperial Court of ': { suffix: '帝國朝廷' },
  'Crown of ': { suffix: '王冠' },
  'Tsardom of ': { suffix: '沙皇國' },
  'tsardom of ': { suffix: '沙皇國' },
  'Despotate of ': { suffix: '專制國' },
  'despotate of ': { suffix: '專制國' },
  'Banate of ': { suffix: '班國' },
  'banate of ': { suffix: '班國' },
  'Voivodeship of ': { suffix: '伏伊伏丁那' },
  'House of ': { suffix: '家族' },
  'Realm of ': { suffix: '王國' },
  'realm of ': { suffix: '王國' },
  'State of ': { suffix: '邦' },
  'Province of ': { suffix: '行省' },
  'province of ': { suffix: '行省' },
  'Land van ': { suffix: '邦' },  // Dutch
  'Lands of the ': { suffix: '領地' },
  'Taifa of ': { suffix: '泰法王國' },
  'taifa of ': { suffix: '泰法王國' },
  'Tribal Duchy of ': { suffix: '部落公國' },
  'Signoria of ': { suffix: '領主國' },
  'Signoria di ': { suffix: '領主國' },
  'Spanish protectorate in ': { suffix: '西班牙保護地' },
  'Sheikhdom of ': { suffix: '酋長國' },
  'Sheikdom of ': { suffix: '酋長國' },
  'sheikhdom of ': { suffix: '酋長國' },
  'Provisional government of ': { suffix: '臨時政府' },
  'Provisional Government of ': { suffix: '臨時政府' },
  'Free State of ': { suffix: '自由邦' },
  'Free and Independent State of ': { suffix: '自由獨立邦' },
  'Confederation of ': { suffix: '聯盟' },
  'United States of ': { suffix: '合眾國' },
  'United Provinces of ': { suffix: '聯合省' },
  'Estado Libre del ': { suffix: '自由邦' },
  'Republic of the ': { suffix: '共和國' },
  'Democratic Republic of ': { suffix: '民主共和國' },
  'Federal Republic of ': { suffix: '聯邦共和國' },
  'Federation of ': { suffix: '聯邦' },
  'Federative Republic of ': { suffix: '聯邦共和國' },
  'Socialist Republic of ': { suffix: '社會主義共和國' },
  'Socialist Federal Republic of ': { suffix: '社會主義聯邦共和國' },
  "Worker's Socialist Republic of ": { suffix: '工人社會主義共和國' },
  "Worker's Socialist Respublic of ": { suffix: '工人社會主義共和國' },
  'People\'s Republic of ': { suffix: '人民共和國' },
  'Soviet Republic of ': { suffix: '蘇維埃共和國' },
  'Soviet Socialist Republic of ': { suffix: '蘇維埃社會主義共和國' },
  'Autonomous Republic of ': { suffix: '自治共和國' },
  'Islamic Republic of ': { suffix: '伊斯蘭共和國' },
  'Islamic government of ': { suffix: '伊斯蘭政府' },
  'Islamic Emirate of ': { suffix: '伊斯蘭酋長國' },
  'Khedivate of ': { suffix: '赫迪夫國' },
  'Eyalet of ': { suffix: '艾雅勒' },
  'Sanjak of ': { suffix: '桑賈克' },
  'Vilayet of ': { suffix: '維拉耶特' },
  'Pashalik of ': { suffix: '帕夏轄區' },
  'Beylik of ': { suffix: '貝伊國' },
  'beylik of ': { suffix: '貝伊國' },
  'Barony of ': { suffix: '男爵領' },
  'barony of ': { suffix: '男爵領' },
  'Viscounty of ': { suffix: '子爵領' },
  'viscounty of ': { suffix: '子爵領' },
  'Count of ': { suffix: '伯爵' },
  'Counts of ': { suffix: '伯爵' },
  'Mandala of ': { suffix: '曼荼羅國' },
  'Maharajadom of ': { suffix: '大君國' },
  'Rajadom of ': { suffix: '王國' },
  'Thakuratha of ': { suffix: '塔庫拉特' },
  'Sheikhdom of ': { suffix: '酋長國' },
  'Dukedom of ': { suffix: '公國' },
  'Crown colony of ': { suffix: '直屬殖民地' },
  'Crown Colony of ': { suffix: '直屬殖民地' },
  'Protectorate of ': { suffix: '保護國' },
  'protectorate of ': { suffix: '保護國' },
  'Pre-Colonial ': { suffix: '前殖民' },
  'Canton of ': { suffix: '坎頓' },
  'Chiefdom of ': { suffix: '酋邦' },
  'Duke of ': { suffix: '公爵' },
  'Commune of ': { suffix: '公社' },
  'Comune of ': { suffix: '公社' },
  'Comune di ': { suffix: '公社' },
  'Commonwealth of ': { suffix: '聯邦' },
  'Countship ': { suffix: '伯國' },
  'Château ': { suffix: '城堡' },
  'Château fort de ': { suffix: '城堡' },
  'crown of ': { suffix: '王冠' },
  'captalat de ': { suffix: '卡普塔特' },
  'Catholic Monarchy': { suffix: '天主教王國' },  // special: no place after
}

// 國名前綴保持前置（不移到後）
const PREFIX_KEEP_FRONT = {
  'Dutch ': '荷屬',
  'Portuguese ': '葡屬',
  'Spanish ': '西屬',
  'French ': '法屬',
  'British ': '英屬',
  'Italian ': '義屬',
  'German ': '德屬',
  'Roman ': '羅馬',
  'Russian ': '俄屬',
  'Soviet ': '蘇聯',
  'Ottoman ': '奧斯曼',
  'Mughal ': '蒙兀兒',
  'Byzantine ': '拜占庭',
  'Imperial ': '帝國',
  'Ancient ': '古',
  'Old ': '古',
  'Eastern ': '東',
  'Western ': '西',
  'Northern ': '北',
  'Southern ': '南',
  'Upper ': '上',
  'Lower ': '下',
  'Great ': '大',
  'Greater ': '大',
  'Lesser ': '小',
  'Old Kingdom of ': '古王國 ',
  'New Kingdom of ': '新王國 ',
  'Middle Kingdom of ': '中王國 ',
  'First ': '第一',
  'Second ': '第二',
  'Third ': '第三',
  'Fourth ': '第四',
  'Fifth ': '第五',
  'Provisional ': '臨時',
  'Interim ': '過渡',
  'Republic „Otto Luoghi": ': '八地 ',
  'United ': '聯合',
  'Confederate ': '邦聯',
}

function ruleTranslate(name) {
  // Prefix 模式（地名移到前，加後綴）
  for (const [prefix, { suffix }] of Object.entries(PREFIX_DICT)) {
    if (name.startsWith(prefix)) {
      const place = name.slice(prefix.length).trim()
      return place + ' ' + suffix
    }
  }
  // 國名前綴保持前置
  for (const [prefix, zhPrefix] of Object.entries(PREFIX_KEEP_FRONT)) {
    if (name.startsWith(prefix)) {
      const rest = name.slice(prefix.length).trim()
      // 後半可能本身有 suffix pattern，遞迴翻譯
      const restTranslated = MANUAL_TRANSLATIONS[rest] || ruleTranslate(rest) || rest
      return zhPrefix + restTranslated
    }
  }
  // Suffix 模式
  for (const [suffix, zhSuffix] of Object.entries(SUFFIX_DICT)) {
    if (name.endsWith(suffix)) {
      const stem = name.slice(0, name.length - suffix.length).trim()
      return stem + zhSuffix
    }
  }
  return null
}

// ===== Main =====
const states = JSON.parse(readFileSync(FILE, 'utf8'))

let filledManual = 0
let filledRule = 0

for (const s of states) {
  if (s.name_zh) continue
  // 1) Manual
  if (MANUAL_TRANSLATIONS[s.name_en]) {
    s.name_zh = MANUAL_TRANSLATIONS[s.name_en]
    filledManual += 1
    continue
  }
  // 2) Rule
  const r = ruleTranslate(s.name_en)
  if (r) {
    s.name_zh = r
    filledRule += 1
  }
}

writeFileSync(FILE, JSON.stringify(states))
const withZh = states.filter(s => s.name_zh).length
console.log(`Filled by manual table: ${filledManual}`)
console.log(`Filled by rule patterns: ${filledRule}`)
console.log(`Total with zh: ${withZh} / ${states.length} (${(withZh*100/states.length).toFixed(1)}%)`)
